### ISSUE TITLE
[Package Request]: PsExec

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#194783] opened 2024-11-27 19:07 UTC
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://learn.microsoft.com/en-us/sysinternals/downloads/psexec
Publisher: microsoft
Package Name: psexec
Description: Execute processes on remote systems.
Package Version: 2.43
Installer Url: https://download.sysinternals.com/files/PSTools.zip

**Comment by KarbitsCode** [comment] 2024-11-27 22:10
Already exists on [PsTools](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/Sysinternals/PsTools/)

**Comment by Dragon1573** [comment] 2024-12-01 17:16
> [!NOTE]
>
> Close with reason: **Duplicate request**.
>
> The package is already available in package identifier `Microsoft.Sysinternals.PsTools`.
>
> - See https://github.com/microsoft/winget-pkgs/issues/194783#issuecomment-2504881748

CC @soredake @stephengillie 🙏🏼

**Comment by stephengillie** [comment] 2024-12-02 18:39
Close with reason: Duplicate of #144385;

**Closed** 2024-12-02 18:40 UTC
Labels: Help-Wanted, Package-Request
