### ISSUE TITLE
Multiple apps found matching input criteria. Please refine the input.

### ISSUE THREAD

**Issue by liurunliang** [microsoft/winget-pkgs#586] opened 2020-05-21 07:43 UTC
winget install gimp.gimp
Multiple apps found matching input criteria. Please refine the input.
Name Id        Version
----------------------
GIMP gimp.gimp 2.10.18
GIMP Gimp.Gimp 2.10.0
please regulate submission of app 
don't let them to have same id

**Comment by VIKTORVAV99** [comment] 2020-05-21 08:28
The problem here isn't that thry use the same id cause they should because they should since it's the same app. (just two different versions)

The problem seems to be that it's case sensitive and one manifest is using all lowercase and the other is not.

**Comment by maxmichels** [comment] 2020-05-21 13:07
fixed with #582

**Comment by uaevuon** [comment] 2020-05-21 13:21
Duplicate of https://github.com/microsoft/winget-pkgs/issues/319

**Comment by denelon** [comment] 2021-01-06 17:24
This issue is resolved.

**Closed by denelon** 2021-01-06 17:24 UTC
