### ISSUE TITLE
[Package Request]: KDE.Kate.Release

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [microsoft/winget-pkgs#38936] opened 2021-12-26 14:33 UTC
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: KDE e.V.
Publisher Url: http://kde.org
Package Name: KDE.Kate.Release
Description: http://apps.kde.org/kate
Package Version: master-1514
Installer URL: http://binary-factory.kde.org/view/Windows%2064-bit/job/Kate_Release_win64/lastSuccessfulBuild/artifact/kate-21.12.0-1514-windows-msvc2019_64-cl-sideload.appx

Current Package Identifier (for new versions): master-1514

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2021-12-26 14:35
Although I have attempted to replace the current installer with one "APPX" package at "http://github.com/microsoft/winget-pkgs/pull/33731", I did not accomplish the replacement. Consequently, I am requesting assistance.

**Comment by OfficialEsco** [comment] 2021-12-29 16:23
Duplicate of #39190

Please post your KDE requests here

**Closed** 2021-12-29 16:29 UTC
Labels: Help-Wanted, Package-Request
