### ISSUE TITLE
[Update Request]: Update DuckStudio.FufuDevTools version 2024.10.01.0630

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-pkgs#189992] opened 2024-11-08 23:35 UTC
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

DuckStudio.FufuDevTools

### Package Version

2024.10.01.0630

### Please describe the changes you would like to see

[ReleaseNotes](https://github.com/DuckDuckStudio/Fufu_Dev_Tools/releases/tag/2024.10.01.0630) are changed:
![Image](https://github.com/user-attachments/assets/cc2e8bff-3b15-4703-bba3-0078b760d317)

**Comment by stephengillie** [comment] 2024-11-09 00:42
Close with reason: Duplicate of #189988;

**Closed** 2024-11-09 00:42 UTC
Labels: In-PR, Package-Metadata

**Comment by DuckDuckStudio** [comment] 2024-11-09 01:07
Maybe it not Duplicate with any issue...

**Comment by DuckDuckStudio** [comment] 2024-11-09 01:09
> Close with reason: Duplicate of #189988;

#189988 is update `DuckStudio.FufuTools`
And this issue is update `DuckStudio.FufuDevTools`
