### ISSUE TITLE
The Bot sometimes doesn't run properly

### ISSUE THREAD

**Issue by Reset12138** [microsoft/winget-pkgs#697] opened 2020-05-22 00:02 UTC
The bot didn't process the PRs [#544](https://github.com/microsoft/winget-pkgs/pull/544) and [#545](https://github.com/microsoft/winget-pkgs/pull/545) automatically.
However, after I commit the PR [#545](https://github.com/microsoft/winget-pkgs/pull/545) again and the bot run automatically.

**Comment by KevinLaMS** [comment] 2020-05-26 16:04
I think this is due to issue 494 that got resolved.
Duplicate of #494 
https://github.com/microsoft/winget-pkgs/issues/494

**Closed** 2020-05-26 16:18 UTC
