### ISSUE TITLE
[Package Request]: 

### ISSUE THREAD

**Issue by kuro68k** [microsoft/winget-pkgs#166983] opened 2024-08-09 10:44 UTC
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://freefilesync.org/download.php
Publisher: Zenju
Package Name: FreeFileSync
Description: Synchronize file and directories
Package Version: 13.7
Installer URL: https://freefilesync.org/download/FreeFileSync_13.7_Windows_Setup.exe

**Comment by Trenly** [comment] 2024-08-09 12:54
* Duplicate of #57900

**Closed** 2024-08-09 12:54 UTC
Labels: Help-Wanted, Package-Request
