### ISSUE TITLE
[Package Issue]: Package.Identifer

### ISSUE THREAD

**Issue by uzuki7777** [microsoft/winget-pkgs#109591] opened 2023-06-12 19:40 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Well this is strange. winget is suddenly telling me today to upgrade vlc player but vlc player says I'm uptodate and have 3.0.18. winget says I have 3.0.17 for some reason and it only just started doing that today. I even did the regedit trick which I have to do every time I update OBS but that also says 3.0.18 so I'm not sure where it's getting the old value from suddenly.

### Steps to reproduce

I just do the command winget upgrade in powershell. Still does it even if I reinstall vlc player.

### Actual behavior

It thinks I have vlc 3.0.17 when I have 3.0.18 and regedit also says 3.0.18.

### Expected behavior

It should be saying I'm uptodate!

### Environment

```raw
Windows Package Manager v1.4.11071
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3031
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.11071.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by ItzLevvie** [comment] 2023-06-12 19:41
Close with reason: Duplicate of Issue 109572;

**Closed** 2023-06-12 19:41 UTC
Labels: Issue-Bug, Needs-Triage
