### ISSUE TITLE
[Package Request]: Equalizer APO

### ISSUE THREAD

**Issue by vikingnope** [microsoft/winget-pkgs#145074] opened 2024-03-18 13:43 UTC
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://sourceforge.net/projects/equalizerapo/
Publisher: [jthedering](https://sourceforge.net/u/jthedering/profile/)
Package Name: Equalizer APO
Description: Equaliser for headphones
Package Version: 1.3.2
Installer URL: https://sourceforge.net/projects/equalizerapo/files/1.3.2/

**Comment by vikingnope** [comment] 2024-03-18 20:57
#145126

**Comment by Trenly** [comment] 2024-03-19 15:38
Duplicate of #9186

**Closed** 2024-03-19 15:38 UTC
Labels: Help-Wanted, Package-Request
