### ISSUE TITLE
Cannot upgrade Microsoft.VC++2015-2019Redist-x64

### ISSUE THREAD

**Issue by lunacd** [microsoft/winget-pkgs#27935] opened 2021-09-17 18:41 UTC
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

Cannot upgrade Microsoft.VC++2015-2019Redist-x64
# Steps to reproduce
winget upgrade Microsoft.VC++2015-2019Redist-x64

# Expected behavior
Microsoft.VC++2015-2019Redist-x64 upgrades.

# Actual behavior

```
Multiple installed packages found matching input criteria. Please refine the input.
Name                                                               Id
---------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2019 Redistributable (x64)               Microsoft.VC++2015-2019Redist-x64
Microsoft Visual C++ 2015-2019 Redistributable (x86) - 14.28.29913 {03d1453c-7d5c-479c-afea-8482f406e036}
```
# Environment

```none
Windows Package Manager v1.0.11692

Windows: Windows.Desktop v10.0.19043.1237
Package: Microsoft.DesktopAppInstaller v1.12.11692.0
```

**Comment by vedantmgoyal2009** [comment] 2021-09-18 02:47
I think if you use the `--exact` flag, it would resolve the issue.

**Comment by andyliuhaowen** [comment] 2021-09-18 05:05
Unfortunately it does not:

```
PS> winget upgrade Microsoft.VC++2015-2019Redist-x64 --exact
Multiple installed packages found matching input criteria. Please refine the input.
Name                                                               Id
---------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2019 Redistributable (x64)               Microsoft.VC++2015-2019Redist-x64
Microsoft Visual C++ 2015-2019 Redistributable (x86) - 14.28.29913 {03d1453c-7d5c-479c-afea-8482f406e036}
```

**Comment by OfficialEsco** [comment] 2021-09-21 12:05
Try now, the issue is probably caused by winget-cli stripping away x64/x86 and version from the PackageName.

**Comment by OfficialEsco** [comment] 2021-09-21 15:28
Not sure why `winget source refresh` didn't throw a error, but try `winget source update`
Technically `{03d1453c-7d5c-479c-afea-8482f406e036}` is linked to `Microsoft Visual C++ 2015-2019 Redistributable (x86)` so it should look at it as a different package..

**Comment by andyliuhaowen** [comment] 2021-09-21 15:39
Sorry, the command should be update. I typed here differently than I typed in the terminal. That's the full thing:
```
PS C:\Users\liuha> winget source update
Updating all sources...
Updating source: winget...
Done
PS C:\Users\liuha> winget upgrade Microsoft.VC++2015-2019Redist-x64 --exact
Multiple installed packages found matching input criteria. Please refine the input.
Name                                                               Id
---------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2019 Redistributable (x64)               Microsoft.VC++2015-2019Redist-x64
Microsoft Visual C++ 2015-2019 Redistributable (x86) - 14.28.29913 {03d1453c-7d5c-479c-afea-8482f406e036}
```

**Comment by OfficialEsco** [comment] 2021-09-21 15:48
@andyliuhaowen depending if you want to do this, you can try `winget upgrade --all` which should bypass this issue

@denelon any clue why `--exact` is not working/being ignored? We have had this issue for quite some time but i think these issues have been redirected from [winget-cli](https://github.com/microsoft/winget-cli) to [winget-pkgs](https://github.com/microsoft/winget-pkgs)

Issue 2; why is `Microsoft Visual C++ 2015-2019 Redistributable (x86) - 14.28.29913` not assigned ID `Microsoft Visual C++ 2015-2019 Redistributable`?

Issue 3: IIRC there are multiple issues with `winget upgrade <ID> <sub commands>`, IIRC example `winget upgrade <ID> --silent`

**Comment by andyliuhaowen** [comment] 2021-09-21 15:50
I'm waiting on the ability to pin a package to do `upgrade --all`. Following that features with all eagerness :)

**Comment by lychichem** [comment] 2021-09-22 09:02
> @andyliuhaowen depending if you want to do this, you can try `winget upgrade --all` which should bypass this issue
> 
> @denelon any clue why `--exact` is not working/being ignored? We have had this issue for quite some time but i think these issues have been redirected from [winget-cli](https://github.com/microsoft/winget-cli) to [winget-pkgs](https://github.com/microsoft/winget-pkgs)
> 
> Issue 2; why is `Microsoft Visual C++ 2015-2019 Redistributable (x86) - 14.28.29913` not assigned ID `Microsoft Visual C++ 2015-2019 Redistributable`?
> 
> Issue 3: IIRC there are multiple issues with `winget upgrade <ID> <sub commands>`, IIRC example `winget upgrade <ID> --silent`

I can answer question two, as I used to directly update current manifest but not create a new one. This is my fault.

**Comment by andyliuhaowen** [comment] 2021-11-17 06:18
Any update on this?

**Comment by OfficialEsco** [comment] 2021-11-17 08:45
@denelon can we get a roadmap for winget-pkgs?

winget-cli release seems to be `1.1.12653` while the pre-release is `1.1.12701`, however my client seems to be `1.2.3131-preview`?

According to this logic manifest schema `1.1.0` should be usable, and manifest schema `1.2.0` for whatever magic client i got?..

**Comment by OfficialEsco** [comment] 2021-11-17 12:49
Actually, i'm dumb, this is a winget-cli thing, its on the winget 1.3.0 milestone https://github.com/microsoft/winget-cli/milestone/37 which is ETA next year

**Comment by denelon** [comment] 2021-11-17 16:38
I'm probably going to have to move some of the 1.2 milestone work into 1.3. We have far less resources due to all the remaining PTO to get all the scope we were aiming for. I'm playing catch up right now to adjust estimates. We also have some internal engineering work related to changes with some of our dependent services that was unanticipated.

**Comment by andyliuhaowen** [comment] 2021-12-01 22:30
To update:
```
PS > winget upgrade
Name                                             Id                                Version        Available      Source
-----------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2013 Redistributable (x64)  Microsoft.VC++2013Redist-x64      12.0.30501.0   12.0.40664.0   winget
Microsoft Visual C++ 2008 Redistributable - x64  Microsoft.VC++2008Redist-x64      9.0.30729.4148 9.0.30729.6161 winget
Microsoft Visual C++ 2015-2022 Redistributable … Microsoft.VC++2015-2022Redist-x64 14.30.30704.0  14.31.30818.0  winget
...
7 upgrades available.
```

However:

```
PS > winget upgrade Microsoft.VC++2008Redist-x64
No installed package found matching input criteria.
PS > winget upgrade Microsoft.VC++2008Redist-x64 --exact
No installed package found matching input criteria.
```

```
PS > winget upgrade Microsoft.VC++2013Redist-x64
No installed package found matching input criteria.
PS > winget upgrade Microsoft.VC++2013Redist-x64 --exact
No installed package found matching input criteria.
```

```
PS > winget upgrade Microsoft.VC++2015-2022Redist-x64 --exact
No applicable update found.
PS > winget upgrade Microsoft.VC++2015-2022Redist-x64
No applicable update found.
```

**Comment by agowa338** [comment] 2021-12-25 00:19
Workaround uninstall until it's no longer listed via `winget uninstall --id Microsoft.VC++2015-2022Redist-x64` and then reinstall via `winget install --id Microsoft.VC++2015-2022Redist-x64`

But attention, the uninstall may reboot the computer without warning...

**Comment by andyliuhaowen** [comment] 2022-01-02 07:33
That helped. But this is what I found:

winget output:

```
PS > winget upgrade
Name                                                 Id                                Version       Available      Source
--------------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x86) Microsoft.VC++2015-2022Redist-x86 14.30.30704.0 14.31.30919.0  winget
2 upgrades available.
```

But:
![image](https://user-images.githubusercontent.com/35328328/147869185-5e27bdf3-a7df-4b17-82a8-585058e5c850.png)

It seems that winget incorrectly retrieved the 64-bit version number.

**Comment by denelon** [comment] 2022-01-03 17:35
The irony that it's a Microsoft package is not lost on us. We've been working through the matching logic both in terms of the new schema entries for Apps & Features as well as some additional logic for better matching when strings reported in Apps & Features depend on architecture.

**Comment by thevirajshelke** [comment] 2022-01-08 10:08
I am having the same issue,

When I run the following command `winget upgrade` I see the following

```bash
Name                                            Id                           Version          Available        Source
---------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2008 Redistributable - x64 Microsoft.VC++2008Redist-x64 9.0.30729.4148   9.0.30729.6161   winget
```

After that when I try to run `winget upgrade --id Microsoft.VC++2008Redist-x64` I can see the following

```bash
Multiple installed packages found matching input criteria. Please refine the input.
Name                                                           Id
-----------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2008 Redistributable - x64                Microsoft.VC++2008Redist-x64
Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.6161 {5FCE6D76-F5DC-37AB-B2B8-22AB8CEDB1D4}
Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.6161 {9BE518E6-ECC6-35A9-88E4-87755C07200F}
```
This doesn't make any sense right? It (`winget`) should have chosen the first one, isn't it? Since the `Id` is different for all the packages! Moreover the string-based alphanumeric `Id` (`Microsoft.VC++2008Redist-x64`) is what gave the issue in the first place how come it is still the part of the output? The other two `Id` which are GUIDs may make sense as the output! Which brings me to my next question can't we pass GUID as input to `winget upgrade --id` ? Something like `winget upgrade --id 5FCE6D76-F5DC-37AB-B2B8-22AB8CEDB1D4`. Didn't work for me I got `No installed package found matching input criteria.`. Isn't me specifing a GUID "refine the  input"?

Anyone any insights?

**Comment by OfficialEsco** [comment] 2022-01-08 10:23
The issue comes from winget-cli stripping away x64/x86 and the version number so it only sees `Microsoft Visual C++ 2008 Redistributable` = 2 matches.

However its a bit weird because `winget upgrade` and `winget list` can spot the update (possibly because of the ID), but when you do `winget upgrade Microsoft.VC++2008Redist-x64` it updates `Microsoft Visual C++ 2008 Redistributable` (x64) to `9.0.30729.6161`, but when when you try to update `Microsoft.VC++2008Redist-x86` to `9.0.30729.6161` it sees that `Microsoft Visual C++ 2008 Redistributable` (x64) is already up to date...

The second issue here is that it installed `9.0.30729.6161` and left `9.0.30729.4148` installed so you currently have 2 `Microsoft Visual C++ 2008 Redistributable - x64` installed.

I was actually looking at this package yesterday and saw no critical reason to update other than the UpgradeBehaviour which coincidentally affected you 🤔

**Comment by denelon** [comment] 2024-04-30 18:28
Several other issues are tracking issues related to VC Runtimes and side-by-side. I'm closing this issue in favor of the work over at the CLI.

**Closed by denelon** 2024-04-30 18:28 UTC
Labels: Help-Wanted
