### ISSUE TITLE
[New Feature]: Winget could add DisplayVersion if the installer does not

### ISSUE THREAD

**Issue by JustMyGithub** [microsoft/winget-pkgs#109910] opened 2023-06-15 20:21 UTC
### Description of the new feature/enhancement

Hey there. Recently I noticed that winget does work correctly as expected when I manually set the DisplayVersion registry value of a setup that doesn't - so why not make winget set it? As it does a hash check, winget verifies the correct version number of the software it installs (if the manifest is correct). 

For the setup I tested, a re-install did even remove the DisplayVersion value, so if the user (or anything else) does an update, the value is removed (and not wrong)

Even if there was a setup that does not delete the DisplayVersion, the worst thing that can happen is that winget installs the same version again - which is exactly what happens now.

**Comment by quhxl** [comment] 2023-06-15 22:22
Duplicate of [winget-cli#2294](https://github.com/microsoft/winget-cli/issues/2294)

**Comment by ItzLevvie** [comment] 2023-06-15 23:46
Close with reason: See above;

**Closed** 2023-06-15 23:47 UTC
Labels: Issue-Feature, Needs-Triage
