### ISSUE TITLE
Pull request #158282 approved, but still not merged

### ISSUE THREAD

**Issue by DeusMaximus** [microsoft/winget-pkgs#158565] opened 2024-06-18 22:58 UTC
Hey guys, it seems like the bot is somewhat stuck with pull request #158282 

Initially this pull request had two issues - release notes were in the previous manifest but weren't in the current one when generated by wingetcreate, and that was shortly edited afterwards.

The second issue was to do with domain validation, and this was worked around by @stephengillie.

This has since been approved, and is ready to merge but 4 hours later, it still sits unmerged with the bot removing and readding the "validation completed" tag and re-approving the already approved merge.

**Comment by Trenly** [comment] 2024-06-18 23:11
Duplicate of #142854

**Closed** 2024-06-18 23:11 UTC
