### ISSUE TITLE
[Package Request]: KDE-Elisa

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#39647] opened 2022-01-02 13:14 UTC
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: KDE
Publisher Url: https://elisa.kde.org/
Package Name: KDE Elisa
Description: music player by KDE
Package Version: 21.12
Installer URL: https://binary-factory.kde.org/view/Windows%2064-bit/job/Elisa_Release_win64/lastSuccessfulBuild/artifact/elisa-21.12.0-998-windows-msvc2019_64-cl.exe

Current Package Identifier (for new versions): 21.12

**Comment by ItzLevvie** [comment] 2022-01-02 13:25
Duplicate of https://github.com/microsoft/winget-pkgs/issues/39190

**Comment by OfficialEsco** [comment] 2022-01-02 14:42
Duplicate of #39190

Since the bot don't seem to like Levvie 🤷‍♂️
We currently have issues with keeping KDE up to date which is why they are not added.

**Closed by OfficialEsco** 2022-01-02 14:42 UTC
Labels: Help-Wanted, Package-Request, Needs-Triage
