### ISSUE TITLE
[Bug]: GOG.Galaxy installer does not register DisplayVersion

### ISSUE THREAD

**Issue by robross0606** [microsoft/winget-pkgs#30134] opened 2021-10-12 13:54 UTC
### Brief description of your issue

winget reports "GOG.Galaxy" version "2.0.40.1" is available to install.  Installing this registers the application but with no `DisplayVersion` property in the registry.  This causes a subsequent call to `winget upgrade` to continuously report an upgrade is available for the package.

### Steps to reproduce

1. `winget install -e GOG.Galaxy`
2. `winget upgrade` will continuously report an upgrade is available for "Gog.Galaxy".
4. Edit registry and add "DisplayVersion" key to install information for GOG Galaxy as "2.0.40.1"
5. `winget upgrade` will no longer report an upgrade is available for "Gog.Galaxy".

### Expected behavior

GOG Galaxy would register the "DisplayVersion" so that `winget` does not continuously try to update it.  Additionally, `winget` should not keep trying to install something that doesn't report a current version by default.  Perhaps with some sort of flag to control behavior.

### Actual behavior

`winget upgrade` continuously report an upgrade is available for "Gog.Galaxy" even though latest was just installed via `winget`.

### Environment

```shell
Windows Package Manager v1.1.12653
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1266
Package: Microsoft.DesktopAppInstaller v1.16.12653.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by pavll** [comment] 2021-11-10 21:50
Just found this RegKey: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\GOG.com\GalaxyClient
seems to be the place where the GOG Galaxy people thought they should put their version number...

**Comment by pavll** [comment] 2021-11-10 22:00
### **Fix**:  
- create a file called "gog_galaxy_version_fix.reg" and put this in:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{7258BA11-600C-430E-A759-27E2C691A335}_is1]
"DisplayVersion"="2.0.43.71"
```
- Replace the content of "DisplayVersion" with the current version from `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\GOG.com\GalaxyClient` it's `version` key.
- Maybe "{7258BA11-600C-430E-A759-27E2C691A335}_is1" is something other on your PC so check if "{7258BA11-600C-430E-A759-27E2C691A335}_is1" contains the key "DisplayName" = "GOG Galaxy".

**Comment by robross0606** [comment] 2021-11-10 22:29
That is a workaround, not a “fix”.  It will break the second you update GOG Galaxy again.

**Comment by Toby-Broom** [comment] 2021-12-04 21:32
I made a bug to GOG [https://mantis2.gog.com/view.php?id=162317](url)

**Comment by jedieaston** [comment] 2021-12-04 22:07
The infinite upgrading should be bandaided (if not completely fixed) by: https://github.com/microsoft/winget-cli/pull/1765

**Comment by BraINstinct0** [comment] 2022-01-15 12:59
In regards to https://github.com/microsoft/winget-pkgs/issues/30134#issuecomment-965805170 :
```
(Get-ItemProperty -Path HKLM:\SOFTWARE\WOW6432Node\GOG.com\GalaxyClient -Name version).version
```
would be a working PS script to get the version.
Setting the new registry value using the value (**PowerShell must be run as ADMIN**):
```
New-ItemProperty -Path "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{7258BA11-600C-430E-A759-27E2C691A335}_is1" -Name DisplayVersion -Value ((Get-ItemProperty -Path HKLM:\SOFTWARE\WOW6432Node\GOG.com\GalaxyClient -Name version).version) -Force
```

**Comment by OfficialEsco** [comment] 2022-01-20 21:45
Duplicate of https://github.com/microsoft/winget-pkgs/pull/38887

**Comment by vedantmgoyal2009** [comment] 2022-01-21 04:56
@OfficialEsco Duplicate of https://github.com/microsoft/winget-pkgs/issues/27206

**Comment by BraINstinct0** [comment] 2022-02-17 23:38
> HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{7258BA11-600C-430E-A759-27E2C691A335

Still working for the latest update.(No reason to stop working tho)

**Comment by denelon** [comment] 2022-06-09 17:42
Duplicate of #27206

**Closed by denelon** 2022-06-09 17:42 UTC
Labels: Issue-Bug, Area-External
