### ISSUE TITLE
Does winget can use this one as a payload because that file is linking the location to over there?

### ISSUE THREAD

**Issue by BrandonWanHuanSheng** [microsoft/winget-pkgs#117375] opened 2023-08-19 03:27 UTC
### Description of the new feature/enhancement

It look like https://download.geogebra.org/installers/6.0 is a payload for GeoGebra-6.0 installers. Does winget available to read their content in the directory. Also, another application also use payload to determine the location of the installer.  Mozilla is also the one use payload. Does the payload can change the hashes during the update?

**Comment by BrandonWanHuanSheng** [comment] 2023-08-19 03:33
Also, wget can read the directory from the config file https://download.geogebra.org/installers/6.0 but the robots need to be turned off just able to detect the installer location correctly..

**Comment by Trenly** [comment] 2023-08-19 03:37
Winget does not have any crawling ability or ability to parse directories to check for new versions. The only way for winget to create automatic updates is when the hash at an existing InstallerUrl changes

**Comment by BrandonWanHuanSheng** [comment] 2023-08-19 03:40
But wget have ability to do this wget -e robots=off -r https://download.geogebra.org/installers/6.0/

**Comment by Trenly** [comment] 2023-08-19 03:40
* Duplicate of #500

**Closed** 2023-08-19 03:41 UTC
Labels: Issue-Feature
