### ISSUE TITLE
Winget source update error

### ISSUE THREAD

**Issue by lychichem** [microsoft/winget-pkgs#96351] opened 2023-02-12 01:36 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

The server that stores winget source has an expired certificate, and winget cannot update source.

此服务器无法证明它是 cdn.winget.microsoft.com；它的安全证书已于昨天到期。这可能是错误配置或攻击者截获连接而导致。计算机的时钟当前设置为 2023年2月12日星期日。显示的时间是否正确？如果不正确，则应更正系统时钟，然后刷新此页面。

### Steps to reproduce

winget upgrade

### Actual behavior

source update error

### Expected behavior

should update source

### Environment

```shell
Windows 程序包管理器(预览) v1.5.101-preview
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.22621.1194
系统体系结构: X64
软件包: Microsoft.DesktopAppInstaller v1.20.101.0

日志: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

用户设置: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

链接
----------------------------------------------------------------------------
隐私声明             https://aka.ms/winget-privacy
许可协议             https://aka.ms/winget-license
第三方声明           https://aka.ms/winget-3rdPartyNotice
主页                 https://aka.ms/winget
Windows 应用商店条款 https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/9316590/218288350-53f5d94c-fb3e-4470-a3ea-4c9458f8c552.png)
![image](https://user-images.githubusercontent.com/9316590/218288397-c68877dd-437b-417d-9ffd-83580a80d23a.png)

**Comment by lychichem** [comment] 2023-02-12 01:37
@denelon

**Comment by Trenly** [comment] 2023-02-12 02:27
Duplicates https://github.com/microsoft/winget-cli/issues/2956

**Comment by denelon** [comment] 2023-02-12 07:09
Duplicate of https://github.com/microsoft/winget-cli/issues/2956

**Closed** 2023-02-12 07:18 UTC
Labels: Issue-Bug, Needs-Triage
