### ISSUE TITLE
voidtools.Everything.Lite updated to latest version but winget keeps showing update available

### ISSUE THREAD

**Issue by jmaraujouy** [microsoft/winget-pkgs#88726] opened 2022-11-16 05:49 UTC
### Brief description of your issue

Winget shows that an update is available, even though the software is up to date with the latest version. (id="voidtools.Everything.Lite" version="1.4.1.1022")

`winget upgrade`
```
Name                             Id                        Version      Available  Source
-----------------------------------------------------------------------------------------
Everything 1.4.1.1022 Lite (x64) voidtools.Everything.Lite < 1.4.1.1015 1.4.1.1022 winget
1 upgrade available.
```

### Steps to reproduce

`winget install "voidtools.Everything.Lite"`
`winget upgrade`

### Expected behavior

No available updates should be displayed (with "_winget upgrade_") if the latest version is already installed.

### Actual behavior

Winget shows that an update is available, even though the software is up to date with the latest version.

### Environment

```shell
Administrador de paquetes de Windows v1.3.2691
Copyright (c) Microsoft Corporation. Todos los derechos reservados.

Windows: Windows.Desktop v10.0.22621.819
Arquitectura del sistema: X64
Paquete: Microsoft.DesktopAppInstaller v1.18.2691.0

Registros: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

**Comment by Trenly** [comment] 2022-11-17 18:28
@jmaraujouy - Can you provide the output of `winget list Everything` ?

**Comment by jmaraujouy** [comment] 2022-11-17 19:10
Yes, sure. ;)

`winget list Everything`

```
Nombre                           Id                        Versión      Disponible Origen
-----------------------------------------------------------------------------------------
Everything 1.4.1.1022 Lite (x64) voidtools.Everything.Lite < 1.4.1.1015 1.4.1.1022 winget
```

**Comment by jmaraujouy** [comment] 2022-12-23 13:09
I just noticed that the [manifest for v1.4.1.2022](https://github.com/microsoft/winget-pkgs/blob/master/manifests/v/voidtools/Everything/1.4.1.1022/voidtools.Everything.installer.yaml) shows "DisplayName: Everything 1.4.1.**1021**" six times.

It should be 1.4.1.1022.

**Comment by jmaraujouy** [comment] 2022-12-28 10:20
Hello, @Dragon1573 

Can you please fix the version number? (See my previous message)

I have no idea on how to make a pull request.

**Comment by Dragon1573** [comment] 2022-12-28 16:29
> Can you guys please fix the version number? (See my previous message)

Em ...

I'm not sure if I can achieve it and fix this issue, but I think it worth a try.

**Comment by Dragon1573** [comment] 2022-12-29 03:54
@jmaraujouy ARP entries of `voidtools.Everything` is successfully fixed. But our problem here is about `voidtools.Everything.Lite`. I think you have searched a wrong place 😕

In the [`installer.yaml`](https://github.com/microsoft/winget-pkgs/blob/master/manifests/v/voidtools/Everything/Lite/1.4.1.1022/voidtools.Everything.Lite.installer.yaml) of `voidtools.Everything.Lite` with version `1.4.1.1022`, all ARP entries information seems correct. There's no "version number" issue as [your comments](https://github.com/microsoft/winget-pkgs/issues/88726#issuecomment-1363940816) above.

There should be something else causing the problem. No idea how to fix it ...

**Comment by ajkajk** [comment] 2023-01-19 13:59
This problem is still there.  I tried creating a new (as simple as I could make it) manifest and testing with that.  `winget` still didn't see the installed version.  

I think there is some problem with the way `winget` is identifying the installed version.  Looking at the registry, version information is there.  

Should a problem be raised against `winget-cli`?

**Comment by ajkajk** [comment] 2023-01-19 18:19
> > This problem is still there. I tried creating a new (as simple as I could make it) manifest and testing with that. `winget` still didn't see the installed version.
> > I think there is some problem with the way `winget` is identifying the installed version. Looking at the registry, version information is there.
> > Should a problem be raised against `winget-cli`?
> 
> What happens if you run `winget list Everything`

```
λ winget list everything                                                                   
Name                             Id                        Version      Available  Source  
-----------------------------------------------------------------------------------------  
Everything 1.4.1.1022 Lite (x64) voidtools.Everything.Lite < 1.4.1.1015 1.4.1.1022 winget  
```

**Comment by ajkajk** [comment] 2023-01-19 20:20
I don't know if winget still looks for DisplayVersion in the registry.  The MSI installer for Everything Lite sets: 

`"DisplayVersion"="1.4.1.1022"` in `[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{2910A105-C9DA-45B0-97A5-F149D4773C23}]`.  

It also sets up 
```
"VersionMajor"=dword:00000001
"VersionMinor"=dword:00000004
"Version"=dword:01040001
```
`settings/Apps & Features` displays the version number correctly.

The exe installer sets up: 

`"DisplayVersion"="1.4.1.1022"` but in key `[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Everything]`

Again `settings/Apps & Features` displays the version number correctly.  However the version of Everything Lite as set up by this installer is again not recognised by winget.

Is there some confusion arising from the use of `Everything` and `Everything Lite` i.e. is winget looking for and not finding keys associated with `Everything Lite` rather than `Everything`?

(As an aside a similar problem arises with the Windows SDK, where after Visual Studio updates the SDK winget starts reporting an incorrect need to update - if we ever sort out Everything I'll check back on that.)

**Comment by mdanish-kh** [comment] 2023-01-20 21:04
The issue here is related to https://github.com/microsoft/winget-pkgs/issues/91888#issuecomment-1380817845.
The versions <= [1.4.1.1017](https://github.com/microsoft/winget-pkgs/tree/master/manifests/v/voidtools/Everything/Lite) had inconsistent versioning scheme for the MSI Installers that forced us to use `DisplayVersion` in these manifests. https://github.com/microsoft/winget-pkgs/blob/d2baaa3a64bc8c164403ab25e128917e75019701/manifests/v/voidtools/Everything/Lite/1.4.1.1017/voidtools.Everything.Lite.installer.yaml#L24-L25

This got fixed by the publisher in subsequent versions where PackageVersion == DisplayVersion, so this field was no longer required. As stated in https://github.com/microsoft/winget-pkgs/issues/91888#issuecomment-1380817845, there are strange behaviors if some manifests contain DisplayVersion and others don't.

Per my understanding, the potential solutions are:

1) Remove versions prior than `1.4.1.1020` that use DisplayVersion because of inconsistent versioning by the publisher.

*OR*

2) While the engineers advise against using DisplayVersion when it's equal to PackageVersion, adding DisplayVersion to all manifests may resolve the issue.

**Comment by mdanish-kh** [comment] 2023-01-20 21:08
cc @denelon Could you please confirm this with an engineer?

**Comment by denelon** [comment] 2023-01-20 21:49
Yes,

In general, the advice is:

1) If we need to have separate "packageVersion" and "displayVersion" values for one version of a package, then all manifests for that package should have "displayVersion".

2) If we do not need separate "packageVersion" and "displayVersion" values for any version of a package, then all manifests for that package should not have "displayVersion".

**Comment by ajkajk** [comment] 2023-01-21 10:01
Have I got this right.  

1. This is a fault with the manifest and should have been picked up when testing the manifest.   
2. When I create a manifest which looks good and validates fine, it may not give the right behaviour because of the way previous manifests, which I have not looked at, have been set up. I may need to visit previous manifests when creating my new manifest.
3. The winget program cannot/will not be changed to allow a correct manifest associated with a correct installer to work correctly if a previous manifest had to be tweaked to cater for a deficient installer.

**Comment by ajkajk** [comment] 2023-01-21 10:15
Sorry - I should have added thank you for fixing this @[mdanish-kh](https://github.com/mdanish-kh)

**Comment by Trenly** [comment] 2023-01-21 14:54
> 3\. The winget program cannot/will not be changed to allow a correct manifest associated with a correct installer to work correctly if a previous manifest had to be tweaked to cater for a deficient installer.

I would say this isn’t entirely correct. There has been an issue filed over at [winget-cli](/microsoft/winget-cli) around this bug - https://github.com/microsoft/winget-cli/issues/2503.

> 1. This is a fault with the manifest and should have been picked up when testing the manifest.

Yes, kind of, but mostly no. The automated manifest tests don’t include an upgrade scenario, but there are requests open for this. The manifest was entirely correct, and actually installs fine, it just results in that upgrade loop. The tricky part is that in order to know if it will result in an upgrade loop, it has to be added into the source to see how the search results will come back, which requires it to be merged and published. Its a bit of a circular logic problem. 

> 2\. When I create a manifest which looks good and validates fine, it may not give the right behaviour because of the way previous manifests, which I have not looked at, have been set up.

Yes, this is true. However, this usually only effects a few packages. Using tools such as wingetcreate or YamlCreate also helps reduce the likelihood of this happening will generally prevent incorrect behaviors, but it isn’t a guarantee since someone else may submit a manifest that results in an incorrect behavior that gets propogated forward.

> I may need to visit previous manifests when creating my new manifest.

Its not a bad idea to do this, but it isn’t required to do so. Because these behavior issues only occur in very specific conditions, once they are fixed they generally remain fixed, even as new versions are added. Even if they do occur, filing an issue here can result in it being resolved quickly. I did open https://github.com/microsoft/winget-pkgs/issues/92688 a little while ago which does suggest that the automated pipelines check for differences between the latest and previous manifest, but I'm sure that will take some time to be implemented (if ever)

**Comment by mdanish-kh** [comment] 2023-01-21 20:49
> Sorry - I should have added thank you for fixing this @[mdanish-kh](https://github.com/mdanish-kh)

The issue still persists - The only thing stopping me from creating PRs to add DisplayVersion to every manifest is I am unsure to how winget will sort these versions. I may end up creating another issue where users get an older version as the "latest" one if winget thinks `1.4.1017` > `1.4.1.1022`. I believe winget's implementation mimics semver as much as it can and online tools for version string comparisons as per semver show that `1.4.1017` is > `1.4.1.1022`. I may have to resort to solution#1 for removing older manifests with inconsistent versioning

**Comment by ajkajk** [comment] 2023-01-22 13:30
> The issue still persists 
Ah I was being a little premature.  I should have been more cautious and said the issue is fixed for me on one machine at the moment....

**Comment by denelon** [comment] 2023-01-23 19:21
@mdanish-kh WinGet will evaluate the version in the "displayVersion" key.

Yes, the following expression is true for WinGet version comparison:

`1.4.1017 > 1.4.1.1022`

Removing versions that cause WinGet's evaluation logic to produce undesirable results is likely the best action to take for users.

**Comment by ajkajk** [comment] 2023-01-23 20:30
Yes - I get exactly the same as you now.  Thank you again.

**Comment by mdanish-kh** [comment] 2023-01-24 18:19
Close with reason: Resolved by removing old manifests causing version range issues;

**Closed** 2023-01-24 18:19 UTC
Labels: Help-Wanted

**Comment by jmaraujouy** [comment] 2023-01-25 08:10
> Resolved in above PRs. @jmaraujouy @Dragon1573 @ajkajk Please check your output of `winget list everything`
> 
> ```powershell
> ~ winget list everything
> Name                             Id                        Version    Source
> -----------------------------------------------------------------------------
> Everything 1.4.1.1022 Lite (x64) voidtools.Everything.Lite 1.4.1.1022 winget
> ```

Yes, its solved now. A big thank you to all involved in fixing this issue.
