### ISSUE TITLE
[Package Request]: 

### ISSUE THREAD

**Issue by anyuzu99** [microsoft/winget-pkgs#67361] opened 2022-07-24 12:29 UTC
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: MSI
Publisher Url: https://www.msi.com/Landing/afterburner/graphics-cards
Package Name: Afterburner
Description: MSI Afterburner is the most used graphics card software for a good reason.
Package Version: 4.6.3.16255
Installer URL: https://download.msi.com/uti_exe/vga/MSIAfterburnerSetup.zip
Current Package Identifier (for new versions): 

it is the most popular gpu overclocking softward in the world. although it is a .zip file, it will be a .exe after extracted.

**Comment by ItzLevvie** [comment] 2022-07-24 12:31
Duplicate of https://github.com/microsoft/winget-pkgs/issues/1990

**Closed** 2022-07-24 12:32 UTC
Labels: Help-Wanted, Package-Request, Needs-Triage
