### ISSUE TITLE
install XYplorer from winget report that hash not match

### ISSUE THREAD

**Issue by ali50m** [microsoft/winget-pkgs#175129] opened 2024-09-25 06:12 UTC
### Brief description of your issue

install XYplorer from winget report that hash not match.

```
winget install CologneCodeCompany.XYplorer
```

![图片](https://github.com/user-attachments/assets/c1605741-3dff-46b3-b0f0-b41a1618bc4b)

### Steps to reproduce

install XYplorer in winget through Windows Terminal/Powershell

### Expected behavior

install successfully.

### Actual behavior

install failed. report that "安装程序哈希不匹配。"

### Environment

```shell
Winget v1.8.1911
Windows: Windows.Desktop v10.0.19044.4894
CologneCodeCompany.XYplorer: 26.40.0200
WT: 1.21.2361.0
PowerShell 7.4.5
```

**Comment by Dragon1573** [comment] 2024-09-26 15:12
Reproduced.

```text
23:01:53 C:\...\winget-pkgs  [master ≡] 2ms pwsh> komac.exe show CologneCodeCompany.XYplorer
PackageIdentifier: CologneCodeCompany.XYplorer
PackageVersion: 26.40.0200
InstallerLocale: en-US
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
UpgradeBehavior: install
Commands:
- xyplorer
Installers:
- Architecture: x64
  InstallerUrl: https://www.xyplorer.com/download/XYplorer_26.40_Install.exe
  InstallerSha256: 0ABD5D3C6F12A2CFA62D3AF1481AEBBB92F63B32353ADB5CCE5D08FAC4CD5D29
ManifestType: installer
ManifestVersion: 1.6.0

PackageIdentifier: CologneCodeCompany.XYplorer
PackageVersion: 26.40.0200
PackageLocale: en-US
Publisher: Donald Lessau, Cologne Code Company
PublisherUrl: https://www.xyplorer.com/
PublisherSupportUrl: https://www.xyplorer.com/support.php
Author: Donald Lessau
PackageName: XYplorer
PackageUrl: https://www.xyplorer.com/
License: Proprietary
LicenseUrl: https://www.xyplorer.com/LicenseXY.txt
Copyright: Copyright © 1997 by Donald Lessau
ShortDescription: XYplorer is a file manager for Windows
Description: XYplorer is a file manager for Windows. It features tabbed browsing, a powerful file search, a versatile preview, a highly customizable interface, optional dual pane, and a large array of unique ways to efficiently automate frequently recurring tasks. It's fast and light, it's innovative, and it's portable.
Moniker: xyplorer
Tags:
- file-manager
- xyplorer
PurchaseUrl: https://www.xyplorer.com/purchase.php
ManifestType: defaultLocale
ManifestVersion: 1.6.0

PackageIdentifier: CologneCodeCompany.XYplorer
PackageVersion: 26.40.0200
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0

23:04:20 C:\...\winget-pkgs  [master ≡] 1.958s pwsh> winget download --id CologneCodeCompany.XYplorer
已找到 XYplorer [CologneCodeCompany.XYplorer] 版本 26.40.0200
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://www.xyplorer.com/download/XYplorer_26.40_Install.exe
  ██████████████████████████████  6.33 MB / 6.33 MB
安装程序哈希不匹配。
```

**Comment by stephengillie** [comment] 2024-09-26 17:04
Since https://github.com/microsoft/winget-pkgs/pull/175287 is merged, I'll close this as complete. If this is in error, please @ me and I'll reopen.

**Closed by stephengillie** 2024-09-26 17:04 UTC
Labels: In-PR, Help-Wanted, Error-Hash-Mismatch, Package-Update
