### ISSUE TITLE
[Package Issue]: Microsoft.WindowsTerminal

### ISSUE THREAD

**Issue by thunderstatic** [microsoft/winget-pkgs#60858] opened 2022-05-15 14:06 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The attempt to install the latest version of Windows Terminal on Windows 10 system ends up with «**No applicable installer found**» error. 
That happens cause the manifest of this version contains installer URLs only for Win11 platform. You can see it clearly after downloading and trying to run the installer manually, as I showed on 2nd screenshot.
Since the official repository of Windows Terminal contains Win10 installer, is there any way to fix this issue?

### Steps to reproduce

Run `winget install --id Microsoft.WindowsTerminal` in cmd or PowerShell.

### Actual behavior

Error caused by missing an applicable installer.

### Expected behavior

An option to choose the right installer for your current OS or automatic successful installation.

### Environment

```shell
Windows Package Manager v1.2.10271
Windows: Windows.Desktop v10.0.19044.1706
Package: Microsoft.DesktopAppInstaller v1.17.10271.0
```

### Screenshots and Logs

![cmd log](https://user-images.githubusercontent.com/47780366/168475830-4232a4c5-68fa-4f30-abb6-1c770be9a1f5.png)
![installer log](https://user-images.githubusercontent.com/47780366/168475870-6dcfd240-ef3e-473e-bf29-943573ced895.png)
![current manifest](https://user-images.githubusercontent.com/47780366/168476507-de3fad58-45e8-4f8d-9c82-2f044db0a953.png)
![wt releases](https://user-images.githubusercontent.com/47780366/168476510-98eea201-116b-4159-a782-2f047f30c753.png)

**Comment by ItzLevvie** [comment] 2022-05-15 14:47
Duplicate of https://github.com/microsoft/winget-cli/issues/2134.

**Comment by thunderstatic** [comment] 2022-05-15 15:04
@ItzLevvie Ouch. I've read all this topic already: https://github.com/microsoft/winget-pkgs/issues/36878
Here, I described the issue in more detail and wanted to find out if there is an accurate solution. So far as the decision to manually pick the older version of the software with a suitable manifest doesn't seem right to me, especially when we have the latest release in two clicks from here.
But with this great discussion, which I missed in my search, I think I can close that topic.

**Closed** 2022-05-15 15:30 UTC
Labels: Issue-Bug, Needs-Triage
