### ISSUE TITLE
Battle.net

### ISSUE THREAD

**Issue by IanFreas** [microsoft/winget-pkgs#154435] opened 2024-05-21 02:41 UTC
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://download.battle.net/en-us/?platform=windows
Publisher: Blizzard Entertaiment INC 
Package Name: Battle.net
Description: Installer for Battle.net
Package Version: 1.18.10.3141
Installer URL: https://downloader.battle.net/download/getInstallerForGame?os=win&gameProgram=BATTLENET_APP&version=Live

**Comment by Trenly** [comment] 2024-05-21 17:55
* Duplicate of #60622

**Closed** 2024-05-21 17:55 UTC
Labels: Help-Wanted, Package-Request
