### ISSUE TITLE
[Package Issue]: Martchus.syncthingtray does not create syncthungtray command

### ISSUE THREAD

**Issue by martianrock** [microsoft/winget-pkgs#132145] opened 2023-12-29 21:35 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

package is supposed to install syncthingtray command/alias, it does not.
winget install prints this line:
```Command line alias added: "syncthingtray"```
However, that alias is not found (after reloading shell to pick new path).  `syncthingtray-1.4.11-x86_64-w64-mingw32.exe` can be launched, but `syncthingtray` can't:

```
﬌  syncthingtray
syncthingtray: The term 'syncthingtray' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

﬌
```
New directory with binaries is added to env:PATH. But alias does not get added.

Content of the added path after install:
```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a---        12/11/2023   9:14 PM         962062 ﬓ  syncthingtray-1.4.11-x86_64-w64-mingw32-cli.exe
-a---        12/11/2023   9:25 PM         708465   syncthingtray-1.4.11-x86_64-w64-mingw32-LICENSES.md
-a---        12/11/2023   9:14 PM       59621406 ﬓ  syncthingtray-1.4.11-x86_64-w64-mingw32.exe

```
%localAppData%\Microsoft\WinGet\Links\ is empty after install

Logs have "[CORE] Failed to create symlink at: C:\Users\LaptopUser\AppData\Local\Microsoft\WinGet\Links\syncthingtray.exe" line

### Steps to reproduce

1. `winget install syncthingtray` in a powershell window to install syncthingtray
2. restart shell to pick up new env:PATH
3. type `synctingtray` in powershell window
4. alias is not found, syncthingtray is not launched

### Actual behavior

`syncthingtray` command is not found

### Expected behavior

`syncthingtray` can be used to launch the app after install

### Environment

```raw
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2861
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0
```

### Screenshots and Logs

2023-12-29 09:38:55.084 [CORE] WinGet, version [1.6.3482], activity [{A33D250D-D3F5-421A-A5E4-392E24B4243C}]
2023-12-29 09:38:55.085 [CORE] OS: Windows.Desktop v10.0.22621.2861
2023-12-29 09:38:55.085 [CORE] Command line Args: "C:\Users\LaptopUser\AppData\Local\Microsoft\WindowsApps\winget.exe" install syncthingtray
2023-12-29 09:38:55.085 [CORE] Package: Microsoft.DesktopAppInstaller v1.21.3482.0
2023-12-29 09:38:55.085 [CORE] IsCOMCall:0; Caller: winget-cli
2023-12-29 09:38:55.112 [CLI ] WinGet invoked with arguments: 'install' 'syncthingtray'
2023-12-29 09:38:55.112 [CLI ] Found subcommand: install
2023-12-29 09:38:55.114 [CLI ] Leaf command to execute: root:install
2023-12-29 09:38:55.202 [CLI ] Executing command: install
2023-12-29 09:38:55.232 [REPO] Default source requested, multiple sources available, adding all to source references.
2023-12-29 09:38:55.232 [REPO] Adding to source references msstore
2023-12-29 09:38:55.232 [REPO] Adding to source references winget
2023-12-29 09:38:55.261 [CORE] Examining extension: PFN = Microsoft.Winget.Source_8wekyb3d8bbwe, ID = IndexDB
2023-12-29 09:38:55.262 [CORE] Found matching extension.
2023-12-29 09:38:55.274 [REPO] Multiple sources available, creating aggregated source.
2023-12-29 09:38:55.274 [REPO] Adding to aggregated source: msstore
2023-12-29 09:38:55.274 [REPO] Sending http GET request to: https://storeedgefd.dsx.mp.microsoft.com/v9.0/information
2023-12-29 09:38:55.465 [REPO] Response status: 200
2023-12-29 09:38:55.466 [REPO] Sending http GET request to: https://storeedgefd.dsx.mp.microsoft.com/v9.0/information
2023-12-29 09:38:55.718 [REPO] Response status: 200
2023-12-29 09:38:55.719 [REPO] Adding to aggregated source: winget
2023-12-29 09:38:55.736 [CORE] Examining extension: PFN = Microsoft.Winget.Source_8wekyb3d8bbwe, ID = IndexDB
2023-12-29 09:38:55.736 [CORE] Found matching extension.
2023-12-29 09:38:55.844 [REPO] Opening SQLite Index for ImmutableRead at 'C:\Program Files\WindowsApps\Microsoft.Winget.Source_2023.1229.1120.67_neutral__8wekyb3d8bbwe\Public\index.db'
2023-12-29 09:38:55.844 [SQL ] Opening SQLite connection #1: 'C:\Program Files\WindowsApps\Microsoft.Winget.Source_2023.1229.1120.67_neutral__8wekyb3d8bbwe\Public\index.db' [1, 40]
2023-12-29 09:38:55.848 [REPO] Opened SQLite Index with version [1.7], last write [2023-12-29 05:19:46.000]
2023-12-29 09:38:56.138 [REPO] Creating new SQLite Index with version [Latest] at ':memory:'
2023-12-29 09:38:56.138 [SQL ] Opening SQLite connection #2: ':memory:' [6, 0]
2023-12-29 09:38:56.163 [REPO] Reading MSI UpgradeCodes
2023-12-29 09:38:56.814 [REPO] Reading MSI UpgradeCodes
2023-12-29 09:38:56.860 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(204)\WindowsPackageManager.dll!00007FF9FD525995: (caller: 00007FF9FD52BE09) Exception(1) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:56.861 [REPO] Ignoring duplicate ARP entry User|X64|BleachBit [BleachBit 4.4.2.2142 (current user)]
2023-12-29 09:38:57.019 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(2) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.047 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(3) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.067 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(4) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.091 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(5) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.115 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(6) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.136 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(7) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.155 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(8) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.175 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(9) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.197 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(10) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.242 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(11) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.260 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(12) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.283 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(13) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.319 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(14) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.354 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(15) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.372 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(16) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.458 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(17) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.514 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(18) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.628 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(19) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.668 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(20) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.689 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(21) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.772 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(22) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:57.791 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(23) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:58.090 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(24) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:58.229 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FF9FD52597D: (caller: 00007FF9FD52BE09) Exception(25) tid(75b4) 800700B7 Cannot create a file when that file already exists.

2023-12-29 09:38:58.825 [SQL ] Opening SQLite connection #3: ':memory:' [6, 0]
2023-12-29 09:38:58.872 [REPO] Opening SQLite Index for ReadWrite at 'C:\Users\LaptopUser\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\StoreEdgeFD\installed.db'
2023-12-29 09:38:58.872 [SQL ] Opening SQLite connection #4: 'C:\Users\LaptopUser\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\StoreEdgeFD\installed.db' [2, 0]
2023-12-29 09:38:58.876 [REPO] Opened SQLite Index with version [1.3], last write [2022-07-21 20:22:38.000]
2023-12-29 09:38:58.886 [REPO] Sending http POST request to: https://storeedgefd.dsx.mp.microsoft.com/v9.0/manifestSearch
2023-12-29 09:38:59.058 [REPO] Response status: 200
2023-12-29 09:38:59.076 [REPO] Opening SQLite Index for ReadWrite at 'C:\Users\LaptopUser\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db'
2023-12-29 09:38:59.076 [SQL ] Opening SQLite connection #5: 'C:\Users\LaptopUser\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db' [2, 0]
2023-12-29 09:38:59.081 [REPO] Opened SQLite Index with version [1.3], last write [2023-12-29 09:31:39.000]
2023-12-29 09:38:59.181 [REPO] Finding installed package from available package using system reference search: Query:[none] Include:NormalizedNameAndPublisher='syncthingtray'+'martchus'[Exact]
2023-12-29 09:38:59.206 [REPO] Opening pinning index
2023-12-29 09:38:59.207 [REPO] Opening existing pinning index
2023-12-29 09:38:59.207 [REPO] Opening SQLite Index for ReadWrite at 'C:\Users\LaptopUser\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\pinning.db'
2023-12-29 09:38:59.207 [SQL ] Opening SQLite connection #6: 'C:\Users\LaptopUser\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\pinning.db' [2, 0]
2023-12-29 09:38:59.209 [REPO] Opened Pinning Index with version [1.0], last write [2023-09-22 00:48:02.000]
2023-12-29 09:38:59.215 [CLI ] Found one app. App id: Martchus.syncthingtray App name: syncthingtray
2023-12-29 09:38:59.220 [REPO] Downloading manifest
2023-12-29 09:38:59.220 [CORE] WinINet downloading from url: https://cdn.winget.microsoft.com/cache/manifests/m/Martchus/syncthingtray/1.4.11/b8ab
2023-12-29 09:38:59.578 [CORE] Download hash: 253bb249213609ec1af48fc981a0892440d994349b7f517fdbec90b56bd522d0
2023-12-29 09:38:59.578 [CORE] Download completed.
2023-12-29 09:38:59.582 [CLI ] Manifest fields: Name [syncthingtray], Version [1.4.11]
2023-12-29 09:38:59.639 [CLI ] Generated temp download path: C:\Users\LAPTOP~1\AppData\Local\Temp\WinGet\Martchus.syncthingtray.1.4.11\84bb58505df4e9de5653352a8357359e8b46d8376e0d6e7e197b0c6786f1c8fb
2023-12-29 09:38:59.640 [CORE] Downloading to path: C:\Users\LAPTOP~1\AppData\Local\Temp\WinGet\Martchus.syncthingtray.1.4.11\84bb58505df4e9de5653352a8357359e8b46d8376e0d6e7e197b0c6786f1c8fb
2023-12-29 09:38:59.642 [CORE] DeliveryOptimization downloading from url: https://github.com/Martchus/syncthingtray/releases/download/v1.4.11/syncthingtray-1.4.11-x86_64-w64-mingw32.exe.zip
2023-12-29 09:39:04.360 [CORE] Download completed.
2023-12-29 09:39:05.204 [CORE] Started applying motw to C:\Users\LAPTOP~1\AppData\Local\Temp\WinGet\Martchus.syncthingtray.1.4.11\84bb58505df4e9de5653352a8357359e8b46d8376e0d6e7e197b0c6786f1c8fb with zone: 3
2023-12-29 09:39:05.216 [CORE] Finished applying motw
2023-12-29 09:39:05.217 [CLI ] Installer hash verified
2023-12-29 09:39:05.217 [CORE] Started applying motw to C:\Users\LAPTOP~1\AppData\Local\Temp\WinGet\Martchus.syncthingtray.1.4.11\84bb58505df4e9de5653352a8357359e8b46d8376e0d6e7e197b0c6786f1c8fb with zone: 2
2023-12-29 09:39:05.223 [CORE] Finished applying motw
2023-12-29 09:39:05.226 [CLI ] Successfully renamed downloaded installer. Path: C:\Users\LAPTOP~1\AppData\Local\Temp\WinGet\Martchus.syncthingtray.1.4.11\syncthingtray-1.4.11-x86_64-w64-mingw32.exe.zip
2023-12-29 09:39:05.328 [CLI ] Extracting archive to: C:\Users\LAPTOP~1\AppData\Local\Temp\WinGet\Martchus.syncthingtray.1.4.11\extracted
2023-12-29 09:39:11.266 [CLI ] Successfully extracted archive
2023-12-29 09:39:12.687 [CORE] Created target install directory: C:\Users\LaptopUser\AppData\Local\Microsoft\WinGet\Packages\Martchus.syncthingtray_Microsoft.Winget.Source_8wekyb3d8bbwe
2023-12-29 09:39:12.688 [REPO] Creating new Portable Index with version [Latest] at 'C:\Users\LaptopUser\AppData\Local\Microsoft\WinGet\Packages\Martchus.syncthingtray_Microsoft.Winget.Source_8wekyb3d8bbwe\Martchus.syncthingtray_Microsoft.Winget.Source_8wekyb3d8bbwe.db'
2023-12-29 09:39:12.688 [SQL ] Opening SQLite connection #7: 'C:\Users\LaptopUser\AppData\Local\Microsoft\WinGet\Packages\Martchus.syncthingtray_Microsoft.Winget.Source_8wekyb3d8bbwe\Martchus.syncthingtray_Microsoft.Winget.Source_8wekyb3d8bbwe.db' [6, 0]
2023-12-29 09:39:13.872 [CORE] Moving portable exe to: C:\Users\LaptopUser\AppData\Local\Microsoft\WinGet\Packages\Martchus.syncthingtray_Microsoft.Winget.Source_8wekyb3d8bbwe\syncthingtray-1.4.11-x86_64-w64-mingw32-cli.exe
2023-12-29 09:39:14.114 [CORE] Moving portable exe to: C:\Users\LaptopUser\AppData\Local\Microsoft\WinGet\Packages\Martchus.syncthingtray_Microsoft.Winget.Source_8wekyb3d8bbwe\syncthingtray-1.4.11-x86_64-w64-mingw32-LICENSES.md
2023-12-29 09:39:14.367 [CORE] Moving portable exe to: C:\Users\LaptopUser\AppData\Local\Microsoft\WinGet\Packages\Martchus.syncthingtray_Microsoft.Winget.Source_8wekyb3d8bbwe\syncthingtray-1.4.11-x86_64-w64-mingw32.exe
2023-12-29 09:39:14.631 [CORE] Failed to create symlink at: C:\Users\LaptopUser\AppData\Local\Microsoft\WinGet\Links\syncthingtray.exe
2023-12-29 09:39:14.635 [CORE] Appending portable target directory to PATH registry: C:\Users\LaptopUser\AppData\Local\Microsoft\WinGet\Packages\Martchus.syncthingtray_Microsoft.Winget.Source_8wekyb3d8bbwe
2023-12-29 09:39:14.690 [REPO] Opening SQLite Index for ReadWrite at 'C:\Users\LaptopUser\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db'
2023-12-29 09:39:14.690 [SQL ] Opening SQLite connection #8: 'C:\Users\LaptopUser\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db' [2, 0]
2023-12-29 09:39:14.700 [REPO] Opened SQLite Index with version [1.3], last write [2023-12-29 09:31:39.000]
2023-12-29 09:39:15.574 [CLI ] Removing installer: C:\Users\LAPTOP~1\AppData\Local\Temp\WinGet\Martchus.syncthingtray.1.4.11\extracted
2023-12-29 09:39:15.575 [CLI ] Leaf command succeeded: root:install

**Comment by fancybody** [comment] 2023-12-30 10:33
Run your terminal as admin first (as per https://github.com/microsoft/winget-pkgs/issues/111454#issuecomment-1623617464).

**Comment by soredake** [comment] 2023-12-30 10:51
Or wait for shims to be implemented in winget https://github.com/microsoft/winget-cli/issues/361

**Comment by Trenly** [comment] 2023-12-30 16:46
* Duplicate of https://github.com/microsoft/winget-cli/issues/3437

**Closed** 2023-12-30 16:46 UTC
Labels: Issue-Bug, Needs-Triage
