### ISSUE TITLE
[Bug]: winget upgrade return version unknown

### ISSUE THREAD

**Issue by ivonenchev** [microsoft/winget-pkgs#36722] opened 2021-12-02 11:16 UTC
### Brief description of your issue

I installed the packages : MEGAsync   - Mega.MEGASync 4.6.1.0   and GOG GALAXY GOG.Galaxy   2.0.43.71a.
When i run the command : winget upgrade I face the issue with text : 

PS C:\Users\> winget upgrade
Name          Id             Version    Available    Source
------------------------------------------------------------
MEGAsync      Mega.MEGASync  Unknown    4.6.1.0       winget
GOG GALAXY    GOG.Galaxy     Unknown    2.0.43.71a    winget
2 upgrades available.

### Steps to reproduce

winget upgrade

### Expected behavior

To upgrade the packages

### Actual behavior

Cannot upgrade the packages. 

### Environment

```shell
winget --info
Windows Package Manager v1.1.12986
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.348
Package: Microsoft.DesktopAppInstaller v1.16.12986.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by KaranKad** [comment] 2021-12-02 11:38
related to https://github.com/microsoft/winget-pkgs/issues/30134 and https://github.com/microsoft/winget-pkgs/issues/27206

**Comment by jedieaston** [comment] 2021-12-02 16:03
To actually start an upgrade, you need to do either `winget upgrade --all` (to upgrade all applications on your system that need it), or `winget upgrade <id for package you want to upgrade>` (to upgrade just one).

`winget upgrade` only lists what applications need to be upgraded, it doesn't actually do anything.

**Comment by OfficialEsco** [comment] 2022-01-20 23:04
Duplicate of #15946

**Closed by OfficialEsco** 2022-01-20 23:04 UTC
Labels: Issue-Bug

**Comment by khalili-mohammad** [comment] 2024-03-13 12:45
I have been experiencing an issue for the past 5 weeks with the Winget upgrade process. Below is an example of the error I encounter when attempting to upgrade the "Foxit PDF Reader":

`
winget upgrade "Foxit PDF Reader" --silent
Found Foxit PDF Reader [Foxit.FoxitReader] Version 2024.1.0.23997
PS C:\Windows\system32> winget install "Foxit.FoxitReader" --silent
An existing package was found. Attempting to upgrade the installed package...
Found Foxit PDF Reader [Foxit.FoxitReader] Version 2024.1.0.23997
This application is licensed to you by its owner.
Microsoft is not responsible and does not grant licenses for third-party packages.
The installer hash was successfully verified.
Starting package installation...

Now installing, please wait...

Setup failed.
Installation failed with Exitcode: 1603.`



winget --info
Windows-Paket-Manager v1.7.10582
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22631.3296
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.22.10582.0

WinGet-Verzeichnisse
-----------------------------------------------------------------------------------------------------------------------
Protokolle                                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Benutzereinstellungen                        %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Verzeichnis für portierbare Links (Benutzer) %LOCALAPPDATA%\Microsoft\WinGet\Links
Portables Linkverzeichnis (Computer)         C:\Program Files\WinGet\Links
Portierbarer Paketstamm (Benutzer)           %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portierbarer Paketstamm                      C:\Program Files\WinGet\Packages
Portierbares Paketstamm (x86)                C:\Program Files (x86)\WinGet\Packages
Installationsprogrammdownloads               %USERPROFILE%\Downloads

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store-Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale

Administratoreinstellung                  Status
-----------------------------------------------------
LocalManifestFiles                        Deaktiviert
BypassCertificatePinningForMicrosoftStore Deaktiviert
InstallerHashOverride                     Deaktiviert
LocalArchiveMalwareScanOverride           Deaktiviert
