### ISSUE TITLE
127891

### ISSUE THREAD

**Issue by fwadnjar** [microsoft/winget-pkgs#128407] opened 2023-11-28 14:58 UTC
MesterPerfect:windows.PCSX2-1.6.0-10b500e4-e5c9-437e-a905-3c8d0cb81243

_Originally posted by @fwadnjar in https://github.com/microsoft/winget-pkgs/issues/127891#issuecomment-1830016568_

**Comment by mdanish-kh** [comment] 2023-11-28 15:13
Duplicate of #128404

**Closed** 2023-11-28 15:13 UTC
Labels: Needs-Triage
