### ISSUE TITLE
[Package Removal/Fix Request]: DavidTHOIRON.FotoSketcher

### ISSUE THREAD

**Issue by thedoggybrad** [microsoft/winget-pkgs#58611] opened 2022-04-24 02:00 UTC
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

I want to remove this package or change its version, I guess to 00.00 or any version number that will not cause its reinstallation over and over again when using "winget upgrade --all". Thank You in advance. Its version in Control Panel is nothing.

**Comment by Trenly** [comment] 2022-04-24 04:20
This is fixed in the latest preview version of the client, where apps which do not register a version to ARP won’t be included in upgrade by default. 

We cannot change the existing version, since it will not fix the issue, and the package should bot be removed as it is working as intended. 

Duplicate of #55988

**Closed by Trenly** 2022-04-24 04:21 UTC
Labels: Help-Wanted, Package-Request, Needs-Triage
