### ISSUE TITLE
[Package Issue]: flux.flux no installed version info

### ISSUE THREAD

**Issue by risshun** [microsoft/winget-pkgs#59385] opened 2022-05-03 04:56 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

local installed version shows "Unknown"

### Steps to reproduce

`winget list --name f.lux`

### Actual behavior

```
Name  Id        Version Available Source
----------------------------------------
f.lux flux.flux Unknown 4.120     winget
```

### Expected behavior

```
Name  Id        Version Available Source
----------------------------------------
f.lux flux.flux 4.120            winget
```

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.613
Package: Microsoft.DesktopAppInstaller v1.17.10271.0
```
```


### Screenshots and Logs

_No response_

**Comment by lychichem** [comment] 2022-05-03 09:15
You should ask the developer of flux to write version number into registry when they build new installers. It's an external bug which winget yeam cannot solve.

**Comment by Trenly** [comment] 2022-05-03 12:58
Duplicate of #16003

**Closed by Trenly** 2022-05-03 12:58 UTC
Labels: Issue-Bug, Needs-Triage
