### ISSUE TITLE
Flux gets reinstalled every time winget upgrade --all is run

### ISSUE THREAD

**Issue by savyajha** [microsoft/winget-pkgs#18089] opened 2021-06-19 07:57 UTC
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

Whenever I type `winget upgrade --all` in powershell, flux gets updated regardless of whether there is a version increment or not.

# Steps to reproduce

**Step 1:** Upgrade all packages using winget:

```none
PS C:\Users\savya> winget upgrade --all
Found f.lux [flux.flux]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://justgetflux.com/flux-setup.exe
  ██████████████████████████████   653 KB /  653 KB
Successfully verified installer hash
Starting package install...
Successfully installed

Found Microsoft OneDrive [Microsoft.OneDrive]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://oneclient.sfx.ms/Win/Prod/21.109.0530.0001/amd64/OneDriveSetup.exe
  ██████████████████████████████  43.2 MB / 43.2 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Found WinSCP [WinSCP.WinSCP]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://sourceforge.net/projects/winscp/files/WinSCP/5.19/WinSCP-5.19-Setup.exe/download
  ██████████████████████████████  10.8 MB / 10.8 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Found WireGuard [WireGuard.WireGuard]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://download.wireguard.com/windows-client/wireguard-amd64-0.3.15.msi
  ██████████████████████████████  2.68 MB / 2.68 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```
**Step 2:** Check the flux version. In my case I see v4.119

**Step 3:** Upgrade all packages again using the CLI

```none
PS C:\Users\savya> winget upgrade --all
Found f.lux [flux.flux]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://justgetflux.com/flux-setup.exe
  ██████████████████████████████   653 KB /  653 KB
Successfully verified installer hash
Starting package install...
Successfully installed
```

**Step 4:** Check version number of flux again. In my case, it did not increment from v4.119

# Expected behavior

If there is no version change, I expect flux to not get reinstalled.

# Actual behavior

Flux gets reinstalled despite there being no version increment.

# Environment

```none
Windows Package Manager v1.0.11451
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.1055
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
Licence Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
```

**Comment by DylanSealy** [comment] 2021-06-19 08:27
Hello @savyajha,

The problem here is that f.lux doesn't report it's version number and because of that winget doesn't know which version is installed.

**Comment by savyajha** [comment] 2021-06-19 09:14
Ah, I see. Thank you for clearing that up. Is there any way of mitigating this issue? Or does the fix have to come from the flux team?

**Comment by DylanSealy** [comment] 2021-06-19 09:41
The easiest solution is that f.lux reports it's version and that has to come from the f.lux team. For more info you can read this discussion #15243 about this topic.

**Comment by lychichem** [comment] 2021-06-19 11:42
You may also add a registry key called DisplayVersion in `HKCU\Software\Microsoft\Windows\Currentversion\Uninstall\flux` which has the value `4.119`. This will force flux report it has version number 4.119.

**Comment by quhxl** [comment] 2021-06-26 08:44
They know about this issue, maybe they will fix it in a future update: https://forum.justgetflux.com/topic/7933/add-installation-version-number

**Comment by vedantmgoyal2009** [comment] 2021-09-12 05:26
Duplicate of #16003

**Closed** 2021-11-07 12:06 UTC
Labels: Help-Wanted
