### ISSUE TITLE
[Package Request]: WinSCP

### ISSUE THREAD

**Issue by TobiasSekan** [microsoft/winget-pkgs#49840] opened 2022-03-02 08:27 UTC
### Package Requested

- [X] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: WinSCP.net
Publisher Url: https://winscp.net
Package Name: WinSCP-5.19.6-Setup.exe
Description: WinSCP is a popular SFTP client and FTP client for Microsoft Windows! 
Package Version: 5.19
Installer URL: https://winscp.net/download/WinSCP-5.19.6-Setup.exe

Current Package Identifier (for new versions): 

Checksums
    MD5: 5f2ba7a3b97574f2462420370092df75
    SHA-1: d12f9d76678708b657af3cd4b4a1822afefa5fc6
    SHA-256: d5402b38b60099335e091c6d6b8143eb64a6eb02f24bf014edbd598313440463

**Comment by OfficialEsco** [comment] 2022-03-02 10:49
[WinSCP.WinSCP](https://github.com/microsoft/winget-pkgs/tree/master/manifests/w/WinSCP/WinSCP) have been in the repo since 2020-05-19.
Duplicate of #307

**Closed** 2022-03-02 10:54 UTC
Labels: Help-Wanted, Package-Request, Needs-Triage
