### ISSUE TITLE
[Package Issue]: Package.Identifer

### ISSUE THREAD

**Issue by Cromaxxx** [microsoft/winget-pkgs#82134] opened 2022-10-03 04:32 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Cant upgrade .net sdk 6.0 through winget 

### Steps to reproduce

![193492425-f7e08b1f-4c6b-46c2-8b86-afd27dd9f7a7](https://user-images.githubusercontent.com/10215299/193501000-b345337c-fa73-4f48-b840-a3214ce66842.png)

![gabba](https://user-images.githubusercontent.com/10215299/193501118-a150ed04-810b-468a-aa03-f2ffb173e4c2.png)

### Actual behavior

It cant find package even though its installed on computer

### Expected behavior

To upgrade package 

### Environment

```shell
Windows Package Manager v1.3.2091
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.608
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2091.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

[WinGet-2022-10-03-04-39-51.120.log](https://github.com/microsoft/winget-pkgs/files/9694656/WinGet-2022-10-03-04-39-51.120.log)

**Comment by Trenly** [comment] 2022-10-03 12:24
What happens when you run `winget list '.NET SDK'`

**Comment by Cromaxxx** [comment] 2022-10-03 12:33
![sdk](https://user-images.githubusercontent.com/10215299/193577451-7953dd8b-3339-4c38-9d29-779a3766467c.png)

**Comment by Trenly** [comment] 2022-10-03 13:45
The issue is happening because it is detecting that you have two versions installed, and thinks the older version needs to be upgraded, but then upgrade fails because you already have the newer version. Removing the older version should fix the issue

**Comment by jedieaston** [comment] 2022-10-03 14:36
> Removing the older version should fix the issue

Just a note that this is a mitigation, not a fix. Many .NET shops have their projects pinned to a specific minor/patch version of the SDK, so you need to have multiple installed at once for the compiler not to complain at you about global.json.

**Comment by Trenly** [comment] 2024-05-01 14:50
Thank you for taking the time to report this issue. In the amount of time the issue has been open, there have been several updates to the WinGet CLI which may have helped mitigate some of these concerns. I encourage you to try out the [latest pre-release](https://github.com/microsoft/winget-cli/releases) of the CLI and see if your problem still persists. 

There is a new [experimental feature](https://github.com/microsoft/winget-cli/discussions/4281) for `Side-By-Side` installs which may help with this case. As there are many similar issues for side by side open on the CLI repo, I'll be closing this one to keep things clean.

###### Close with reason: Tracked at winget-cli; Experimental feature available

**Closed** 2024-05-01 14:50 UTC
Labels: Issue-Bug
