### ISSUE TITLE
'winget upgrade' reports WinDirStat upgradable when latest version is installed

### ISSUE THREAD

**Issue by Hobart** [microsoft/winget-pkgs#88994] opened 2022-02-15 20:50 UTC
### Brief description of your issue

I have WinDirStat 1.1.2 installed.  `winget upgrade` lists it as upgradable.

### Steps to reproduce

```
C:\Windows\system32>winget upgrade
Name                Id                    Version Available Source
------------------------------------------------------------------
Mozilla Firefox ESR Mozilla.Firefox.ESR   45.9.0  91.6.0    winget
WinDirStat          WinDirStat.WinDirStat Unknown 1.1.2     winget
2 upgrades available.

C:\Windows\system32>
```

### Expected behavior

Not see an up to date product listed.

### Actual behavior

Product is listed with installed 'Version' of 'Unknown'

### Environment

```shell
C:\Windows\system32>winget --info
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1526
Package: Microsoft.DesktopAppInstaller v1.16.13405.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

```
reg query hkcu\software\microsoft\windows\currentversion\uninstall\windirstat

HKEY_CURRENT_USER\software\microsoft\windows\currentversion\uninstall\windirstat
    UninstallString    REG_EXPAND_SZ    "C:\Program Files (x86)\WinDirStat\Uninstall.exe"
    InstallLocation    REG_EXPAND_SZ    C:\Program Files (x86)\WinDirStat
    DisplayName    REG_SZ    WinDirStat 1.1.2
    DisplayIcon    REG_SZ    C:\Program Files (x86)\WinDirStat\windirstat.exe,0
    dwVersionMajor    REG_DWORD    0x1
    dwVersionMinor    REG_DWORD    0x1
    dwVersionRev    REG_DWORD    0x2
    dwVersionBuild    REG_DWORD    0x4f
    URLInfoAbout    REG_SZ    http://windirstat.info/
    NoModify    REG_DWORD    0x1
    NoRepair    REG_DWORD    0x1
```
```

**Comment by ShockwaveNN** [comment] 2022-11-17 18:26
I found WinDirStat issue tracker and [reported problem with versioning](https://osdn.net/projects/windirstat/ticket/46072#preview)

**Comment by Bertaz** [comment] 2023-02-13 17:47
More active repo https://github.com/windirstat/windirstat/pull/2

**Comment by krystofkrticka** [comment] 2023-07-06 12:00
This might be fixed by this https://github.com/microsoft/winget-cli/issues/3134 once it's implemented in winget.

**Comment by db2222** [comment] 2023-09-02 07:39
In case anybody wants to correct it manually until a general fix is available do the following:
- Open ```RegEdit```.
- Go to ```Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\WinDirStat```.
- Add ```DisplayVersion``` and set the value to ```1.1.2```.

**Comment by ShockwaveNN** [comment] 2023-09-12 15:16
@db2222

Thanks for workaround, but seems didn't worked for me:

<img width="681" alt="image" src="https://github.com/microsoft/winget-pkgs/assets/668524/29b18210-1ac7-4bb6-a855-6dbb4139a4cb">


Any advice? Mabye DisplayVersion should be specific type, not REG_SZ

**Comment by db2222** [comment] 2023-09-12 15:32
@ShockwaveNN I have a suspicion.  In the Registry it is set for ```HKEY_CURRENT_USER```. Your PowerShell window is running as Administrator. Maybe those are 2 different users?

Or maybe you also need to restart the command line window or login in windows again as it maybe is cached. I cannot remember exactly if this was necessary.

**Comment by ShockwaveNN** [comment] 2023-09-12 16:21
> Your PowerShell window is running as Administrator. Maybe those are 2 different users?

Yeah, you right

But seems like 

1. winget can be only run from administrator
2. I've tried to find those keys for any other users - and seems they not exists

So probably workaround works only if user you've installed the WinDirStat is Administrator

**Comment by db2222** [comment] 2023-09-12 19:57
For me winget also works in a "normal" (none-admin) PowerShell window.
I can confirm that WinDirStat is installed as admin. The setup itself demands it.

Just as an idea. Does it work in case you set ```Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\WinDirStat``` in the registry? You most likely have to create it. Furthermore I'm unsure what happens if you have a mixture between LOCAL_MACHINE and HKEY_CURRENT_USER. So maybe you have to remove the folder in USER and only create under LOCAL_MACHINE (make a backup before 😉). Also restart the computer to be sure that it is recognized.

**Comment by 3xploiton3** [comment] 2023-11-25 22:26
![image](https://github.com/microsoft/winget-pkgs/assets/19517680/4a5ce1c1-d2b4-4518-8f49-97e197e6e232)

**Closed** 2023-12-26 18:29 UTC
Labels: Issue-Bug, Help-Wanted, Area-External

**Comment by JoKalliauer** [comment] 2024-04-11 17:27
> @ShockwaveNN 
> 
> Thanks for workaround, but seems didn't worked for me:
> <img alt="image" src="https://github.com/microsoft/winget-pkgs/assets/15687581/8260b417-ca70-4b20-a9a5-dc987689a45b?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTU4MzUsIm5iZiI6MTcxMjg1NTUzNSwicGF0aCI6Ii82Njg1MjQvMjY3Mzc4MzUyLTI5YjE4MjEwLTFhYzctNGJiNi1hODU1LTZkYmI0MTM5YTRjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNzEyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzY1MGJmZWEyYTFmNzA2YWUwMmMxMGQwNGY4NDkxZmMxYjU3ZWI1NzI3YjZiMDdkZmViZDM2Mjg3ODc2NDUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l0xprvB3TuFEWeXA1PeTiwA8JWXKRbg3QopATMlU0cE">
> 
> Any advice? Mabye DisplayVersion should be specific type, not REG_SZ

Maybe you have a trailing space at the end (`DisplayVersion ` instead of `DisplayVersion`) ?

To avoid copying-mistakes run the following command:
`reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\WinDirStat" /v "DisplayVersion" /d 1.1.2 /t REG_SZ /f`

or try importing the following registry:
```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\WinDirStat]
"DisplayVersion"="1.1.2"

```

----
General advice:
Before running any code, or adding anything to the registry, allways make a quick check if the code might be malicious.

**Comment by ShockwaveNN** [comment] 2024-04-14 07:12
@JoKalliauer Thanks, actually you're right, there was a space at the end of reg key

Thanks for help, seems everything is all right when I've applied your registry command

**Comment by JaneX8** [comment] 2024-04-20 15:00
This is seriously annoying. As per above suggestion, I used this Powershell command (as admin) directly after installing WinDirStat using winget. I run as administrator, but it checks for other users too, to also work if it was previously installed otherwise. Also, it only works for 1.1.2 (based on the DisplayName).

```
winget install --scope machine --accept-source-agreements -e --id WinDirStat.WinDirStat
```

```
Get-ChildItem Registry::HKEY_USERS\ -ErrorAction SilentlyContinue | Where-Object { $_.Name -match 'S-1-5-21-' } | ForEach-Object { $path = "Registry::HKEY_USERS\$($_.Name -replace 'HKEY_USERS\\', '')\Software\Microsoft\Windows\CurrentVersion\Uninstall\WinDirStat"; if ((Test-Path $path) -and ((Get-ItemProperty -Path $path -Name "DisplayName" -ErrorAction SilentlyContinue).DisplayName -like "*1.1.2*")) { Set-ItemProperty -Path $path -Name "DisplayVersion" -Value "1.1.2" -Force } }
```

**Comment by Lonniebiz** [comment] 2024-09-19 23:37
Why is this issues closed, given that it is still unresolved?

**Comment by JoKalliauer** [comment] 2024-09-20 08:32
> Why is this issues closed, given that it is still unresolved?

Please read ALL previous comments word-by-word before commenting, including the [one](https://github.com/microsoft/winget-pkgs/issues/88994#issuecomment-1869706911) which closed this issue.

Afaik it is a WinDirStat-Bug, see [#88994#issuecomment-1428391559](https://github.com/microsoft/winget-pkgs/issues/88994#issuecomment-1428391559), I think it is already fixed (since [Dec 2023](https://github.com/windirstat/windirstat/commit/65d89377e11b24bd2d7c064018a5e201b79fa005)) in the current source code for WinDirStat.
WinDirStat 1.1.2 was released in [2005](https://de.wikipedia.org/wiki/WinDirStat#cite_ref-_5f95d5e617b826c6_1-0), and re-released in [2007](https://sourceforge.net/projects/windirstat/files/windirstat/1.1.2%20installer%20re-release%20%28more%20languages%21%29/), so you have to wait for the next verison (1.1.3 or 1.2.0 or 2.0.0 or similar) or in case you are not patient you can compile the WinDirStat-source-code yourself.

If you expect a Workaround by WinGet, be more specific, as e.g. [another previous comment](https://github.com/microsoft/winget-pkgs/issues/88994#issuecomment-1623559007).

I recommend fixing it for WinDirStat 1.1.2 locally according to [another previous comment](https://github.com/microsoft/winget-pkgs/issues/88994#issuecomment-1703754131).

**Comment by Lonniebiz** [comment] 2024-09-20 10:05
I'm not a fan of bots auto-closing unresolved issues. [Ninite](https://ninite.com/) doesn't seem to have this problem of installing the same version of windirstat over and over again . Apparently, their developers took responsibility that their updater should at least be smart enough to recognize the version (it just installed) without depending solely on some arbitrary value in the windows registry. 

If winget installs an application it should take note of the version it installed (somewhere) especially if this windows registry entry doesn't exist. Since all installations and updates are timestamped, winget can assume that the current version of an application is the same version it previously installed as long as the timestamps match (between what winget recalls installing itself and the installation time of the currently installed application). Only when those timestamps do not match should winget consider upgrading.
