### ISSUE TITLE
[Package Issue]: WinDirStat.WinDirStat

### ISSUE THREAD

**Issue by fghamsary** [microsoft/winget-pkgs#54490] opened 2022-03-15 17:14 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

I have already had this application installed before, and now winget propose an update for it, but can't detect the current version installed, but proposes an update (a phantom update, because I am on the same version)
I've already uninstalled it, and installed it again via winget, always the same.

### Steps to reproduce

Just install WinDirStat and afterwards check with a winget upgrade.
You can see that winget can't determine the currently installed version, so it proposes the update which doesn't work as well.
May be it has something to do with the language of my windows which is in French.

### Actual behavior

Can't determine the currently installed version so proposes the update always!

### Expected behavior

Determine the current version correctly and not proposing any update for it.

### Environment

```shell
PS C:\Users\fghamsary> winget --info
Windows Package Manager (Preview) v1.2.3411-preview
Copyright (c) Microsoft Corporation. Tous droits réservés.

Windows: Windows.Desktop v10.0.22000.556
Package: Microsoft.DesktopAppInstaller v1.17.3411.0
```

### Screenshots and Logs

PS C:\Users\fghamsary> winget install WinDirStat.WinDirStat
Trouvé WinDirStat [WinDirStat.WinDirStat] Version 1.1.2
La licence d’utilisation de cette application vous est octroyée par son propriétaire.
Microsoft n’est pas responsable des paquets tiers et n’accorde pas de licences à ceux-ci.
Downloading https://sourceforge.net/projects/windirstat/files/windirstat/1.1.2%20installer%20re-release%20%28more%20languages%21%29/windirstat1_1_2_setup.exe/download
  ██████████████████████████████   630 KB /  630 KB
Le code de hachage de l’installation a été vérifié avec succès
Démarrage du package d’installation... Merci de patienter.
Installé correctement (This means installed correctly => it is in French)

PS C:\Users\fghamsary> winget upgrade
Nom                ID                    Version       Disponible    Source
---------------------------------------------------------------------------
WinDirStat         WinDirStat.WinDirStat Unknown       1.1.2         winget
Microsoft .NET SDK Microsoft.dotnet      5.4.622.11901 6.1.322.12413 winget

**Comment by jedieaston** [comment] 2022-03-15 17:16
This issue will be resolved in winget v1.3, and a preview release is [available now](https://github.com/microsoft/winget-cli/releases/tag/v1.3.431). Note that there are some bugs in this release that have been resolved (but a new preview release hasn't been cut yet), but it will get rid of your problem if you want to give it a shot.

**Comment by fghamsary** [comment] 2022-03-15 17:39
Thanks, I can confirm that the new release doesn't show the version Unknown, but I have the same problem yet, as it's just not showing the unknown versions.
The result can be the same by including the new --include-unknown parameter.
So the real issue which is determining the version of the application is still there.
I've not yet have enough time to investigate how does the version is determined by winget, but it can't be determined for WinDirStat anyway at the moment, event with the new version of winget, so maybe problem in definition or lack of functionality to be able to find the version, or just maybe the language.
As I said didn't have time to investigate more yet.

**Comment by OfficialEsco** [comment] 2022-03-15 18:41
The issue is with WinDirStat not reporting a DisplayVersion to Windows.
There is nothing we can do as that is the developers fault. Which is why there is a --include-unknown workaround for these packages.

**Comment by Trenly** [comment] 2022-11-11 04:37
> The issue is with WinDirStat not reporting a DisplayVersion to Windows. There is nothing we can do as that is the developers fault. Which is why there is a --include-unknown workaround for these packages.

@msftbot Installer-Issue
@msftbot Area-External

**Comment by jfernandz** [comment] 2023-06-05 08:39
I'd say this is a duplicate of https://github.com/microsoft/winget-pkgs/issues/88994 😉

**Comment by fghamsary** [comment] 2023-06-05 13:26
Yes that's right didn't see the other ticket when I searched

**Comment by fghamsary** [comment] 2023-06-05 13:27
> I'd say this is a duplicate of #88994 😉

I just created the ticket as requested by the guidelines of tickets

**Closed** 2023-12-07 16:51 UTC
Labels: Issue-Bug, Help-Wanted, Area-External, Installer-Issue
