### ISSUE TITLE
Mismatched Id of listed VC++ upgrade

### ISSUE THREAD

**Issue by VoidMonk** [microsoft/winget-pkgs#85478] opened 2022-10-19 02:23 UTC
### Brief description of your issue

Running `winget upgrade` shows incorrect package Id for Microsoft Visual C++ 2015-2022 Redistributable, hence doesn't perform an upgrade with the given Id.

### Steps to reproduce

I have both `Microsoft Visual C++ 2015-2022 Redistributable (x86)` and `Microsoft Visual C++ 2015-2022 Redistributable (x64)` installed, with x64 one at latest version and x86 one older (not the latest).

Running `winget upgrade` shows:

```
Name                                                               Id                           Version       Available     Source
----------------------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x86) - 14.32.31332 Microsoft.VCRedist.2015+.x64 14.32.31332.0 14.34.31823.3 winget
```

### Expected behavior

Suggested package Id above `Microsoft.VCRedist.2015+.x64` does not match the package (x86). Id should be `Microsoft.VCRedist.2015+.x86` in this case, so that running `winget upgrade Microsoft.VCRedist.2015+.x86` can upgrade the relevant package.

### Actual behavior

Running, `winget upgrade Microsoft.VCRedist.2015+.x64` (suggested Id above) does not perform an upgrade, because the listed Id is incorrect (x64) for an x86 library package, but both packages list fine in Windows - Installed Apps.

### Environment

```shell
Windows Package Manager v1.3.2691
Windows: Windows.Desktop v10.0.22621.675
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0
```

**Comment by OfficialEsco** [comment] 2022-10-19 17:08
Would you mind fetching the ProductCode by using RevoUninstaller Portable?
https://www.revouninstaller.com/revo-uninstaller-free-download/
Right click VC++2015-2022 x86 -> Open Registry Key -> Paste the RegistryKey folder
The registry path should be `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{a98dc6ff-d360-4878-9f0a-915eba86eaf3}` where `{a98dc6ff-d360-4878-9f0a-915eba86eaf3}` is the `ProductCode`.
`{3746f21b-c990-4045-bb33-1cf98cff7a68}` is the ProductCode for x64

https://github.com/microsoft/winget-pkgs/blob/ac6afe856c44d3f138fa0cc5d160f8e18d157e83/manifests/m/Microsoft/VCRedist/2015%2B/x86/14.32.31332.0/Microsoft.VCRedist.2015%2B.x86.installer.yaml#L28-L31
https://github.com/microsoft/winget-pkgs/blob/ac6afe856c44d3f138fa0cc5d160f8e18d157e83/manifests/m/Microsoft/VCRedist/2015%2B/x64/14.32.31332.0/Microsoft.VCRedist.2015%2B.x64.installer.yaml#L28-L31

**Comment by VoidMonk** [comment] 2022-10-19 23:03
@OfficialEsco - I had to manually upgrade the x86 package on my machine, due to this issue.

Current `DisplayName` and `ProductCode` for both the package:

```
Microsoft Visual C++ 2015-2022 Redistributable (x86) - 14.34.31823: {485c6580-376a-450b-9a80-43c390b968a3}
```
```
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.34.31823: {ac8ae441-cfc2-41f2-bbca-7b6668740f8d}
```

**Comment by elfmimi** [comment] 2023-04-23 05:07
Similar problem occurs while trying to install x86 variant when you have x64 variant already installed. or vice versa.

When only one of either x86 or x64 variants are installed `winget list` behaves wrongly.
example:
- when only Microsoft.VCRedist.2010.x86 is installed `winget list Microsoft.VCRedist.2010.x64` shows this.
<pre>
Name                                                        Id                          Version    Source
---------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219 Microsoft.VCRedist.2010.x64 10.0.40219 winget
</pre>

- when only Microsoft.VCRedist.2010.x64 is installed `winget list Microsoft.VCRedist.2010.x86` shows this.
<pre>
Name                                                        Id                          Version    Source
---------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2010  x64 Redistributable - 10.0.40219 Microsoft.VCRedist.2010.x86 10.0.40219 winget
</pre>

Hence winget says "Found an existing package already installed" and won't install second variant.

As far as I could test, this applies to 2010 2012 2013 and 2015+ .

**Comment by thomasneubergersdx** [comment] 2023-08-29 05:52
I had the same problem, this seems to have helped for me:
* Manually uninstall the x86 version in Add and Remove programs
* Reinstall it via `winget install Microsoft.VCRedist.2015+.x86`
It is now reported with the correct id and hopefully will get the next update as intended.

**Comment by ArmandDelessert** [comment] 2024-02-21 10:44
Hello there.

I have the same issue:

``` WinGet
> winget upgrade
Nom                                                                ID                           Version                     Disponible                Source
------------------------------------------------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x86) - 14.38.33130 Microsoft.VCRedist.2015+.x64 14.38.33130.0               14.38.33135.0             winget

> winget download -q Microsoft.VCRedist.2015+.x64
Trouvé Microsoft Visual C++ 2015-2022 Redistributable (x64) [Microsoft.VCRedist.2015+.x64] Version 14.38.33135.0
...
Programme d’installation téléchargé : C:\Users\ArmandDelessert\Downloads\Microsoft.VCRedist.2015+.x64_14.38.33135.0\Microsoft Visual C++ 2015-2022 Redistributable (x64)_14.38.33135.0_Machine_X64_burn_en-US.exe

> winget download -q Microsoft.VCRedist.2015+.x86
Trouvé Microsoft Visual C++ 2015-2022 Redistributable (x86) [Microsoft.VCRedist.2015+.x86] Version 14.38.33130.0
...
Programme d’installation téléchargé : C:\Users\ArmandDelessert\Downloads\Microsoft.VCRedist.2015+.x86_14.38.33130.0\Microsoft Visual C++ 2015-2022 Redistributable (x86)_14.38.33130.0_Machine_X86_burn_en-US.exe
```

![List of the "Microsoft Visual C++ 2015-2022 Redistributable" in "Uninstall or change a program"](https://github.com/microsoft/winget-pkgs/assets/11057437/4595df1a-dd94-4c8c-8ec1-ebf78f4db0a4)

WinGet seems to confuse the 2 x86 and x64 versions of _Microsoft Visual C++ 2015-2022 Redistributable_. As a result, it can't update the package `Microsoft.VCRedist.2015+.x86` [to the latest version](https://learn.microsoft.com/cpp/windows/latest-supported-vc-redist#latest-microsoft-visual-c-redistributable-version).
I also noticed that the latest version of the package `Microsoft.VCRedist.2015+.x86` is missing [from this GitHub's Manifest database](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/VCRedist/2015%2B/x86). Is it a related problem?

I am running Windows 10 19045.4046 and WinGet v1.7.3481-preview.

**Comment by ArmandDelessert** [comment] 2024-02-21 11:02
So, I uninstalled the package `Microsoft.VCRedist.2015+.x86`, then reinstalled it from WinGet (`winget install Microsoft.VCRedist.2015+.x86`). It installed version `14.38.33130.0`. I then updated it to version `14.38.33135.0` using the executable downloaded directly [from the Microsoft website](https://learn.microsoft.com/cpp/windows/latest-supported-vc-redist#latest-microsoft-visual-c-redistributable-version). And it's all good now!

``` WinGet
> winget list "Visual C++ 2015-2022 Redistributable"
Nom                                                                ID                           Version       Source
---------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x86) - 14.38.33135 Microsoft.VCRedist.2015+.x86 14.38.33135.0 winget
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.38.33135 Microsoft.VCRedist.2015+.x64 14.38.33135.0 winget

> winget upgrade
0 mise à niveau disponible.
```

**Comment by Trenly** [comment] 2024-04-30 19:30
Several other issues are tracking issues related to VC Runtimes and side-by-side. I'm closing this issue in favor of the work over at the CLI.

###### Close with reason: Tracked at CLI;

**Closed** 2024-04-30 19:30 UTC
Labels: Issue-Bug
