### ISSUE TITLE
[Package Issue]: GNU.Emacs does not register as installed after successful installation

### ISSUE THREAD

**Issue by xgqt** [microsoft/winget-pkgs#133066] opened 2024-01-07 21:19 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

GNU.Emacs does not register as installed after successful installation.

This is a dusplicate of resolved issue https://github.com/microsoft/winget-pkgs/issues/88443#issuecomment-1846870238 ***but*** the issue was not fixed. If this package is still left broken I think it would be better to delete it.

### Steps to reproduce

> winget install --source winget --verbose GNU.Emacs
> winget list

### Actual behavior

GNU.Emacs is not on the list.
Because of this then a installation is requested GNU.Emacs will be always reinstalled.

### Expected behavior

GNU.Emacs registers in the system as installed application.

### Environment

```raw
-> winget --info
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2861
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### Screenshots and Logs

None

**Comment by xgqt** [comment] 2024-01-08 08:51
We could work around this by explicitly adding some record that GNU Emacs was installed always after the provided installers succeeds but I do not know winget and do not know if this is possible now. WDYT?

**Comment by stephengillie** [comment] 2024-08-27 16:18
Since https://github.com/microsoft/winget-pkgs/pull/136062 is merged, I'll assume this is complete. If this is in error, please @ me and I'll reopen.

**Closed by stephengillie** 2024-08-27 16:18 UTC
Labels: Issue-Bug, In-PR

**Comment by neerolyte** [comment] 2024-09-14 07:45
The reported issue still occurs on 29.4:

```
PS C:\> winget install GNU.Emacs
Found GNU Emacs [GNU.Emacs] Version 29.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://ftp.gnu.org/gnu/emacs/windows/emacs-29/emacs-29.4-installer.exe
  ██████████████████████████████  69.5 MB / 69.5 MB
Successfully verified installer hash
Starting package install...
Successfully installed
PS C:\> winget list | select-string emacs
PS C:\> 
```

**Comment by albertosantini** [comment] 2025-04-03 07:41
I am the author of the old #88443.

I tried with `30.1` and the issue is resolved: GNU.Emacs is on the list of winget.

**Comment by albertosantini** [comment] 2025-08-04 21:42
The issue is addressed by Emacs maintainers.
I directly contacted them suggesting oneline fix in admin/nt/dist-build/emacs.nsi.

I suppose it will be in 30.2.

**Comment by albertosantini** [comment] 2025-08-05 16:07
https://github.com/emacs-mirror/emacs/compare/master...emacs-30
