### ISSUE TITLE
[Package Issue]: Gyan.FFmpeg sets environment path incorrectly

### ISSUE THREAD

**Issue by rlaphoenix** [microsoft/winget-pkgs#95349] opened 2023-02-02 00:18 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The ffmpeg, ffprobe, and ffplay aliases do not work even after restarting shell due to the environment path being wrong.

The environment path added was `C:\Users\...\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe` but it needs to be `C:\Users\...\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-5.1.2-full_build\bin` before it works.

### Steps to reproduce

1. `winget install ffmpeg`
2. Wait for installation to complete
3. Close and re-open shell
4. Type `ffmpeg --help`, it will fail and say it's unrecognised

### Actual behavior

the `ffmpeg`, `ffplay`, and `ffprobe` aliases are not recognized

### Expected behavior

They should be found and refer to the binary.

### Environment

```shell
Windows Package Manager (Preview) v1.5.101-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1105
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.101.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/17136956/216227506-f12cbba7-3882-4a59-8cf4-8d9fec21b7c2.png)

**Comment by Trenly** [comment] 2023-02-02 02:03
This is because ffmpeg is a library and not truly a portable application or portable installer 

Blocked by https://github.com/microsoft/winget-cli/issues/2711

**Comment by SpecterShell** [comment] 2023-02-02 02:18
It works for me though.
![image](https://user-images.githubusercontent.com/56779163/216214755-d07e558a-4361-46f9-88b1-af79cdb8177c.png)

**Comment by Trenly** [comment] 2023-02-02 02:26
Interesting. 

I wonder if it's due to path cramming differences between user/admin and whether or not developer mode is enabled. Might have something to do with symlink creation

**Comment by rlaphoenix** [comment] 2023-02-02 02:27
Doesn't work for me, I had to explicitly put `\ffmpeg-5.1.2-full_build\bin` to the end of the environment path. It looks like you're either on Linux or using a different terminal to me. Maybe it's something to do with that? But I tried Windows Terminal, PowerShell (latest from the Windows Store), normal PowerShell, and Command Prompt. It didn't work on any.

**Comment by SpecterShell** [comment] 2023-02-02 02:46
Also tried in my virtual machine. Even if the directory `C:\Users\<Username>\AppData\Local\Microsoft\WinGet\Links` has been added to PATH and can be seen in the system's "Environmental Variables" settings, it is not shown in the subsequent processes. 🤔
![image](https://user-images.githubusercontent.com/56779163/216217960-b417669d-4f23-43f5-a9dc-4fd8aa9420e4.png)

**Comment by rlaphoenix** [comment] 2023-02-02 02:59
> Also tried in my virtual machine. Even if the directory `C:\Users\<Username>\AppData\Local\Microsoft\WinGet\Links` has been added to PATH and can be seen in the system's "Environmental Variables" settings, it is not shown in the subsequent processes. 🤔 ![image](https://user-images.githubusercontent.com/56779163/216219191-004b5712-327d-4f70-98b2-801ac1922c73.png)

I believe you need to fully close all previous terminals, then open a new one for it to actually refresh. Hence why it's not in your PATH yet.

**Comment by Trenly** [comment] 2023-02-02 03:02
> C:\Users\<Username>\AppData\Local\Microsoft\WinGet\Link

Even when doing that, I still don't see it reflected in `$env:Path`

It looks to me like it is only added to the User Variable path and not the System Variable path
![image](https://user-images.githubusercontent.com/12611259/216220982-ba006122-77ec-4f8c-bfff-c8868b94f8f6.png)

**Comment by SpecterShell** [comment] 2023-02-02 03:14
> I believe you need to fully close all previous terminals, then open a new one for it to actually refresh.

Doesn't work for me.

> It looks to me like it is only added to the User Variable path and not the System Variable path, Adding `%LOCALAPPDATA%\Microsoft\WinGet\Links` to the System Variable path seemed to resolve the issue for me.

Simply opening User Variable Path edit dialog and then clicking on "OK"s twice also resolves the issue.

**Comment by rlaphoenix** [comment] 2023-02-02 03:38
For me, `%LOCALAPPDATA%\Microsoft\WinGet\Links` was never added. Only `%LOCALAPPDATA%\Microsoft\WindowsApps`. I tried adding it to both user and system PATH, as well as one or the other, and nothing still.

I also tried undoing my change and just opening and hitting save twice, and still nothing.
The fact that did work for you has to be incredibly odd.

**Comment by GyanD** [comment] 2023-02-02 03:51
> This is because ffmpeg is a library and not truly a portable application or portable installer

The pkg being downloaded is ffmpeg-5.1.2-full_build.zip which contains three statically compiled i.e. standalone bnaries.

P.S. The PackageName in the locale files should be corrected to just FFmpeg.

**Comment by Trenly** [comment] 2023-02-02 03:59
> The pkg being downloaded is ffmpeg-5.1.2-full_build.zip which contains three statically linked i.e. standalone bnaries.

My mistake, I was misunderstanding between multiple issues

**Comment by rlaphoenix** [comment] 2023-02-02 04:06
> > This is because ffmpeg is a library and not truly a portable application or portable installer
> 
> The pkg being downloaded is ffmpeg-5.1.2-full_build.zip which contains three statically linked i.e. standalone bnaries.
> 
> P.S. The PackageName in the locale files should be corrected to just FFmpeg.

I think the package names require authors, and therefore it should be Gyan.FFmpeg as it is now. Theoretically, it could be FFmpeg.FFmpeg, however, FFmpeg did not author the builds themselves.

**Comment by GyanD** [comment] 2023-02-02 04:10
I'm referring to PackageName, not PackageIdentifier.
See line 12 of https://github.com/microsoft/winget-pkgs/blob/master/manifests/g/Gyan/FFmpeg/5.1.2/Gyan.FFmpeg.locale.en-US.yaml and https://github.com/microsoft/winget-pkgs/blob/master/manifests/g/Gyan/FFmpeg/5.1.2/Gyan.FFmpeg.locale.zh-CN.yaml

'Codex FFmpeg' is the name of my site. The package is simply 'FFmpeg;'.

**Comment by rlaphoenix** [comment] 2023-02-02 04:14
> I'm referring to PackageName, not PackageIdentifier. See line 12 of https://github.com/microsoft/winget-pkgs/blob/master/manifests/g/Gyan/FFmpeg/5.1.2/Gyan.FFmpeg.locale.en-US.yaml and https://github.com/microsoft/winget-pkgs/blob/master/manifests/g/Gyan/FFmpeg/5.1.2/Gyan.FFmpeg.locale.zh-CN.yaml
> 
> 'Codex FFmpeg' is the name of my site. The package is simply 'FFmpeg;'.

Ahh my mad. I do agree with this.

**Comment by SpecterShell** [comment] 2023-02-02 04:37
> P.S. The PackageName in the locale files should be corrected to just FFmpeg.

I forgot to change the PackageName and have opened a PR for this 😂:
https://github.com/microsoft/winget-pkgs/pull/95368

**Comment by mstevens83** [comment] 2023-02-02 08:18
> Doesn't work for me, I had to explicitly put `\ffmpeg-5.1.2-full_build\bin` to the end of the environment path. It looks like you're either on Linux or using a different terminal to me. Maybe it's something to do with that? But I tried Windows Terminal, PowerShell (latest from the Windows Store), normal PowerShell, and Command Prompt. It didn't work on any.
> 
> The normal environment path has nothing but that `ffmpeg-5.1.2-full_build` folder within it. Maybe a solution would be to symlink the ffmpeg, ffprobe and ffplay binaries to the root?

I have the exact same problem.
This was added my PATH: `C:\Users\steven89\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\`
But the exe's live 2 folders deeper: `C:\Users\steven89\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-5.1.2-full_build\bin`

**Comment by sitiom** [comment] 2023-02-02 08:20
> and whether or not developer mode is enabled. Might have something to do with symlink creation

I have developer mode enabled, and it works for me. Is it related to that? Does Winget not create symlinks on non-developer machines and adds the binary directly to the PATH instead? If so, that is a non-developer mode-specific bug.

**Comment by mstevens83** [comment] 2023-02-02 08:27
> > and whether or not developer mode is enabled. Might have something to do with symlink creation
> 
> I have developer mode enabled, and it works for me. A symlink is added to `%localappdata%\Microsoft\WinGet\Links\`, people who report it to not work have the binary PATH directly added instead. Is it related to that? Does Winget not create symlinks on non-developer machines and adds the binary directly to the PATH instead? If so, that is a non-developer mode-specific bug.

What "developer mode" are you referring to? Is this a winget-cli thing? A powershell thing? Windows itself?
As you can tell from the question it is safe to assume I'm not running developer mode :), so you may be on to something.

**Comment by sitiom** [comment] 2023-02-02 08:30
> What "developer mode" are you referring to? Is this a winget-cli thing? A powershell thing? Windows itself?

See https://learn.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development. Yes, it is a Windows thing. The important thing that you need to know is that symlinks normally only work under admin, and developer mode bypasses that:
![image](https://user-images.githubusercontent.com/56180050/216271520-34c7f9c3-1d97-456e-b3f9-518134297b0a.png)

Try enabling it and see if it resolves your problem.

**Comment by mstevens83** [comment] 2023-02-02 08:33
> > What "developer mode" are you referring to? Is this a winget-cli thing? A powershell thing? Windows itself?
> 
> See https://learn.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development. Yes, it is a Windows thing. The important thing that you need to know is that symlinks normally only work under admin, and developer mode bypasses that: 
> 
> I'm thinking the "Add binary directory to PATH directly" is a fallback to non-admin and non-developer mode machines. Try enabling it and see if it resolves your problem.

Ok, I'll try that. But even if it would fix my problem, there is still a bug at work here, no? The path added to PATH on non-developer mode machines should not be incomplete...

**Comment by sitiom** [comment] 2023-02-02 08:38
I am now able to replicate this bug by turning off developer mode. Note that [`refreshenv`](https://github.com/chocolatey/choco/blob/develop/src/chocolatey.resources/redirects/RefreshEnv.cmd) is a Chocolatey command that  refresh environment variables in the current terminal session:
![image](https://user-images.githubusercontent.com/56180050/216272862-4764c16d-e42e-49e5-8dd1-98e4e8101315.png)

**Comment by sitiom** [comment] 2023-02-02 09:26
- I have opened up an issue for it: https://github.com/microsoft/winget-cli/issues/2909. This bug should only affect people with non-admin and non-developer mode enabled.

**Comment by rlaphoenix** [comment] 2023-02-05 22:57
This same issue is happening with `aria2.aria2`, in the exact same way.

**Comment by KevinMarquette** [comment] 2023-04-15 21:52
I also ran into this issue. Fresh Win11 install, unelevated, no developer mode.

    winget install ffmpeg

Closed and opened the terminal, then checked the path:

    PS> $env:path -split ';'
    ...
    C:\Users\kevma\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe
    
    PS> ls C:\Users\kevma\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe
    Mode                 LastWriteTime         Length Name
    ----                 -------------         ------ ----
    d-----         4/15/2023   2:38 PM                ffmpeg-6.0-full_build
   
Going deeper into the path, at `\ffmpeg-6.0-full_build\bin`, I can find the executables.

        Directory: 
    C:\Users\kevma\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe
    \ffmpeg-6.0-full_build\bin

    Mode                 LastWriteTime         Length Name
    ----                 -------------         ------ ----
    -a----          3/4/2023  11:54 AM      131666944 ffmpeg.exe
    -a----          3/4/2023  11:54 AM      131504128 ffplay.exe
    -a----          3/4/2023  11:54 AM      131544064 ffprobe.exe

**Comment by davidnr** [comment] 2023-04-23 01:13
Same here

**Comment by mdanish-kh** [comment] 2023-04-29 16:21
Resolved in WinGet [v1.5.1081-preview release](https://github.com/microsoft/winget-cli/releases/tag/v1.5.1081-preview)

**Comment by ZhiZe-ZG** [comment] 2023-04-30 02:17
It may be a bug. For now, try `winget install Gyan.FFmpeg` with administrator status.

**Comment by mdanish-kh** [comment] 2023-05-01 17:15
> Resolved in WinGet [v1.5.1081-preview release](https://github.com/microsoft/winget-cli/releases/tag/v1.5.1081-preview)

Close with reason: Stated above;

**Closed by mdanish-kh** 2023-05-01 17:15 UTC
Labels: Issue-Bug

**Comment by rvxfahim** [comment] 2023-05-21 17:51
> Resolved in WinGet [v1.5.1081-preview release](https://github.com/microsoft/winget-cli/releases/tag/v1.5.1081-preview)

I tried with the prerelease winget, doesn't solve for me.

**Comment by GavinRay97** [comment] 2023-05-27 18:54
This is happening for me still as a heads up

The issue is that the install seems to add the parent directory to the PATH, instead of `full-build/bin`:

![image](https://github.com/microsoft/winget-pkgs/assets/26604994/6bfcac63-27cd-4975-8e05-50a89a452679)

**Comment by brizolara** [comment] 2023-05-27 19:06
> The issue is that the install seems to add the parent directory to the PATH, instead of `full-build/bin`

Same here...

**Comment by mdanish-kh** [comment] 2023-05-27 20:56
@rvxfahim Did you already have an installation of ffmpeg from an older version of WinGet?

@GavinRay97 @brizolara Can you please share the version of WinGet you are running from `winget -v` command?

**Comment by GavinRay97** [comment] 2023-05-27 21:04
@mdanish-kh Certainly, thanks for the swift reply (and on a weekend, no less)

```ps1
S C:\Users\rayga> winget -v
v1.4.11071
```

I suspect this is because of your earlier comment:

https://github.com/microsoft/winget-pkgs/issues/95349#issuecomment-1528823080
> Resolved in WinGet [v1.5.1081-preview release](https://github.com/microsoft/winget-cli/releases/tag/v1.5.1081-preview)

Sorry, I should have double-checked my version. For some reason I thought WinGet auto-updated.

**Comment by mdanish-kh** [comment] 2023-05-27 21:19
@GavinRay97 An uninstall would be required first to benefit from the fix. I would advise uninstalling the package first from WinGet 1.4 (if you haven't upgraded already) as there's a bug currently in the preview version where the uninstall command gets stuck infinitely for these packages if there is a prior installation from WinGet 1.4.

If you have upgraded though, the most convenient workaround I've found is to downgrade to WinGet 1.4 (i.e. download and install msix from https://github.com/microsoft/winget-cli/releases/download/v1.4.10173/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle), force uninstall the package using `winget uninstall ffmpeg --force`, then upgrade to the preview release and install the package with `winget install ffmpeg`

**Comment by rvxfahim** [comment] 2023-05-27 21:42
> @rvxfahim Did you already have an installation of ffmpeg from an older version of WinGet?

yes, I installed 1.4 then force uninstalled and then installed preview version of winget and then installed ffmpeg. Now it works

**Comment by mtuan293** [comment] 2023-06-07 07:37
> * I have opened up an issue for it: [Root directory of portable packages is always added to the PATH regardless of `RelativeFilePath` winget-cli#2909](https://github.com/microsoft/winget-cli/issues/2909).
> 
> This bug should only affect people without developer mode enabled and don't have admin previlages.

can confirm I still get this bug as of June of 2023.
I didn't turn on Developer Mode at all, just launch Terminal as admin that makes a difference.

- Without admin privileges: `C:\Users\_YourName_\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe` got added as PATH. Nothing in `C:\Users\Tuan\AppData\Local\Microsoft\WinGet\Links`, it's just an empty folder.
- With admin privileges: `C:\Users\Tuan\AppData\Local\Microsoft\WinGet\Links` is added as PATH instead. There are also 3 symlinks: "ffmpeg.exe", "ffplay.exe" and "ffprobe.exe" in this folder.

**Comment by MJWexer** [comment] 2023-06-21 15:38
Confirmed issue and solution for 6.0
..\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-6.0-full_build\bin

**Comment by B4ttleMast0r** [comment] 2023-06-27 22:43
Why was this closed? I have the same issue. It added the path two directories up to PATH instead of the bin directory

**Comment by dan-mcdonald** [comment] 2023-07-03 19:53
> Why was this closed? I have the same issue. It added the path two directories up to PATH instead of the bin directory

@B4ttleMast0r I had the same problem as you, but it was because I didn't carefully read the all the messages in this thread. It is fixed only if you installed FFmpeg with winget 1.5+. It has been in release candidate stage for almost a month so hopefully they can push it to GA soon and us poor folks will stop cutting our metaphorical fingers on this issue.

**Comment by XueshiQiao** [comment] 2023-07-28 07:18
> > Also tried in my virtual machine. Even if the directory `C:\Users\<Username>\AppData\Local\Microsoft\WinGet\Links` has been added to PATH and can be seen in the system's "Environmental Variables" settings, it is not shown in the subsequent processes. 🤔
> 
> I believe you need to fully close all previous terminals, then open a new one for it to actually refresh. Hence why it's not in your PATH yet.

works for me, thank you.

**Comment by ZhymabekRoman** [comment] 2023-08-15 09:09
+1, Same error: as workaround:
```
$env:path += ";C:\Users\Administrator\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-6.0-full_build\bin"
```

**Comment by seancheung** [comment] 2024-04-02 03:01
For me, I found out that I wasn't running winget as admin. It got installed but no environment variables can be added.

**Comment by JetUni** [comment] 2024-05-09 23:30
Still not working for me with fresh install on Windows 11 22H2
Winget `v1.7.11261`
FFmpeg `C:\Users\Administrator\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-7.0-full_build\bin`

**Comment by mikfar** [comment] 2024-05-11 20:00
I uninstalled the package and reinstalled as admin, then the PATH was actually updated.

**Comment by rlaphoenix** [comment] 2024-05-11 20:08
I recently clean installed Windows 11 with the latest Media Creation Tool -> USB. I did `winget install ffmpeg` as admin and it properly added to path correctly for ffmpeg, ffplay, and ffprobe. I did not attempt without admin but I presume it would have failed.

**Comment by dave2nian** [comment] 2024-09-14 06:09
when you used command: "winget install ffmpeg" 
the bin PATH maybe not add in windows 11.

resolution: 

run sysdm.cply
to add a new record in $PATH in Windows 
its path as below:
C:\Users\<username>\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-7.0.2-full_build\bin

updated Sep.14 2024.

**Comment by NeoMod** [comment] 2024-10-25 13:35
> when you used command: "winget install ffmpeg" the bin PATH maybe not add in windows 11.
> 
> resolution:
> 
> run sysdm.cply to add a new record in $PATH in Windows its path as below: C:\Users<username>\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-7.0.2-full_build\bin
> 
> updated Sep.14 2024.

thank you @dave2nian, I was trying to figure out where the binary was after using winget.

**Comment by ArhumMK** [comment] 2025-03-01 22:05
> when you used command: "winget install ffmpeg" the bin PATH maybe not add in windows 11.
> 
> resolution:
> 
> run sysdm.cply to add a new record in $PATH in Windows its path as below: C:\Users<username>\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-7.0.2-full_build\bin
> 
> updated Sep.14 2024.

This is only a temporary workaround as this somehow gets removed from PATH each time FFmpeg updated by winget.

**Comment by ArhumMK** [comment] 2025-03-28 21:00
> > when you used command: "winget install ffmpeg" the bin PATH maybe not add in windows 11.
> > resolution:
> > run sysdm.cply to add a new record in $PATH in Windows its path as below: C:\Users\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-7.0.2-full_build\bin
> > updated Sep.14 2024.
> 
> This is only a temporary workaround as this somehow gets removed from PATH each time FFmpeg is updated by winget.

Returning to this post to let you know that yt-dlp is also affected by this issue, possibly due to the FFmpeg package being a dependency for it; both FFmpeg and yt-dlp gets removed from PATH each time yt-dlp gets an update.

No idea why this issue has been closed as it still persists very consistently for both FFmpeg and yt-dlp, having to manually add both programs each time one of them gets an update (which is quite frequent) is starting to get tiring.

**Comment by EmileDirigera** [comment] 2025-04-29 11:31
@ArhumMK 

> No idea why this issue has been closed

Best guess is that the [fault is with WinGet](https://github.com/microsoft/winget-pkgs/issues/95349#issuecomment-1413044906) and not not entierly with FFmpeg.
