### ISSUE TITLE
[Package Request]: Apache Maven

### ISSUE THREAD

**Issue by migueltercero** [microsoft/winget-pkgs#70971] opened 2022-08-19 09:51 UTC
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Apache Sorftware Foundation
Publisher Url: https://maven.apache.org/download.cgi
Package Name: Apache Maven
Description: Apache Maven is a software project management and comprehension tool. Based on the concept of a project object model (POM), Maven can manage a project's build, reporting and documentation from a central piece of information
Package Version: 3.8.6
Installer URL: https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.zip

**Comment by Trenly** [comment] 2022-08-19 12:10
Duplicate of #65391

**Closed** 2022-08-19 12:10 UTC
Labels: Help-Wanted, Package-Request, Needs-Triage
