### ISSUE TITLE
GOG Galaxy has unknown version

### ISSUE THREAD

**Issue by BlueTooth4269** [microsoft/winget-pkgs#27206] opened 2021-09-08 08:53 UTC
# Brief description of your issue

When installing GOG Galaxy using Winget, it does not seem to register the version correctly. After installation, it says version "unknown", still lists it in the upgrade list and reinstalls when using `winget upgrade --all`

# Steps to reproduce

Install GOG Galaxy using `winget install GOG.Galaxy -i`

# Expected behavior

The version should be registered correctly and not be "unknown".

# Actual behavior

The version is not registered correctly and is "unknown".

# Environment

```
winget --info
Windows Package Manager v1.0.11692
Windows: Windows.Desktop v10.0.19043.1165
Paket: Microsoft.DesktopAppInstaller v1.12.11692.0
```

**Comment by ItzLevvie** [comment] 2021-09-08 08:54
GOG Galaxy doesn't display a version in Control Panel, therefore, Windows Package Manager doesn't know what version you have installed on your machine.

**Comment by ItzLevvie** [comment] 2021-10-12 14:17
> > Alternatively, if you want to partially fix this, you can add a `DisplayVersion` key and make it "Unknown", so that way the Windows Package Manager won't be able to upgrade the application when running the `winget upgrade` command. You may or will have to readd the DisplayVersion key every time the application automatically updates to prevent this behavior.
> 
> With all due respect, the fact that adding "Unknown" to a DisplayVersion key works with `winget` while the key missing completely does _not_ points to at least a minor bug or improvement to `winget` itself. How is the key missing effectively any different than it being there with "Unknown" in it? `winget` should be improved to react the same in both situations.

There's a typo in my messages (this particular issue and previous issues), it's meant to match the version in the package from the repository rather than being set as Unknown.

When you're running `winget upgrade` it compares the version you've installed (from Control Panel/Registry) to the repository, since Unknown is larger than say `1.33.7`, it'll always upgrade it.

So setting the version temporarily to `1.33.7` fixes it to avoid wasting internet bandwidth.

**Comment by OfficialEsco** [comment] 2022-01-20 21:46
Resolved in https://github.com/microsoft/winget-pkgs/pull/38887

**Comment by MenaceInc** [comment] 2022-05-13 13:44
Sent a support request and this was the response I got

> Hello,
> 
> Thank you for your feedback.
> Our developers are already aware of this issue, unfortunately I cannot provide any ETA.
> I apologise for the inconvenience.
> 
> Regards,
> Cypers,
> GOG Support

Not sure why it's taking longer than 6 months to update an Inno Setup file but here we are.

**Comment by persechini** [comment] 2022-07-13 02:17
Still the same issues has not been fixed

**Comment by OfficialEsco** [comment] 2022-07-13 15:11
Is this not "resolved" in WinGet-CLI version 1.2?
In that case if its too annoying you can install [WinGet-CLI 1.3 Release Candidate](https://github.com/microsoft/winget-cli/releases)

Since GOG cannot be bothered to add 1 short line of code that is the only way.

**Comment by markusdd** [comment] 2022-09-24 19:35
I can confirm that current winget suppresses GOG Galaxy because the version string is unknown.

I also have raised another instance of the issue at GOG to make them aware of this ticket here and underline that it is an easy fix for them.

**Comment by fernandog** [comment] 2022-10-17 21:31
> I also have raised another instance of the issue at GOG to make them aware

already opened a ticked too.

In the meantime. I manually added DisplayVersion to registry

```
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{7258BA11-600C-430E-A759-27E2C691A335}_is1]
"DisplayVersion"="2.0.55.99"
```

**Comment by nbros** [comment] 2022-12-28 12:05
The version is available from the executable:
`(Get-Item "C:\Program Files (x86)\GOG Galaxy\GalaxyClient.exe").VersionInfo`

```
ProductVersion   FileVersion      FileName
--------------   -----------      --------
2.0.55.99        2.0.55.99        C:\Program Files (x86)\GOG Galaxy\GalaxyClient.exe
```

Couldn't WinGet use this as a fallback when the DisplayVersion registry key is missing?

**Comment by markusdd** [comment] 2022-12-28 15:00
No I guess. There is thousands of applications out there and if every single one is doing it their way something like Winget will never work.

I do not see why this issue takes so long to resolve frankly. It would take a dev at GOG probably 10 minutes to put this reg key in.

**Comment by OfficialEsco** [comment] 2022-12-28 15:10
@nbros that is actually another issue, Developers don't actually always add ProductVersion or FileVersion either, AND they can be different/incorrect...

When we complain about the DisplayVersion missing they for some reason look into the ProductVersion/FileVersion which is a different part of the installer...

The reason this takes forever is because the company simply does not care about their userbase which GOG have proven quite well lately.

**Comment by mwisnicki** [comment] 2023-02-11 21:25
Also some software may be discontinued or have very long release cycles so the current limited behavior is completely unreasonable. Winget needs to handle such cases otherwise it will be forever pain to use.

**Comment by markusdd** [comment] 2023-02-11 21:31
disagree. showing up in a package manager for user convencience should demand SOME consistency.
We're debating this as if we are asking for something outreagous here.
Just put the version in the proper place and it's fixed.

**Comment by mwisnicki** [comment] 2023-02-11 21:38
Good luck convincing every vendor, some of which might not even exist anymore.

**Comment by RadAd** [comment] 2023-02-12 01:50
Installers that dont comply shouldnt be allowed in wingets repository.

It should be part of wingets acceptance criteria that after the installation winget can check the version is reporting what it thought it just installed.

**Comment by xIUPITERx** [comment] 2023-03-22 09:47
It's now fixed.

**Comment by irzyxel** [comment] 2023-03-31 18:31
borken again.
worked in gog 2.0.60.2, broken again in 2.0.61.63.

Name                                              ID                                 Version        Verfügbar    Quelle
-----------------------------------------------------------------------------------------------------------------------
GOG GALAXY                                        GOG.Galaxy                         2.0.60.2       2.0.61.63    winget

after install 
GOG GALAXY                                        GOG.Galaxy                         Unknown        2.0.61.63    winget

**Comment by markusdd** [comment] 2023-03-31 18:35
yup, I also noticed that. Seems to be hard xD

**Comment by mdanish-kh** [comment] 2023-03-31 19:22
I've noticed this is a problem in the upgrade scenario. The installer writes DisplayVersion to registry on a fresh install, but seems to somehow remove it when upgrading "in-place" from a previous version.

We can have a fix for it from WinGet's side by adding `UpgradeBehavior: uninstallPrevious` in GOG's manifest for WinGet to invoke the uninstaller first before installing the package. This would act as a "clean" installation and users might lose their previous configurations (if any). I've tested it manually and the DisplayVersion is set properly after the uninstall and install process.

I'm not a user of the package, so I would like to know if a "clean" install would be a problem for the users of the package

**Comment by Trenly** [comment] 2023-05-03 21:42
This should be resolved once https://github.com/microsoft/winget-pkgs/pull/105651 gets merged in

**Comment by ljredux** [comment] 2023-08-30 10:04
I can't believe this situation with GOG. Galaxy is ongoing.  It's what... over two years now?  Their developers are doing a sterling job of underlining why correct versioning info inclusion should be enforced if packages wish to remain in the Winget repository.

**Closed** 2023-12-07 16:51 UTC
Labels: Help-Wanted, Area-External

**Comment by ljredux** [comment] 2024-06-25 11:11
"Completed", "requires a fix from a third party", but no way of getting third party to address the issue, never mind fix the problem, so "use chocolatey instead of winget" seems to be the way to go.  Their maintainers seem to do a better job of enforcing package integrity.
