### ISSUE TITLE
[Package Issue]: VLC Player wrong version shown

### ISSUE THREAD

**Issue by dafunks** [microsoft/winget-pkgs#59869] opened 2022-05-09 19:34 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Winget showing version 3.0.17.0 of VLC media player VideoLAN.VLC but installed version is 3.0.17.4
So showing incorrect version of installed VLC player

### Steps to reproduce

Install VLC player and it will always say it needs updating due to incorrect version.

### Actual behavior

Wrong version shown so always needs updating

### Expected behavior

Once installed it would not need updating due to correct version being shown

### Environment

```shell
Windows: Windows.Desktop v10.0.22000.613
Package: Microsoft.DesktopAppInstaller v1.18.692.0
```

### Screenshots and Logs

https://i.imgur.com/juihyyo.png
https://i.imgur.com/rhEFlxk.png

**Comment by ItzLevvie** [comment] 2022-05-09 19:50
Duplicate of https://github.com/microsoft/winget-cli/issues/2111#issuecomment-1104365472

**Closed** 2023-12-07 16:51 UTC
Labels: Issue-Bug, Area-External
