### ISSUE TITLE
[Package Request]: KDE.Alligator.Nightly

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [microsoft/winget-pkgs#33706] opened 2021-11-03 12:17 UTC
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: KDE e.V.
Publisher Url: http://kde.org
Package Name: KDE.Alligator.Nightly
Description: http://apps.kde.org/alligator
Package Version: master-164
Installer URL: https://binary-factory.kde.org/view/Windows%2064-bit/job/Alligator_Nightly_win64/lastSuccessfulBuild/artifact/alligator-master-164-windows-msvc2019_64-cl.exe

Current Package Identifier (for new versions): master-164

**Comment by OfficialEsco** [comment] 2021-12-29 16:23
Duplicate of #39190

Please post your KDE requests here

**Closed** 2021-12-29 16:27 UTC
Labels: Help-Wanted, Package-Request
