### ISSUE TITLE
[Package Issue]: Google.AndroidStudio

### ISSUE THREAD

**Issue by C8H17OH** [microsoft/winget-pkgs#108921] opened 2023-06-05 11:40 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

After Google.AndroidStudio upgrading to version 2022.2.1.20, winget still recognizes it as version 2022.2.1.18 and prompts me to upgrade it. I have also tried to first uninstall (without clearing user configs, though) then install again, but the problem remains.

I have clicked "Check for Updates" in Android Studio and it says it's already newest. And the version it shows in "About" is "2022.2.1 Patch 2" which, as [Android Studio's release notes](https://developer.android.com/studio/releases/fixed-bugs/studio/2022.2.1#android-studio-flamingo-patch-2-2022.2.1.20) says, is 2022.2.1.20. So I'm sure the problem is not about failing to upgrade, but is about version recognition.

```
Android Studio Flamingo | 2022.2.1 Patch 2
Build #AI-222.4459.24.2221.10121639, built on May 12, 2023
Runtime version: 17.0.6+0-b2043.56-9586694 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 20
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    gradle.version.catalogs.dynamic.support=true
```

By the way:
1. The version shown in Windows Settings > Apps > Installed Apps is just 2022.2. Not sure whether related.
2. At least for now, there is no 2022.2.1.18 version in [Android Studio's release notes](https://developer.android.com/studio/releases/fixed-bugs/studio/2022.2.1). Being not familiar with its history and release cadence, I don't know why this number seems to be skipped. (Considering this, shall we remove this version from winget's packages, too?)
3. The uninstallation of Android Studio seems to work side by side instead of silently. I may create another issue about this. 

### Steps to reproduce

Upgrade Google.AndroidStudio from 2022.2.1.18 to 2022.2.1.20.

### Actual behavior

```
PS> winget upgrade
Name           Id                   Version     Available   Source
------------------------------------------------------------------
Android Studio Google.AndroidStudio 2022.2.1.18 2022.2.1.20 winget
1 upgrades available.
```

### Expected behavior

```
PS> winget upgrade
No upgrades available.
```

### Environment

```raw
PS> winget --info
Windows Package Manager v1.4.11071
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1778
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.11071.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by treysis** [comment] 2023-06-07 21:27
Same here. I believe it has to do with ARP table? But I have no idea what that means in winget context.

**Comment by justinkb** [comment] 2023-06-24 07:21
is there any reason to keep old minor version manifests in the repo? I'm pretty sure purging old minor versions would fix the issue

**Comment by alirahimifachr** [comment] 2023-10-01 12:57
i guess The problem is because of `Google.AndroidStudio.installer.yaml` where the `DisplayVersion` is not entered.  
maybe @russellbanks can help us who added this file.  

maybe we can set the DisplayVersion of AndroidStudio.installer same `PackageVersion`  

```yml
AppsAndFeaturesEntries:
- ProductCode: Android Studio
  DisplayVersion: "2022.3.1.19"
```

**Comment by phpcitizen** [comment] 2023-12-10 00:27
Same continues 2023.1.1.26

**Comment by niStee** [comment] 2024-02-18 19:25
Same continues 2023.1.1.28

**Comment by mdanish-kh** [comment] 2024-02-19 18:26
Can anyone who's facing this issue share the latest output for `winget list "Android Studio"`

**Comment by treysis** [comment] 2024-02-19 19:50
Here you go (both commands are the same):
```
C:\>winget list android
Name            Id                    Version      Available    Source
------------------------------------------------------------------
Android Studio  Google.AndroidStudio  2023.1.1.26  2023.1.1.28  winget
```

**Comment by mdanish-kh** [comment] 2024-02-19 20:02
And I'm assuming the actual version for Android Studio (can be seen from `appwiz.cpl`) is `2023.1.1`?

**Comment by treysis** [comment] 2024-02-19 20:04
No, it's just `2023.1` in ARP. And I think that's also a/the major problem: there is not enough distinction between versions for winget to look at. So either `Android Studio` updates its installer to provide extended version information to ARP, or `winget` needs to be modified to start looking for additional version information somewhere else as well. Until then I think it would be the correct way to pull Android Studio from the winget repository.

**Comment by mdanish-kh** [comment] 2024-02-19 20:06
> Until then I think it would be the correct way to pull Android Studio from the winget repository.

I have a couple ideas in mind that may work. I'll try and do those first, and request updates here once I'm done

**Comment by treysis** [comment] 2024-02-19 20:08
Ideas involving winget? Interested to hear them!

**Comment by mdanish-kh** [comment] 2024-02-19 20:12
Well some obvious issues I see looking at the manifests is that not all manifests for `Google.AndroidStudio` have the `DisplayVersion` value set. This is problematic, the general advice is that if one manifest needs DisplayVersion, then all manifests of that version must include that key to avoid version range, and infinite upgrade issues. Also DisplayVersion set for some manifests seems to be incorrect. And also that since multiple versions e.g., `2023.1.1.27` & `2023.1.1.28` share the same DisplayVersion `2023.1`, we can only include a single version (latest) with that DisplayVersion. This means we need to remove all other `2023.1.x.x` manifests and only ever include the latest in the repo

**Comment by treysis** [comment] 2024-02-19 20:14
Yeah, that's actually the only idea I have how we can get away without pulling Android Studio:
Purge all old versions of Android Studio and just keep the manifest for the latest/current version. Or have at maximum one manifest per 202x.x!

**Comment by mdanish-kh** [comment] 2024-02-19 20:17
> Or have at maximum one manifest per 202x.x!

This should be a good workaround, but requires contributors of this package to be aware of this context when updating the package. I'll try to keep watch of Android Studio PRs but it may get missed occasionally. Guess someone will make an issue for it if things go wrong 😄

**Comment by treysis** [comment] 2024-02-19 20:19
I can do the PRs for the old manifests. But yes, maintainers need to be aware or others need to step in.

**Comment by mdanish-kh** [comment] 2024-02-19 20:42
> I can do the PRs for the old manifests.

Sounds great! I'll come in and approve

**Comment by treysis** [comment] 2024-02-19 20:43
I wonder though if this will prevent updates to be shown. E.g. if 2023.1.1.29 comes out and the manifest for 2023.1.1.28 will be deleted, will we still be notified about an update? Does winget keep track of the `PackageVersion`?

**Comment by mdanish-kh** [comment] 2024-02-19 20:46
> I wonder though if this will prevent updates to be shown. E.g. if 2023.1.1.29 comes out and the manifest for 2023.1.1.28 will be deleted, will we still be notified about an update? Does winget keep track of the `PackageVersion`?

Unfortunately no, because Android Studio doesn't give a lot of version information, a side-effect of this will be users already on a `2023.1.x.x` version (that uses `DisplayVersion: 2023.1`) won't be notified for an update from WinGet. Once DisplayVersion changes to `2023.2`, winget will notify for an update

**Comment by mdanish-kh** [comment] 2024-02-19 20:53
Also, another thing (I assume this would be the case, I haven't tested) would be that once a new patch version comes out say `2023.1.1.29` and is added to winget repository with 2023.1.1.28 removed, the users that have existing installations of `2023.1.1.28` would get incorrect version shown in `winget list "Android Studio"`. WinGet will try to map the installed version to a DisplayVersion / PackageVersion here in the repo and will show them as:

```
winget list "Android Studio"
Name            Id                    Version      Source
------------------------------------------------------------------
Android Studio  Google.AndroidStudio  2023.1.1.29  winget
```
when they actually have the `2023.1.1.28` installed. Again, don't think anything else we can do here except request the publisher to write the full version to registry

**Comment by treysis** [comment] 2024-02-20 00:10
> when they actually have the `2023.1.1.28` installed. Again, don't think anything else we can do here except request the publisher to write the full version to registry

I have a feeling they don't care. JetBrains is notorious for not taking care of this version information for a decade, saying it's not an issue. Pulling Android Studio from the winget repository however might get their attention.

**Comment by treysis** [comment] 2024-02-20 12:57
Grrrr....and this is the version information from Android Studio when installed via JetBrains' `Toolbox` (i.e. their installation manager):
![image](https://github.com/microsoft/winget-pkgs/assets/26790192/42cda693-6c30-48e6-9636-44e05ea8a165)

**Comment by treysis** [comment] 2024-02-20 13:17
Btw. here's the link to the **10+ year old** bug report at JetBrains that documents their problematic behavior regarding version numbers:
https://youtrack.jetbrains.com/issue/IDEA-109831/Update-patch-should-refresh-links-in-Windows-start-menu-and-desktop

**Comment by mdanish-kh** [comment] 2024-02-20 18:57
Looks like all PRs for issues noticed in https://github.com/microsoft/winget-pkgs/issues/108921#issuecomment-1953102919 got merged. Can someone share the output of `winget list android` now and check whether they are facing the upgrade loop problem? (Also check that you don't have a side-by-side installation of Android studio. If you do, you would need to manually remove it from `appwiz.cpl` / Add or Remove Programs)

cc @C8H17OH (OP)
cc @niStee (most recent reporter)

**Comment by treysis** [comment] 2024-02-20 19:09
Fine on my end...for now.

**Comment by niStee** [comment] 2024-02-20 20:52
Same here

**Closed** 2024-02-29 03:52 UTC
Labels: No-Recent-Activity, Issue-Bug, Needs-Author-Feedback
