### ISSUE TITLE
[Update Request]: WinDirStat/WinDirStatt improperly detects v1.1.2 as "Unknown" (Installed Version:  Unknown - Update to 1.1.2 available)

### ISSUE THREAD

**Issue by ntman1** [microsoft/winget-pkgs#161769] opened 2024-07-06 21:41 UTC
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

WinDirStat.WinDirStat

### Package Version

1.1.2

### Please describe the changes you would like to see

The version of WinDirStat.WinDirStat located at https://github.com/microsoft/winget-pkgs/tree/master/manifests/w/WinDirStat/WinDirStat fails to detect either manual or WinGet versions of WinDirStat v1.1.2 as being WinDirStat v1.1.2, and misidentifies the WinDirStat v1.1.21 installation as "Unknown" (aka Installed Version:  Unknown - Update to 1.1.2 available) I am assuming based upon the manifest that it is installing the current package from https://sourceforge.net/projects/windirstat/files/windirstat/1.1.2%20installer%20re-release%20%28more%20languages%21%29/windirstat1_1_2_setup.exe/download, however when WinGet sees the package (eventhough it's showing properly in Control Panel -> Programs and Features or Settings -> Apps -> Installed Apps as v1.1.2 (however the original author's packaging may not be properly inserting the version number into the registry).

**Comment by ntman1** [comment] 2024-07-06 21:49
I put in a bug report to the developers regarding their installer - [https://github.com/windirstat/windirstat/issues/75](url)

**Comment by Trenly** [comment] 2024-07-06 22:20
* Duplicate of #54490 
* Duplicate of #88994

**Closed** 2024-07-06 22:20 UTC
Labels: Help-Wanted, Area-External, Package-Metadata
