### ISSUE TITLE
Support more than one manifest per PR

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/winget-pkgs#842] opened 2020-05-14 22:40 UTC
# Description of the new feature/enhancement
Today in order to submit a PR for a manifest, I can only do 1 at a time.  This is inefficient.  I would like to be able to have the ability to submit multiple Manifests in one PR.

For example if I am adding a new application, I may have one or more older builds I want to submit.  See Windows SDK for example:
17134, 17763, 19041, 18362

Or maybe I have multiple projects that release at one time like a suite, and each app would have its own manifest.  I should be able to submit them all.

# Proposed technical implementation details (optional)

I expect a submission to process each manifest individually.  This should be treated like a normal PR.  If the full submission does not pass, it is OK to fail the submission.  Similar to code.  However the BOT should communicate which manifest failed an why.

If the submission passes, then all manifests should be ingested.

**Comment by denelon** [comment] 2020-06-01 22:08
Duplicate of #125

**Closed by denelon** 2020-06-01 22:08 UTC
