### ISSUE TITLE
[Package Issue]: Mp3tag.Mp3tag version 3.19 Installer hash does not match

### ISSUE THREAD

**Issue by HulkSmashBurgers** [microsoft/winget-pkgs#101563] opened 2023-04-05 04:02 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

when attempting to install Mp3tag.Mp3tag, installation fails with "Installer hash does not match; this cannot be overridden when running as admin"

### Steps to reproduce

1. winget install Mp3tag.Mp3tag
2. wait for the download to complete
3. Winget will report "Installer hash does not match; this cannot be overridden when running as admin"

### Actual behavior

Winget reports "Installer hash does not match; this cannot be overridden when running as admin"

### Expected behavior

Winget installs Mp3tag.Mp3tag successfully.

### Environment

```raw
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1413
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
```

### Screenshots and Logs

[WinGet-2023-04-04-22-28-33.775.log](https://github.com/microsoft/winget-pkgs/files/11155067/WinGet-2023-04-04-22-28-33.775.log)
![Screenshot 2023-04-04 230142](https://user-images.githubusercontent.com/2564116/229977973-9745ce21-6185-49f8-815a-4c96a67dc3c2.png)

**Comment by phuzion** [comment] 2023-04-06 03:46
Looks like 3.19 was pulled for some reason. Submitting #101664 for 3.20 to hopefully resolve this issue.

**Comment by phuzion** [comment] 2023-04-12 14:54
Confirmed that #101664 fixes this issue.

**Comment by Trenly** [comment] 2023-05-01 23:34
Close with reason: Resolved with PR 101664;

**Closed by Trenly** 2023-05-01 23:34 UTC
Labels: Issue-Bug, Help-Wanted, Package-Update
