### ISSUE TITLE
[Version Unknown, Keeps showing in "winget upgrade"]: Mega.MEGASync

### ISSUE THREAD

**Issue by notthisoneguy** [microsoft/winget-pkgs#64458] opened 2022-06-26 10:37 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

When installing MEGASync using winget, winget is not able to detect the current installed version of MEGASync and thus always lists MEGASync as an available update when doing "winget upgrade"

### Steps to reproduce

1. Install MEGASync with winget "winget install Mega.MEGASync"
2. Run "winget upgrade"
3. MEGASync will always be listed there with version "Unknown" and winget will always claim there is an update available for MEGASync despite being freshly installed.

### Actual behavior

MEGASync always being listed in "winget upgrade". Installed version "Unknown".

### Expected behavior

Winget being able to detect the installed version of MEGASync and stop listing it in "winget upgrade" as soon as the version is up to date.

### Environment

```shell
PS C:\Windows\System32> winget --info
Windows-Paket-Manager v1.2.11601
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22000.739
Paket: Microsoft.DesktopAppInstaller v1.17.11601.0

Protokolle: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale
PS C:\Windows\System32>
```

### Screenshots and Logs

![Screenshot 2022-06-26 123549](https://user-images.githubusercontent.com/29334879/175810193-9c42390b-b7e4-448a-a3db-885fb63ee65d.png)

**Comment by Trenly** [comment] 2022-06-26 22:26
@notthisoneguy Thhos should be resolved by the [latest pre-release](/microsoft/winget-cli/releases) of the CLI. Can you attempt to reproduce this issue on the pre-release version?

This bug is caused by the publisher not setting the display version in the registry

**Comment by Trenly** [comment] 2022-06-26 22:27
Duplicate of #15946

**Closed** 2022-06-26 22:27 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by KrisSchneider** [comment] 2022-07-09 01:02
Hello, I'm also having a similar issue as well. https://github.com/microsoft/winget-cli/issues/2319
