### ISSUE TITLE
[New Feature]: Remove AI responses in issues

### ISSUE THREAD

**Issue by Exorcism0666** [microsoft/winget-pkgs#140259] opened 2024-02-20 20:48 UTC
### Description of the new feature/enhancement

More than half of users find the ai's answers useless and uninteresting.
![image](https://github.com/microsoft/winget-pkgs/assets/46537034/37af5641-fceb-4623-9cd8-956bb4d9a802)

**Comment by Trenly** [comment] 2024-02-21 01:38
> More than half of users

Do you have any data you can point to showing why you believe this claim to be true? How many issues does this actually affect compared to the number of issues submitted?

**Comment by CoolPlayLin** [comment] 2024-02-21 03:47
I think it just allows user to find similar issue as they created. If the issue is actually resolved in previous issue, users can find where the issue is instead of waiting for response from community. So, the AI response in issue should not be removed.

**Closed** 2024-02-25 14:39 UTC
Labels: Issue-Feature
