### ISSUE TITLE
[Package Issue]: OBS 

### ISSUE THREAD

**Issue by redragon21yt** [microsoft/winget-pkgs#116656] opened 2023-08-14 04:26 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Winget is installing the same version of OBS that I have currently installed. 

### Steps to reproduce

open the terminal and run widget update --all  it updates all the packages including OBS  version I already have 

### Actual behavior

Winget is installing OBS when it should not. 

### Expected behavior

Not to update apps that are already up to date. 

### Environment

```raw
Windows: Windows.Desktop v10.0.25926.1000
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.1573.0
```

### Screenshots and Logs

![OBS 29 1 3 - Profile_ Untitled - Scenes_ Untitled 8_13_2023 9_22_38 PM](https://github.com/microsoft/winget-pkgs/assets/138932223/d4c659cb-bc79-47df-b5c1-4a3ef464b33d)
![Windows PowerShell 8_13_2023 9_22_48 PM](https://github.com/microsoft/winget-pkgs/assets/138932223/5883a066-e241-4651-a244-33f3e88ed273)

**Comment by Trenly** [comment] 2023-08-14 12:59
* Duplicate of #83521

**Closed** 2023-08-14 12:59 UTC
Labels: Issue-Bug
