### ISSUE TITLE
[Package Request]: FreeFileSync

### ISSUE THREAD

**Issue by HeavySnowJakarta** [microsoft/winget-pkgs#130861] opened 2023-12-18 14:02 UTC
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://freefilesync.org/download.php
Publisher: FreeFileSync
Package Name: FreeFileSync
Description: FreeFileSync is a folder comparison and synchronization software that creates and manages backup copies of all your important files. Instead of copying every file every time, FreeFileSync determines the differences between a source and a target folder and transfers only the minimum amount of data needed. FreeFileSync is Open Source software, available for Windows, macOS, and Linux.
Package Version: 13.2
Installer URL: https://freefilesync.org/download/FreeFileSync_13.2_Windows_Setup.exe

**Comment by Trenly** [comment] 2023-12-18 19:36
Duplicate of #57900

**Closed** 2023-12-18 19:36 UTC
Labels: Help-Wanted, Package-Request
