### ISSUE TITLE
[Package Issue]: Microsoft.WindowsTerminal not installable on windows10 and error msg is misleading

### ISSUE THREAD

**Issue by bugrasan** [microsoft/winget-pkgs#61594] opened 2022-05-22 16:21 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Increasing the `MinimumOSVersion` from `10.0.18362.0` to `10.0.22000` makes the package uninstallable on windows 10.

also the returned error msg is insufficient to pin down the problem why the package is not installable.

### Steps to reproduce

```powershell
> winget search windowsterminal
Name                     Id                                Version      Source
-------------------------------------------------------------------------------
Windows Terminal Preview Microsoft.WindowsTerminal.Preview 1.13.10734.0 winget
Windows Terminal         Microsoft.WindowsTerminal         1.12.10983.0 winget

> winget install Microsoft.WindowsTerminal
No applicable installer found; see logs for more details.

> winget install Microsoft.WindowsTerminal -s winget
No applicable installer found; see logs for more details.

> [system.environment]::osversion.version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19044  0
```

### Actual behavior

no installation of package with a misleading error message:
```powershell
> winget install Microsoft.WindowsTerminal -s winget
No applicable installer found; see logs for more details.
```

### Expected behavior

Windows Terminal v1.12.10983.0 is still installable on windows 10 at least with the package from MS-Store.

### Environment

```shell
> winget --info
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1706
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

```log
...
2022-05-22 18:18:26.078 [REPO] Downloading manifest
2022-05-22 18:18:26.078 [CORE] WinINet downloading from url: https://winget.azureedge.net/cache/manifests/m/Microsoft/WindowsTerminal/1.12.10983.0/1899-Microsoft.WindowsTerminal.yaml
2022-05-22 18:18:26.904 [CORE] Download hash: 13986f2255623d2524b88da4db3c7fe5990af86c088bdf6eaed9a487d08f19b5
2022-05-22 18:18:26.904 [CORE] Download completed.
2022-05-22 18:18:26.909 [CLI ] Manifest fields: Name [Windows Terminal], Version [1.12.10983.0]
2022-05-22 18:18:26.910 [CLI ] Starting installer selection.
2022-05-22 18:18:26.910 [CLI ] Installer [X64,msix,Unknown,] not applicable: Current OS is lower than MinOSVersion 10.0.22000.0
2022-05-22 18:18:26.910 [CLI ] Installer [Arm64,msix,Unknown,] not applicable: Current OS is lower than MinOSVersion 10.0.22000.0
2022-05-22 18:18:26.911 [CLI ] Installer [Arm64,msix,Unknown,] not applicable: Machine is not compatible with Arm64
2022-05-22 18:18:26.911 [CLI ] Installer [X86,msix,Unknown,] not applicable: Current OS is lower than MinOSVersion 10.0.22000.0
2022-05-22 18:18:26.934 [CLI ] Terminating context: 0x8a150010 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:74
```

**Comment by bugrasan** [comment] 2022-05-22 16:25
installing a previous version works:
```powershell
> winget install microsoft.windowsterminal -v 1.12.10982.0
Found Windows Terminal [Microsoft.WindowsTerminal] Version 1.12.10982.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
  ██████████████████████████████  100%
Successfully installed
```

also the package information doesn't show the minimum OS level of the package, to be able to figure out the issue:
```powershell
> winget show microsoft.windowsterminal
Found Windows Terminal [Microsoft.WindowsTerminal]
Version: 1.12.10983.0
Publisher: Microsoft Corporation
Publisher Url: https://www.microsoft.com/
Publisher Support Url: https://github.com/microsoft/terminal/issues
Author: Microsoft
Moniker: terminal
Description: The new Windows Terminal, a tabbed command line experience for Windows.
Homepage: https://docs.microsoft.com/windows/terminal/
License: MIT
License Url: https://github.com/microsoft/terminal/blob/master/LICENSE
Privacy Url: https://privacy.microsoft.com/
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
Copyright Url: https://github.com/microsoft/terminal/blob/master/LICENSE
Release Notes: Changes
• The refreshed Windows 11 UI from the 1.13 preview builds is now available in 1.12!

Bug Fixes
Appearance
• Our Maximize/Restore button is now a fine round boi

Accessibility
• The profile list in the Settings UI now offers tooltips for long profile names
• We'll automatically focus the window renamer textbox when it opens
• High contrast will no longer result in a ridiculous and bad titlebar color
• When you delete a color scheme, we'll move focus back to the color scheme list
• When you delete a profile, we will re-focus the delete button automatically
• Two instances of huge debug log spam with a screen reader connected have been stamped out

Usability
• We've added some text to the color schemes page indicating that it is for editing--not setting--color schemes
  • We're working to refine how color schemes are set and edited, so stay tuned for future improvements!
• The retro terminal effect (as well as other shaders) will now work on pre-D3D11 hardware!
• Terminal will once again render properly when you move between different-DPI displays
• Resizing the window while a background color or underline is displayed will no longer smear it across the whole screen plus a fix for a huge crash that PR introduced
• It took us three releases to get it right, but we've finally solved the issue where we'd punch a hole straight through the Terminal when a dialog appeared

Reliability
• Typing an invalid background image path into the Settings UI will no longer send Terminal to a farm upstate
• There was an issue on Windows 11 where Terminal would queue up billions of animations while the screen was off; it will now no longer do so
• We've fixed crashes in ProposeCommandline, Monarch::_GetPID and other parts of WT's RPC infrastructure
• On Windows 10, the settings UI will no longer sometimes crash on close (we've updated to a new build of WinUI 2 for the fix!)

Miscellaneous
• Windows will no longer reject certain Terminal updates/reinstalls due to "differing package content"
• Fragments can once again override the names of generated profiles
• An issue from the 1073 series, where you could not upgrade the bundle using DISM, has been resolved
  • As a result, our bundle version is now over three thousand!
• @dmezh contributed some wording changes to the text about transparency/opacity
Release Notes Url: https://github.com/microsoft/terminal/releases/v1.12.10982.0/
Installer:
  No applicable installer found; see logs for more details.
````

**Comment by Trenly** [comment] 2022-05-23 03:38
Duplicate of microsoft/winget-cli#2134

**Comment by BrainSlugs83** [comment] 2023-11-10 18:10
Also not working on Windows 11.

**Comment by Trenly** [comment] 2024-05-01 14:21
Thank you for taking the time to report this issue. In the amount of time the issue has been open, there have been several updates to the WinGet CLI which may have helped mitigate some of these concerns. I encourage you to try out the [latest version](https://github.com/microsoft/winget-cli/releases/latest) of the CLI and see if your problem still persists. 

If additional problems persist, it would be extremely helpful if a new issue could be opened. Thanks!

###### Close with reason: Stale;

**Closed** 2024-05-01 14:21 UTC
Labels: Issue-Bug
