### ISSUE TITLE
[Update Request]: Godot Engine

### ISSUE THREAD

**Issue by AhegaHOE** [microsoft/winget-pkgs#150663] opened 2024-04-23 19:57 UTC
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

GodotEngine.GodotEngine

### Package Version

4.2.2

### Please describe the changes you would like to see

There is a new release (4.2.2) available.
It can be downloaded here: 
- https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_win64.exe.zip

**Comment by og-mrk** [comment] 2024-04-24 01:01
This Issue is a Duplicate of an older issue (https://github.com/microsoft/winget-pkgs/issues/149765), both this & the older issue should be resolved in https://github.com/microsoft/winget-pkgs/pull/150735 PR

**Closed** 2024-04-24 16:11 UTC
Labels: Help-Wanted, Package-Update
