### ISSUE TITLE
[Package Request]: Syncthing for Windows

### ISSUE THREAD

**Issue by SheepCommander** [microsoft/winget-pkgs#172267] opened 2024-09-07 22:21 UTC
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/Bill-Stewart/SyncthingWindowsSetup/releases/tag/v1.27.11
Publisher: Bill-Stewart
Package Name: SyncthingWindowsSetup
Description: a lightweight yet full-featured Windows installer for the open-source [Syncthing](https://syncthing.net/) file-synchronization application.
Package Version: 1.27.11
Installer URL: https://github.com/Bill-Stewart/SyncthingWindowsSetup/releases/tag/v1.27.11

**Comment by Trenly** [comment] 2024-09-10 02:43
* Duplicate of #102331

**Closed** 2024-09-10 02:43 UTC
Labels: In-PR, Package-Request
