### ISSUE TITLE
[Update Request]: LyX

### ISSUE THREAD

**Issue by Edoardo66** [microsoft/winget-pkgs#166605] opened 2024-08-07 09:26 UTC
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

LyX.LyX

### Package Version

2.3.5.2

### Please describe the changes you would like to see

There is a new release (x64) available (version 2.4.1)
Download at: [https://lyx.mirror.garr.it/bin/2.4.1/LyX-241-Installer-1-x64.exe](url)

**Comment by Trenly** [comment] 2024-08-07 17:22
Newer versions cannot be added due to an interactive only install which requires MikTex or TexLive to be on PATH.

* See https://github.com/microsoft/winget-pkgs/pull/62657 for more info

Duplicate of #54476

**Closed** 2024-08-07 17:22 UTC
Labels: In-PR, Package-Update
