### ISSUE TITLE
[Package Issue]: astral-sh.uv

### ISSUE THREAD

**Issue by theLastOfCats** [microsoft/winget-pkgs#182780] opened 2024-10-14 11:52 UTC
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

uvx is missing from installation

### Steps to reproduce

1. Clean install
2. Run `uvx` in pwsh

### Actual behavior

`uvx: The term 'uvx' is not recognized as a name of a cmdlet, function, script file, or executable program.`

### Expected behavior

uvx work correctly

### Environment

Windows Package Manager (Preview) v1.9.2411-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22635.4010
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.2411.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled

**Comment by theLastOfCats** [comment] 2024-10-14 11:52
ping @FishAlchemist

**Comment by theLastOfCats** [comment] 2024-10-14 11:53
Looks like it's missing `- RelativeFilePath: uvx.exe` [here ](https://github.com/microsoft/winget-pkgs/blob/master/manifests/a/astral-sh/uv/0.4.20/astral-sh.uv.installer.yaml#L9)

**Comment by FishAlchemist** [comment] 2024-10-14 13:00
> Looks like it's missing `- RelativeFilePath: uvx.exe` [here ](https://github.com/microsoft/winget-pkgs/blob/master/manifests/a/astral-sh/uv/0.4.20/astral-sh.uv.installer.yaml#L9)

I would like to confirm if this is the appropriate solution to the issue. Upon confirmation, I will submit a pull request to implement the fix.
```yaml
NestedInstallerFiles:
- RelativeFilePath: uv.exe
- RelativeFilePath: uvx.exe
```

**Comment by FishAlchemist** [comment] 2024-10-14 13:58
> Looks like it's missing `- RelativeFilePath: uvx.exe` [here ](https://github.com/microsoft/winget-pkgs/blob/master/manifests/a/astral-sh/uv/0.4.20/astral-sh.uv.installer.yaml#L9)

@theLastOfCats  I submitted a PR regarding the issue you mentioned earlier, but I'm not sure why the problem is only surfacing now.
None of the previous versions mentioned ``uvx.exe``. So why is there a problem with it now?
Weirdly, I don't have this problem on my Windows 11 23H2 Home (x86-64).

https://github.com/microsoft/winget-pkgs/blob/86079c52d9902386a0f7015f8975186b6611636f/manifests/a/astral-sh/uv/0.4.20/astral-sh.uv.installer.yaml#L8-L10
https://github.com/microsoft/winget-pkgs/blob/86079c52d9902386a0f7015f8975186b6611636f/manifests/a/astral-sh/uv/0.4.19/astral-sh.uv.installer.yaml#L8-L10
https://github.com/microsoft/winget-pkgs/blob/86079c52d9902386a0f7015f8975186b6611636f/manifests/a/astral-sh/uv/0.4.18/astral-sh.uv.installer.yaml#L8-L10
https://github.com/microsoft/winget-pkgs/blob/86079c52d9902386a0f7015f8975186b6611636f/manifests/a/astral-sh/uv/0.4.15/astral-sh.uv.installer.yaml#L8-L10
https://github.com/microsoft/winget-pkgs/blob/86079c52d9902386a0f7015f8975186b6611636f/manifests/a/astral-sh/uv/0.4.14/astral-sh.uv.installer.yaml#L8-L10
https://github.com/microsoft/winget-pkgs/blob/86079c52d9902386a0f7015f8975186b6611636f/manifests/a/astral-sh/uv/0.4.13/astral-sh.uv.installer.yaml#L8-L10
https://github.com/microsoft/winget-pkgs/blob/86079c52d9902386a0f7015f8975186b6611636f/manifests/a/astral-sh/uv/0.4.12/astral-sh.uv.installer.yaml#L8-L10
https://github.com/microsoft/winget-pkgs/blob/86079c52d9902386a0f7015f8975186b6611636f/manifests/a/astral-sh/uv/0.4.11/astral-sh.uv.installer.yaml#L8-L10
https://github.com/microsoft/winget-pkgs/blob/86079c52d9902386a0f7015f8975186b6611636f/manifests/a/astral-sh/uv/0.4.10/astral-sh.uv.installer.yaml#L8-L10
Older versions have been omitted from this list.

**Comment by stephengillie** [comment] 2024-10-14 16:19
Since #182796 is merged, I'll assume this Issue is complete. If this is in error - possibly to continue the above investigation - please @ me and I'll reopen.

**Closed by stephengillie** 2024-10-14 16:19 UTC
Labels: Issue-Bug, Needs-Triage
