### ISSUE TITLE
installed alacritty but it does not open

### ISSUE THREAD

**Issue by shalva97** [microsoft/winget-pkgs#25704] opened 2021-08-23 09:07 UTC
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

when opening alacritty it displays error "vcruntime140.dll not found"
# Steps to reproduce

winget install --id Alacritty.Alacritty

# Expected behavior
it should just open and work

# Actual behavior
shows missing dll error

![image](https://user-images.githubusercontent.com/22417494/130421151-6a5e4270-458a-4e03-b207-b050b2e520aa.png)

# Environment

```none
[winget --info]
Windows Package Manager version v1.0.11692
Windows: Windows.Desktop v10.0.19043.1165 
Package: Microsoft.DesktopAppInstaller v1.12.11692.0  

Any other software?
```

**Comment by OfficialEsco** [comment] 2021-08-23 10:33
Hay! This is a issue with Alacritty's installer, you need `Microsoft Visual C++ "some version"`, this issue will be resolved once we get Dependency support, however first we need to know the software's dependencies.

I just installed `Microsoft Visual C++ 2015-2019 Redistributable (x64)` and i get this:
![image](https://user-images.githubusercontent.com/15158490/130432384-83eca9bb-bf31-43a7-b643-75eb8f0610c1.png)
```
---------------------------
Alacritty: Runtime Error
---------------------------
panicked at 'gl function was not loaded', D:\a\alacritty\alacritty\target\release\build\alacritty-d8809205f1f2621c\out/gl_bindings.rs:11325:13

Press Ctrl-C to Copy
---------------------------
OK   
---------------------------
```

`Microsoft Windows Desktop Runtime - 3 (x64)`,  `Microsoft Windows Desktop Runtime - 5 (x64)` and `Microsoft Edge WebView2 Runtime` does not solve that issue

https://github.com/alacritty/alacritty/issues/4998 seems to be that issue, which is probably caused by Virtual Desktop not having `OpenGL 3.3+` support?

**Comment by shalva97** [comment] 2021-08-23 11:17
installing `Microsoft.VC++2015-2019Redist-x64` worked. it opens without issues.

**Comment by OfficialEsco** [comment] 2022-01-20 22:20
Duplicate of #25706

**Closed by OfficialEsco** 2022-01-20 22:20 UTC
Labels: Help-Wanted
