### ISSUE TITLE
[Bug]: winget cannot upgrade Microsoft Visual C++ 2008 Redistributable

### ISSUE THREAD

**Issue by ageekhere** [microsoft/winget-pkgs#47041] opened 2022-02-19 01:41 UTC
### Brief description of your issue

winget cannot upgrade Microsoft Visual C++ 2008 Redistributable  9.0.30729.4148 
```
Name                                            Id                           Version        Available      Source
-----------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2008 Redistributable - x86 Microsoft.VC++2008Redist-x86 9.0.30729.4148 9.0.30729.6161 winget
Microsoft Visual C++ 2008 Redistributable - x64 Microsoft.VC++2008Redist-x64 9.0.30729.4148 9.0.30729.6161 winget
2 upgrades available.
winget upgrade --all
No applicable update found.
```

### Steps to reproduce

install Microsoft Visual C++ 2008 Redistributable - x86 Microsoft.VC++2008Redist-x86 9.0.30729.4148
install Microsoft Visual C++ 2008 Redistributable - x64 Microsoft.VC++2008Redist-x86 9.0.30729.4148
And then try and use winget to upgrade

### Expected behavior

winget should find the new update and install it.

### Actual behavior

No applicable update found.

### Environment

```shell
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.527
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
```

**Comment by OfficialEsco** [comment] 2022-02-19 09:46
I'm not 100% sure, but i believe the new 1.2 client will fix this

**Comment by denelon** [comment] 2022-02-22 20:27
Duplicate of 
* microsoft/winget-cli/issues/1413

**Closed** 2022-02-22 20:27 UTC
Labels: Issue-Bug
