### ISSUE TITLE
Cannot be upgraded

### ISSUE THREAD

**Issue by murmir** [microsoft/winget-pkgs#86319] opened 2022-10-25 08:35 UTC
### Brief description of your issue

Android Studio cannot be upgraded

### Steps to reproduce

1) winget upgrade
2) winget upgrade --all
3) winget upgrade

### Expected behavior

successfully upgraded

### Actual behavior

Cannot be upgraded
![error](https://user-images.githubusercontent.com/39002022/197725207-1dd0a17c-c542-4218-bb17-84faa25b03b3.jpg)

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.675
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by denelon** [comment] 2022-10-26 15:21
Is there a command to get the package to display its version? I'm not sure if the upgrade didn't actually run or if the package isn't correctly updating the registry entry associated with the displayVersion property for Windows Apps & Features.

**Comment by murmir** [comment] 2022-10-27 07:09
> Is there a command to get the package to display its version? I'm not sure if the upgrade didn't actually run or if the package isn't correctly updating the registry entry associated with the displayVersion property for Windows Apps & Features.

![error](https://user-images.githubusercontent.com/39002022/198215020-5d3136e7-1a06-4cfe-a29f-56c0f40ebb38.jpg)

**Comment by denelon** [comment] 2022-10-27 18:26
What is displayed for the "displayVersion" in Windows Apps & Features?

I've got an example at https://devblogs.microsoft.com/commandline/windows-package-manager-1-3/#new-version-reporting for the scenario where there is a "marketing" version that is different from the "displayVersion".

I'm guessing 2021.3.1.16 was an initial release and 2021.3.1.17 was a patch to that release based on the UI.

If the registry entry isn't getting updated correctly in the "upgrade" flow, this might be an installer issue.

**Comment by murmir** [comment] 2022-10-30 05:33
![error](https://user-images.githubusercontent.com/39002022/198864147-5a72a9fc-00b8-46eb-ba55-ede597d01865.jpg)

**Comment by denelon** [comment] 2022-10-31 15:55
OK, so the version in the registry looks like "2021.3" which is the "displayVersion" in the registry. That's the value that WinGet looks at when making a determination if a new version of a package is an upgrade.

I do see the "file version" reported as 2021.1.3.0, but we don't track that specific file as a user could run an upgrade outside of WinGet. We do look at the file version as a proxy for the version if it's not displayed in the registry, but in this case, it is.

The ask would be for Android Studio to start reporting the full version in the "displayVersion" property. If they want a "marketing version", we can display that just like we do for .NET and other packages.

**Comment by russellbanks** [comment] 2022-11-04 11:22
I outlined the cause and fix for this here:
- https://github.com/microsoft/winget-pkgs/issues/86933

This should be resolved now, but let me know if it's not.

**Comment by murmir** [comment] 2022-11-06 13:50
Problem is solved. Thank you.

**Comment by russellbanks** [comment] 2022-11-14 16:01
Close with reason: Resolved;

**Closed** 2022-11-14 16:02 UTC
Labels: Issue-Bug, Help-Wanted, Area-External
