### ISSUE TITLE
[Package Issue]: Winget does not update x86 version of Microsoft.DotNet.DesktopRuntime.6

### ISSUE THREAD

**Issue by Cyberdroid1** [microsoft/winget-pkgs#81063] opened 2022-09-29 11:37 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When I am offered to update the x86 version of .NET 6 runtime, winget actually installs the x64 version. This ends up in the x86 version not getting updated.

### Steps to reproduce

1. Have an old version of .NET 6 runtime (x86) installed.
2. Run `winget upgrade Microsoft.DotNet.DesktopRuntime.6`.
3. Notice that winget tries to update the already up-to-date x64 version.

### Actual behavior

winget keeps downloading the x64 version.

### Expected behavior

I expect it to download and install the x86 version of .NET 6

### Environment

```shell
Windows Package Manager (Preview) v1.4.2161-preview
Windows: Windows.Desktop v10.0.25206.1000
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.2161.0
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/51435948/193020943-fde063ba-1d63-4bb5-bc8a-e71d2f235777.png)

**Comment by Trenly** [comment] 2022-09-29 14:18
Duplicate of https://github.com/microsoft/winget-cli/issues/2448

**Closed** 2022-09-29 15:18 UTC
Labels: Issue-Bug, Resolution-Duplicate

**Comment by yoyoda2048** [comment] 2023-07-01 17:02
Hi,
Sorry to post this so rudely, but how did you implement this beautiful coloured progress bar in Windows Shell ?

**Comment by Trenly** [comment] 2023-07-01 17:06
> Hi,
> Sorry to post this so rudely, but how did you implement this beautiful coloured progress bar in Windows Powershell ?

There is a setting for the appearance of the progress bar - 
https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md#progressbar

**Comment by yoyoda2048** [comment] 2023-07-01 17:17
thanks :)

**Comment by ChefBucher** [comment] 2023-09-04 06:36
hello 
i make it work with the following command
winget -a x86 --all
that upgraded the x86 packages sucesfully
hope it helps
