### ISSUE TITLE
Manifest Validation: Failed to process installer (MSIX only)

### ISSUE THREAD

**Issue by AmelBawa-msft** [microsoft/winget-pkgs#79677] opened 2022-09-15 17:06 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

MSIX Manifest installer validation fails for certain installers when attempting to stream the MSIX info from the installer URL during the validation.

### Steps to reproduce

https://github.com/microsoft/winget-pkgs/pull/75891

### Actual behavior

Manifest installer validation fails to get the MSIX info for certain installers.

### Expected behavior

Manifest installer validation should be able to get the MSIX info for all (MSIX) installers.

### Environment

```shell
WinGetUtil
```

**Comment by Jaifroid** [comment] 2022-10-05 21:29
@AmelBawa-msft @denelon I'm getting the same unexpected failure for the latest version of WikiMed (#82540), which I just submitted. I traced my way to this issue by looking for other PRs with the same Manifest-Installer-Validation-Error label, and finding the discussion in #75891. Thank you for creating an issue for that.

Is there any timeline on when this blocker might be addressed? Because it seems I can no longer upload the latest WikiMed manifests to winget. Please note that even if the manifest validation error is solved, we still have the issue that large (>1GB) msix/appxbundle packages from GitHub (at least) fail to install in winget locally (see screenshot), whereas small ones install fine. It may be a related issue. Unkown error `0x80072eff` is produced now whenever I try to install WikiMed via winget, whereas the smaller version of the same package, only without the compressed WikiMed archive, Kiwix.KiwixJS (~12MB) installs fine. So the size of the bundle seems to have something to do with this error. 

<img width="578" alt="image" src="https://user-images.githubusercontent.com/4304337/194166805-0060ec10-515a-4495-aac7-9573f8f019d8.png">

**Comment by denelon** [comment] 2022-10-06 21:44
@Jaifroid @AmelBawa-msft is looking at this issue, we've got a couple of approaches we're looking at. The issue is related to servers not honoring the call that we make when we try to validate without a full download. I would expect we will have this resolved before the 1.4 client is GA. This fix does not depend on that release per se' but we may have client improvements as well as service improvements.

**Comment by denelon** [comment] 2022-10-07 00:21
@Jaifroid how often do you have updates? I want to try and help get these validated manually until the fix is in.

**Comment by Jaifroid** [comment] 2022-10-07 04:36
@denelon Thank you for the updates. The Kiwix.WikiMed app (~1.3GB) is updated monthly, around the beginning of each month. The Kiwix.Wikivoyage app (also affected because it is ~660MB) is updated monthly around the middle of the month. The base Kiwix.KiwixJS app isn't affected because it is much smaller (~12MB). All the packages are hosted on GitHub releases. The reason for the monthly cycle is that it corresponds to the release of updated content by Kiwix org.

**Comment by denelon** [comment] 2022-10-07 15:06
Thanks @Jaifroid. That helps, and hopefully we only have one or two more times we'll need to validate manually.

**Comment by Jaifroid** [comment] 2022-10-29 09:34
Same error `0x80072eff : unknown error` happening with Kiwix.Wikivoyage, with installer 2.1.9, which I just got validated:
```
PS C:\Repos> winget update kiwix.wikivoyage
Found Wikivoyage by Kiwix [Kiwix.Wikivoyage] Version 2.1.9.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
An unexpected error occurred while executing the command:
0x80072eff : unknown error
```
The funny thing is, this one passed installation validation on your end, but in real-world usage, winget fails to install it on a fully up-to-date modern machine.

**Comment by Trenly** [comment] 2024-05-01 14:44
@amelbawa-msft - I believe this issue has been addressed as there have been several updates to the validation pipeline since the issue was opened. If it is not resolved, it would be extremely helpful if a new issue could be opened pointing to a the new failure.

###### Close with reason: Stale;

**Closed** 2024-05-01 14:44 UTC
Labels: Issue-Bug
