### ISSUE TITLE
Access Denied when installing Git

### ISSUE THREAD

**Issue by chrisvire** [microsoft/winget-pkgs#525] opened 2020-05-20 22:39 UTC
I tried installing Git.Git (`winget install -h --id Git.git`). It downloaded https://github.com/git-for-windows/git/releases/download/v2.26.2.windows.1/Git-2.26.2-64-bit.exe and at the end I got an "Access Denied" error.

**Comment by KevinLaMS** [comment] 2020-05-20 22:41
Thanks Chris.  I think this is a duplicate of https://github.com/microsoft/winget-cli/issues/247. Would you mind up voting?

**Comment by jefferai** [comment] 2020-05-21 16:40
I see that you closed the winget-cli bug. I want to note that out of 3 packages I tried installing, this happened to me for 2 of them (winscp, cpu-z). Not sure if this is specific to these manifests/applications or if this is a deeper bug that belongs in the other repo.

**Comment by jefferai** [comment] 2020-05-21 16:41
Also probably since you closed the other bug as a duplicate of this one you should remove the duplicate label from here?

**Comment by KevinLaMS** [comment] 2020-05-21 22:39
Sorry Jefferai  i meant this one.  Duplicate of https://github.com/microsoft/winget-cli/issues/189

**Closed by KevinLaMS** 2020-05-21 22:39 UTC
Labels: duplicate

**Comment by jefferai** [comment] 2020-05-23 21:10
To be clear I don't get "unable to write", I get "access denied". Not sure if it's the same or not.

**Comment by cderv** [comment] 2020-05-31 18:28
I get the same Access Denied issue when the download installer tries to execute.

**Comment by crramirez** [comment] 2021-05-27 08:57
Still happens in winget 1.0

**Comment by crramirez** [comment] 2021-05-27 08:58
![image](https://user-images.githubusercontent.com/8397379/119797336-6addc980-beda-11eb-85af-8786275c7060.png)

**Comment by electronic-dk** [comment] 2021-05-27 13:15
I've had the same issue, but at least I was able to install git from an elevated prompt, unlike discord which does not install from either a user nor an elevated prompt

**Comment by electronic-dk** [comment] 2021-05-27 13:16
AFAIK, correct git installation requires https://github.com/microsoft/winget-cli/issues/254
(But I'd prefer if git would just install into a user directory if there's no elevation)

**Comment by CreepasCraft** [comment] 2021-05-29 16:35
I get the same issue with android studio, discord, cpu-z and some others

**Comment by crramirez** [comment] 2021-05-31 11:41
Trick. It worked for me after I went to Settings->Apps & features searched for App Installer -> Advanced options->Reset

After that I could install things

**Comment by alex-ong** [comment] 2021-07-21 01:08
`Settings->Apps & features searched for App Installer -> Advanced options->Reset` did the trick for me.
