### ISSUE TITLE
[Package Request]: KDE.KAtomic.Nightly

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [microsoft/winget-pkgs#33737] opened 2021-11-03 14:54 UTC
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: KDE e.V.
Publisher Url: http://kde.org
Package Name: KDE.Katomic.Nightly
Description: http://apps.kde.org/katomic
Package Version: master-744
Installer URL: http://binary-factory.kde.org/view/Windows%2064-bit/job/KAtomic_Nightly_win64/lastSuccessfulBuild/artifact/katomic-master-744-windows-msvc2019_64-cl.exe

Current Package Identifier (for new versions): master-744

**Comment by jedieaston** [comment] 2021-11-03 15:06
Is there a particular reason we need the nightly builds over the stable ones? There hasn't been a commit to the Katomic repo in three months.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2021-11-03 15:29
> http://github.com/microsoft/winget-pkgs/issues/33737#issuecomment-959373879.

Personally, I only use developmental-stage software whenever I am able to, because usage of that has allowed me to prepare my other (stable) computers for the latest modification, remediate errata and regression, and provide assistance during development.

**Comment by OfficialEsco** [comment] 2021-12-29 16:23
Duplicate of #39190

Please post your KDE requests here

**Closed** 2021-12-29 16:25 UTC
Labels: Help-Wanted, Package-Request
