### ISSUE TITLE
[Package Request]: KDE.Filelight.Release

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [microsoft/winget-pkgs#33726] opened 2021-11-03 13:29 UTC
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: KDE e.V.
Publisher Url: http://kde.org
Package Name: KDE.Filelight.Nightly
Description: http://apps.kde.org/filelight
Package Version: master-785
Installer URL: http://binary-factory.kde.org/view/Windows%2064-bit/job/Filelight_Release_win64/lastSuccessfulBuild/artifact/filelight-21.08.2-785-windows-msvc2019_64-cl-sideload.appx

Current Package Identifier (for new versions): master-785

**Comment by OfficialEsco** [comment] 2021-12-29 16:23
Duplicate of #39190

Please post your KDE requests here

**Closed** 2021-12-29 16:29 UTC
Labels: Help-Wanted, Package-Request
