### ISSUE TITLE
[Package Request]: KDE.Cantor.Release

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [microsoft/winget-pkgs#33719] opened 2021-11-03 13:13 UTC
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: KDE e.V.
Publisher Url: http://kde.org
Package Name: KDE.Cantor.Release
Description: http://apps.kde.org/cantor
Package Version: master-338
Installer URL: http://binary-factory.kde.org/view/Windows%2064-bit/job/Cantor_Release_win64/lastSuccessfulBuild/artifact/cantor-21.08.2-338-windows-msvc2019_64-cl.exe

Current Package Identifier (for new versions): master-338

**Comment by OfficialEsco** [comment] 2021-12-29 16:23
Duplicate of #39190

Please post your KDE requests here

**Closed** 2021-12-29 16:29 UTC
Labels: Help-Wanted, Package-Request
