### ISSUE TITLE
issue after installing discord

### ISSUE THREAD

**Issue by ivonenchev** [microsoft/winget-pkgs#77947] opened 2022-09-03 14:23 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

After install the discord with the following command : 

 winget install Discord.Discord,

The installation has finished successful, but when I tried to run the application I face the follwoing issue : 

A fatal Javascript error occured. 

![Dicord Javascript fatal error](https://user-images.githubusercontent.com/32977349/188274587-b6a6c40b-7b49-4981-afa0-6ff4f670d2d4.jpg)

### Steps to reproduce

Try to execute the application. 

### Actual behavior

When I tried to execute the Discord application, I face windows with description A fatal Javascript error occured. 

### Expected behavior

To execute the application succesful 

### Environment

```shell
Windows Package Manager v1.3.2091
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.918
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2091.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

![Dicord Javascript fatal error](https://user-images.githubusercontent.com/32977349/188274674-579c1b89-52da-4812-bd94-37afa6f5e9d2.jpg)

**Comment by mdanish-kh** [comment] 2022-09-03 15:00
- Duplicate of #77925

**Comment by ItzLevvie** [comment] 2022-09-04 00:24
Close with reason: This should now be resolved;

Uninstall Discord by running `winget uninstall --id Discord.Discord` and then reinstall Discord by running `winget install --id Discord.Discord`

**Closed** 2022-09-04 00:24 UTC
Labels: Issue-Bug, Needs-Triage
