### ISSUE TITLE
[Update Request]: SysInternals packages

### ISSUE THREAD

**Issue by lzybkr** [microsoft/winget-pkgs#110851] opened 2023-06-28 19:39 UTC
### What type of update are you requesting?

Something else not listed

### Current Package Identifier

Microsoft.Sysinternals.ProcessMonitor

### Package Version

3.94

### Please describe the changes you would like to see

The packages under `Microsoft.Sysinternals` all point to the same URL. This causes problems when the tools are updated to new versions - you end up getting an error about a mismatched hash.

This means you can't reliably install a package like `Microsoft.Sysinternals.ProcessMonitor` because it could get updated at any time . For example, I updated `Microsoft.Sysinternals.ProcessMonitor` a couple days ago for version 3.94, and a day later version 3.95 was published.

I'm not sure what the solution here is - maybe don't provide hashes? And drop the version numbers too since you can't install old versions?

**Comment by mdanish-kh** [comment] 2023-06-28 19:42
Duplicate of #110788

Will be resolved once #110846 gets merged

**Closed** 2023-06-28 19:42 UTC
Labels: Help-Wanted, Needs-Triage, Package-Update

**Comment by lzybkr** [comment] 2023-06-28 19:45
@mdanish-kh - That won't really resolve the problem long term though, installs will be broken the next time the package is updated.

**Comment by mdanish-kh** [comment] 2023-06-28 20:02
@Izybkr Apologies for marking this as duplicate without answering you; Currently there is some automation set-up for these "vanity URLs" i.e., URLs that always point to the latest version of a release. @wingetbot checks for hash mismatches daily in the repo and usually updates these kind of packages in its [automatic PRs](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+author%3Awingetbot+is%3Aclosed+Automatic+update). This package looks like it should've been caught by @wingetbot, but it didn't.

As for dropping hashes, there has been discussion in some issues regarding using other mechanisms to verify the integrity of a package, but that would classify as breaking changes and would likely be addressed in a 2.0 release of WinGet. Please see 
- https://github.com/microsoft/winget-cli/issues/714
