### ISSUE TITLE
[Package Issue]: Microsoft.Sysinternals.ProcessExplorer

### ISSUE THREAD

**Issue by jodakar1192** [microsoft/winget-pkgs#111454] opened 2023-07-06 10:02 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

I was able to install process explorer however I cannot run it with `process-explorer` as stated after the installation completes. I had to dig around to find its install location and finally figured out that even though the install directory is added to my path, there is only a single file by the name `procexp64.exe` in there.

### Steps to reproduce

Ran this in Powershell:
```
> winget install Microsoft.Sysinternals.ProcessExplorer
Found Process Explorer [Microsoft.Sysinternals.ProcessExplorer] Version 17.04
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://live.sysinternals.com/procexp64.exe
  ██████████████████████████████  2.28 MB / 2.28 MB
Successfully verified installer hash
Starting package install...
Path environment variable modified; restart your shell to use the new value.
Command line alias added: "process-explorer"
Successfully installed
```

### Actual behavior

Running `procexp64` works.

```
> process-explorer
process-explorer: The term 'process-explorer' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Expected behavior

Per the post install instructions, I should be able to run `process-explorer` to get it to run.

### Environment

```raw
Windows Package Manager v1.5.1572
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1848
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.1572.0
```

**Comment by krystofkrticka** [comment] 2023-07-06 11:26
You need to restart your shell to apply changes in environment variables as is said after installing the package: "Path environment variable modified; restart your shell to use the new value."

**Comment by jodakar1192** [comment] 2023-07-06 12:23
@krystofkrticka Yes I did that. As I mentioned, running `procexp64` works (after I restart the shell).

**Comment by krystofkrticka** [comment] 2023-07-06 12:26
That's weird because I just tested it using Windows Sandbox and for me `process-explorer` works just fine.

**Comment by krystofkrticka** [comment] 2023-07-06 12:27
It really looks like that refreshing environment variables got somehow stuck for you.

**Comment by jodakar1192** [comment] 2023-07-06 12:34
Where is the `process-explorer` shortcut/alias stored for you? I found [this doc](https://github.com/microsoft/winget-cli/blob/master/doc/specs/%23182%20-%20Support%20for%20installation%20of%20portable%20standalone%20apps.md) describing the implementation of the "portable installer" feature. It says:
> Once the portable application is copied to the appropriate install location based on the preferences of the user, a symlink will be created that points to the portable application. The locations where these symlinks will be stored are "%LOCALAPPDATA%/Microsoft/WinGet/Links/"

However, for me, although `%LOCALAPPDATA%/Microsoft/WinGet/Packages` contains the process explorer install, `%LOCALAPPDATA%/Microsoft/WinGet/Links` is empty. Not sure if that doc is outdated or something?

**Comment by krystofkrticka** [comment] 2023-07-06 12:44
Also sometimes you may need to restart your computer for environment variables to apply, because Windows is notorious for reboots almost everytime you change something.

**Comment by jodakar1192** [comment] 2023-07-06 12:46
Ok yeh. I uninstalled and then installed as admin this time and the symlink got created. Running `process-explorer` now works.

**Comment by jodakar1192** [comment] 2023-07-06 12:49
So I suppose we could either close this issue as "expected behavior" or maybe change it to be (as @Trenly stated) that the exe is not getting renamed. Additionally I feel it would be nice to add a note in the CLI that "symlink could not be created cuz not admin mode" for a better user experience.

**Comment by jodakar1192** [comment] 2023-07-06 12:50
Especially since it did say "command line alias added" which is actually incorrect.

**Comment by krystofkrticka** [comment] 2023-07-06 12:55
Yes, you can close it. I wasn't able to reproduce your issue because I automatically installed it as admin.

**Comment by Trenly** [comment] 2023-07-06 13:03
> r maybe change it to be (as @Trenly stated) that the exe is not getting renamed

This would probably be the preferred path

**Comment by stephengillie** [comment] 2023-07-06 16:51
Feature Request: When the symlink can't be created, display an error to the CLI.

**Comment by mdanish-kh** [comment] 2023-07-14 18:27
[Policy] Blocking-Issue

- Related to https://github.com/microsoft/winget-cli/issues/3437

**Comment by denelon** [comment] 2023-11-01 18:12
I'm going to go ahead and close this issue since we have the one in the comment above for the CLI.

**Closed by denelon** 2023-11-01 18:12 UTC
Labels: Issue-Bug, Issue-Feature, Blocking-Issue
