### ISSUE TITLE
[Package Request]: 

### ISSUE THREAD

**Issue by slavonnet** [microsoft/winget-pkgs#34722] opened 2021-11-12 11:15 UTC
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: 
Publisher Url: 
Package Name: 
Description:  Libvirt virt-viewer client for SPLICE+vnc protocol. Used when admiring oVirt. 
Package Version:  10.0
Installer URL:  https://virt-manager.org/download/sources/virt-viewer/virt-viewer-x64-10.0-1.0.msi

Current Package Identifier (for new versions): 

https://virt-manager.org/download/

**Comment by OfficialEsco** [comment] 2021-11-12 11:52
Package already exists.
https://github.com/microsoft/winget-pkgs/tree/master/manifests/r/RedHat/VirtViewer/10.0.256

And this is why we have this `[ ] I have performed a search and couldn't find this package.`

https://github.com/microsoft/winget-pkgs/search?q=VirtViewer&type=commits

```
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget search virt
Name                                                               Id                                            Version       Match
--------------------------------------------------------------------------------------------------------------------------------------------------------------
Virtual Magnifying Glass                                           VirtualMagnifyingGlass.VirtualMagnifyingGlass 3.6
VirtualGL-Utils                                                    VirtualGL.VirtualGL                           2.6.90
TurboVNC                                                           VirtualGL.TurboVNC                            2.2.6
VirtViewer                                                         RedHat.VirtViewer                             10.0.256
```
```
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget search virtviewer
Name       Id                Version
-------------------------------------
VirtViewer RedHat.VirtViewer 10.0.256
```

**Comment by slavonnet** [comment] 2021-11-12 12:15
I think some bugs in update logic.... I was update it today manual from file.


PS C:\Windows\System32>
PS C:\Windows\System32> winget upgrade
Имя         ИД                      Версия     Доступно   Источник
------------------------------------------------------------------
Python 3    Python.Python.3         3.9.7150.0 3.10.150.0 winget
LibreOffice LibreOffice.LibreOffice 7.2.1.2    7.2.2.2    winget
2 доступных обновлений.

where 2 updates  now

PS C:\Windows\System32> winget upgrade --all
Найдено Python 3 [Python.Python.3] Версия 3.10.150.0
Найдено  [Python.Python.3] Версия 3.10.150.0
Лицензия на это приложение предоставлена вам владельцем.
Корпорация Майкрософт не несет ответственность за сторонние пакеты и не предоставляет для них никакие лицензии.
Downloading https://www.python.org/ftp/python/3.10.0/python-3.10.0-amd64.exe
  ██████████████████████████████  27.0 MB / 27.0 MB
Хэш установщика успешно проверен
Запуск установки пакета...
Успешно установлено

where OpenOffice up[date? And Python update forever

**Comment by slavonnet** [comment] 2021-11-12 12:16
Anyone sorry for mistake. Can close

**Comment by OfficialEsco** [comment] 2021-11-12 12:32
These are 2 troubled packages
Check `A`dd or `R`emove `P`rograms if Python `3.9.7.7150` and `3.10.150.0` is installed, do the same for LibreOffice `7.2.1.2` and `7.2.2.2`

If Python 3.9 and 3.10 is installed then this is by design at the moment
If LibreOffice 7.2.2.2 is not installed do winget --info and check/post the log (`%LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir`), the issue might be that you've installed the Russian version of LibreOffice which is in a bit of a weird place atm (Currently issues with any non en-US LibreOffice versions)

**Comment by OfficialEsco** [comment] 2021-12-30 12:50
@slavonnet you have to close it.

**Comment by slavonnet** [comment] 2022-01-05 03:21
sorry

**Closed** 2022-01-05 03:21 UTC
Labels: Help-Wanted, Package-Request
