### ISSUE TITLE
[Update Request]: Dell Command | Update

### ISSUE THREAD

**Issue by Skeb1ns** [microsoft/winget-pkgs#138899] opened 2024-02-13 08:36 UTC
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Dell.CommandUpdate.Universal

### Package Version

5.2.0

### Please describe the changes you would like to see

There is a new version available (5.2.0). Download url: https://www.dell.com/support/home/en-us/drivers/DriversDetails?driverId=0XNVX

**Comment by mjr4077au** [comment] 2024-03-11 06:27
This is a duplicate of https://github.com/microsoft/winget-pkgs/issues/138899.

**Comment by inverlock** [comment] 2024-03-20 16:13
Hello,
There are actually two versions of this package that require an update.
![image](https://github.com/microsoft/winget-pkgs/assets/22609089/3cad64b7-2862-4bc9-b714-499f885944fb)

Both have been updated to 5.2.0 since January

Dell Command | Update Windows Universal Application:
 https://www.dell.com/support/home/en-us/drivers/DriversDetails?driverId=0XNVX

Dell Command | Update Application (Classic):
 https://www.dell.com/support/home/en-us/drivers/DriversDetails?driverId=4R78G

**Closed** 2024-03-27 15:39 UTC
Labels: In-PR, Package-Update
