### ISSUE TITLE
[Update Request]: scrcpy

### ISSUE THREAD

**Issue by 7wells** [microsoft/winget-pkgs#171430] opened 2024-09-03 14:47 UTC
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

scrcpy

### Package Version

2.6.1

### Please describe the changes you would like to see

There is a new version available. Download releases: https://github.com/Genymobile/scrcpy/releases/

**Comment by Dragon1573** [comment] 2024-09-03 15:18
- Duplicated #166969 
- Will be resolved by #165921

**Comment by stephengillie** [comment] 2024-09-03 15:57
Close with reason: Duplicate of #166969;

**Closed** 2024-09-03 15:57 UTC
Labels: Help-Wanted, Package-Update
