### ISSUE TITLE
[Package Request]: Files

### ISSUE THREAD

**Issue by Kaligula0** [microsoft/winget-pkgs#150390] opened 2024-04-22 00:24 UTC
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://files.community/download
Publisher: Files Community
Package Name: Files
Description: The ultimate, free, open-source file manager app for Windows
Package Version: 3.3
Installer URL: https://cdn.files.community/files/download/Files.Stable.exe (available also via MS Store)

Source code on GitHub https://github.com/files-community/Files

**Comment by Kaligula0** [comment] 2024-04-22 00:35
I wanted to cross-post to https://github.com/files-community/Files and found a closed issue https://github.com/files-community/Files/issues/8653 pointing to closed PR here https://github.com/microsoft/winget-pkgs/pull/146185

**Comment by Josh65-2201** [comment] 2024-04-22 01:22
I attempted this in #150392 it fails with no error given. Local install seem like it doesn't even try download the installer. immediately shows `exit code: 0x80070570 : The file or directory is corrupted and unreadable.`
```
https://cdn.files.community/files/stable/Files.Package_3.3.0.0_Stable_Test/Files.Package_3.3.0.0_x64_arm64_Stable.msixbundle
```

**Comment by BiosPlus** [comment] 2024-04-22 10:18
Given it's already on the MS Store, it can also be installed with `winget install 9nghp3dx8hdx`

![image](https://github.com/microsoft/winget-pkgs/assets/9003059/0fa5cb16-4bcd-463e-aa0d-738df961b6fc)

**Comment by Josh65-2201** [comment] 2024-04-22 13:31
Files on the store is paid where as there are the free options

**Comment by stephengillie** [comment] 2024-04-22 14:49
> I wanted to cross-post to https://github.com/files-community/Files and found a closed issue [files-community/Files#8653](https://github.com/files-community/Files/issues/8653) pointing to closed PR here #146185

This was closed because we couldn't find silent installer switches. Do you know how to install this without user interaction?

**Comment by vikingnope** [comment] 2024-04-22 14:51
@stephengillie, this is the only otherway: 
![image](https://github.com/microsoft/winget-pkgs/assets/81376423/9017b23b-e0ae-46c2-ac8a-51b0a2842a24)

**Comment by Kaligula0** [comment] 2024-04-22 14:53
> This was closed because we couldn't find silent installer switches. Do you know how to install this without user interaction?

No, I just learned about winget few days ago (and fell in love with), and found Files yesterday. So, naturally, I checked if Files are available via winget. I didn't find it, so posted here.

**Comment by vikingnope** [comment] 2024-04-22 14:55
It is not silent:

![image](https://github.com/microsoft/winget-pkgs/assets/81376423/f553d1b0-640c-4c58-898f-19e3dc59126b)


> The offline installers are msixbundles (The one I linked above) which should work silently, what the original one used was the user installer

**Comment by stephengillie** [comment] 2024-04-22 14:55
> It is not silent:
> 
> ![image](https://private-user-images.githubusercontent.com/81376423/324507755-f553d1b0-640c-4c58-898f-19e3dc59126b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTgwMDQsIm5iZiI6MTcxMzc5NzcwNCwicGF0aCI6Ii84MTM3NjQyMy8zMjQ1MDc3NTUtZjU1M2QxYjAtNjQwYy00YzU4LTg5OGYtMTllM2RjNTkxMjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE0NTUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YWI3MDEyODUxNmZkODg4YThjYjJiMjUwODIyNWFiODY0Y2Y0OGMzOTI4M2U1NmJjYTcxNGU4YjM3ODU3NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7gOEjhEcnZ8XLuRngJl816LY8ZzHvE3vq1pgMv90nYk)
> 
> > The offline installers are msixbundles (The one I linked above) which should work silently, what the original one used was the user installer

Correct - when an installer presents an "Install" or simiar button that needs to be clicked before proceeding, it counts as requiring user interaction. We're looking for an installer switch to avoid this.

**Comment by Josh65-2201** [comment] 2024-04-22 14:56
Is that shown when using Winget? Because that interface is just app installer the default open app for them.

**Comment by vikingnope** [comment] 2024-04-22 14:59
> Is that shown when using Winget? Because that interface is just app installer the default open app for them.

Winget does not support interactive installers (a.k.a installers where you need to press buttons), it only supports one's where everything can be done behind the curtains so to speak.

**Comment by Josh65-2201** [comment] 2024-04-22 15:00
Right now the issue I'm facing is trying to get it to install the dependencies.
```
https://cdn.files.community/files/stable/Files.Package_3.3.0.0_Stable_Test/Dependencies/x64/Microsoft.WindowsAppRuntime.1.5.msix
```

**Comment by Josh65-2201** [comment] 2024-04-22 15:02
> > Is that shown when using Winget? Because that interface is just app installer the default open app for them.
> 
> Winget does not support interactive installers (a.k.a installers where you need to press buttons), it only supports one's where everything can be done without any interactions from the user.

msixbundles should work silently if installed via command line. The interface your seeing is what shows when opening the file like a user. Did you also see it when trying to install from Winget using your manifest file?

**Comment by vikingnope** [comment] 2024-04-22 15:02
Do you know how to implement the command into a winget manifest?

**Comment by Josh65-2201** [comment] 2024-04-22 15:08
I would assume it would do itself when downloaded. Right now it reports failing at installing the dependency so it seem it did attempt it correctly but I can't be sure until I can figure out adding where to get the dependency from.

**Comment by vikingnope** [comment] 2024-04-22 15:17
Ah yes I see the issue, creating a pull request soon

**Comment by Josh65-2201** [comment] 2024-04-22 15:21
Currently have one open https://github.com/microsoft/winget-pkgs/pull/150392 if you know how to add the despondency

**Comment by vikingnope** [comment] 2024-04-22 16:20
@Josh65-2201, does the package have any other dependencies than the windows sdk?

**Comment by vikingnope** [comment] 2024-04-22 16:32
Hmm that's weird:

![image](https://github.com/microsoft/winget-pkgs/assets/81376423/3461218c-6e65-4a8e-a95b-56b3551cd01e)

**Comment by Josh65-2201** [comment] 2024-04-22 16:34
@yaira2 The only dependency of Files is WinAppSDK 1.5 right?

**Comment by Kaligula0** [comment] 2024-04-22 16:36
(Maybe it's connected with the problems I also have trying to upgrade WinAppSDK 1.5? Although I use WingetUI, but it shows an update available but cannot update it.)

**Comment by BiosPlus** [comment] 2024-04-23 08:41
If we crack open the [.appinstaller](https://cdn.files.community/files/stable/Files.Package.appinstaller) package on their site with something like notepad or vscode, we'll find this for dependancies 😉

```
<?xml version="1.0" encoding="utf-8"?>
<AppInstaller
	Uri="https://cdn.files.community/files/stable/Files.Package.appinstaller"
	Version="3.3.0.0" xmlns="http://schemas.microsoft.com/appx/appinstaller/2018">
	<MainBundle
		Name="Files"
		Version="3.3.0.0"
		Publisher="CN=Yair Aichenbaum, O=Yair Aichenbaum, L=Baltimore, S=Maryland, C=US"
		Uri="https://cdn.files.community/files/stable/Files.Package_3.3.0.0_Stable_Test/Files.Package_3.3.0.0_x64_arm64_Stable.msixbundle" />
	<Dependencies>
		<Package
			Name="Microsoft.VCLibs.140.00"
			Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"
			ProcessorArchitecture="arm64"
			Uri="https://cdn.files.community/files/stable/Files.Package_3.3.0.0_Stable_Test/Dependencies/ARM64/Microsoft.VCLibs.ARM64.14.00.appx"
			Version="14.0.30704.0" />
		<Package
			Name="Microsoft.VCLibs.140.00"
			Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"
			ProcessorArchitecture="x64"
			Uri="https://cdn.files.community/files/stable/Files.Package_3.3.0.0_Stable_Test/Dependencies/x64/Microsoft.VCLibs.x64.14.00.appx"
			Version="14.0.30704.0" />
		<Package
			Name="Microsoft.WindowsAppRuntime.1.5"
			Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"
			ProcessorArchitecture="x64"
			Uri="https://cdn.files.community/files/stable/Files.Package_3.3.0.0_Stable_Test/Dependencies/x64/Microsoft.WindowsAppRuntime.1.5.msix"
			Version="5001.70.1338.0" />
		<Package
			Name="Microsoft.WindowsAppRuntime.1.5"
			Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"
			ProcessorArchitecture="arm64"
			Uri="https://cdn.files.community/files/stable/Files.Package_3.3.0.0_Stable_Test/Dependencies/ARM64/Microsoft.WindowsAppRuntime.1.5.msix"
			Version="5001.70.1338.0" />
		<Package
			Name="Microsoft.VCLibs.140.00.UWPDesktop"
			Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"
			ProcessorArchitecture="arm64"
			Uri="https://cdn.files.community/files/stable/Files.Package_3.3.0.0_Stable_Test/Dependencies/ARM64/Microsoft.VCLibs.ARM64.14.00.Desktop.appx"
			Version="14.0.30704.0" />
		<Package
			Name="Microsoft.VCLibs.140.00.UWPDesktop"
			Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"
			ProcessorArchitecture="x64"
			Uri="https://cdn.files.community/files/stable/Files.Package_3.3.0.0_Stable_Test/Dependencies/x64/Microsoft.VCLibs.x64.14.00.Desktop.appx"
			Version="14.0.30704.0" />
	</Dependencies>
	<UpdateSettings>
		<OnLaunch
			HoursBetweenUpdateChecks="255" />
	</UpdateSettings>
</AppInstaller>
```

**Comment by vikingnope** [comment] 2024-04-23 09:41
Hi @BiosPlus, I cannot see any suggestions

**Comment by BiosPlus** [comment] 2024-04-23 09:59
Interesting @vikingnope, here they are for context.
Pretty much adding a dupe of the installer and making one arm64, and the other is adding a dependancy.

![image](https://github.com/microsoft/winget-pkgs/assets/9003059/dc4f8115-351c-43a9-bb80-07ff5f075b5e)

**Comment by vikingnope** [comment] 2024-04-23 10:01
So I added the dependency myself, I will add the arm installer when I manage to successfully get it working

**Comment by vikingnope** [comment] 2024-04-23 10:26
@BiosPlus, seems to have some other dependencies other than those 2:

![image](https://github.com/microsoft/winget-pkgs/assets/81376423/a6c33d73-44e2-460c-8628-3abd6db7949a)

**Comment by stephengillie** [comment] 2024-04-23 17:59
It appears that dependency `Microsoft.WindowsAppRuntime.1.5` doesn't completely install, and might be a nested installer mislabeled as a normal installer with an alias. https://github.com/microsoft/winget-pkgs/pull/150504#issuecomment-2073031989

**Comment by Josh65-2201** [comment] 2024-04-27 16:43
If Files ends up working on Winget there is also the preview version that can be added. The name should show as `Files - Preview`. Link for it is below
https://cdn.files.community/files/preview/Files.Package_3.3.5.0_Preview_Test/Files.Package_3.3.5.0_x64_arm64_Preview.msixbundle

**Comment by Josh65-2201** [comment] 2024-07-08 23:45
Hi, any updates on this?

**Comment by vikingnope** [comment] 2024-07-09 15:03
Sadly no

**Comment by Dragon1573** [comment] 2024-08-07 13:47
![image](https://github.com/user-attachments/assets/fe871895-c9f9-409a-8d1c-f1de9b0caeda)

There's a ["classic installer"](https://cdn.files.community/files/download/Files.Stable.exe) of the stable edition. Is it help?

**Comment by vikingnope** [comment] 2024-08-07 13:53
No it does not help since it is only an interactive installer.

**Closed** 2024-09-26 18:19 UTC
Labels: Blocking-Issue, Area-External, Interactive-Only-Installer, Package-Request

**Comment by RokeJulianLockhart** [comment] 2024-09-26 18:58
> https://github.com/microsoft/winget-pkgs/issues/150390#event-14420833064

Then don't close as completed!

**Comment by Josh65-2201** [comment] 2024-09-26 20:44
> This issue has been identified as requiring a fix from a third party

I don't believe so see https://github.com/microsoft/winget-pkgs/pull/150504#issuecomment-2273691802
