### ISSUE TITLE
[Update Request]: LyX

### ISSUE THREAD

**Issue by Edoardo66** [microsoft/winget-pkgs#145500] opened 2024-03-20 18:14 UTC
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

LyX.LyX

### Package Version

2.3.7

### Please describe the changes you would like to see

There is a new release available (2.3.7). Download page is: [https://www.lyx.org/Download](url)

**Comment by Trenly** [comment] 2024-08-07 17:20
Duplicate of #54476

**Closed** 2024-08-07 17:20 UTC
Labels: Help-Wanted, Package-Update
