### ISSUE TITLE
Tool generated binary manifest cause validation failure

### ISSUE THREAD

**Issue by ollieharker** [microsoft/winget-pkgs#411] opened 2020-05-20 08:23 UTC
After committing the manifest file as binary (blame Sourcetree!), the validation pipeline validation fails with the following error:

> Manifest is invalid. (Line: 3, Col: 1, Idx: 38) - (Line: 3, Col: 1, Idx: 38): While scanning a simple key, could not find expected ':'.

I fixed this by re-commiting the file as non-binary, and the manifest is validated successfully.

This may not be an issue, but I have noticed a lot of PRs are having this validation error and this information could help :)

**Comment by LukasNespor** [comment] 2020-05-20 11:33
I bumped to this issue too but in my case the issue was in file encoding. When I opened the file in vscode again it displayed wrong characters. Re-saving the content in UTF-8 helped.

**Comment by LukasNespor** [comment] 2020-05-20 12:10
It seems that core of the issue is ``YamlCreate.ps1`` script.

Repro steps:
1. Use YamlCreate.ps1
2. Generated yaml file is UTF-16 LE encoded
3. Commit and Push changes to GitHub - yaml file is "broken"

**Comment by ollieharker** [comment] 2020-05-20 12:17
@LukasNespor Yes, I was going to mention did you create it using the YamlCreate.ps1 script. I also used that tool to create my manifest, perhaps that is the issue?

**Comment by LukasNespor** [comment] 2020-05-20 12:30
> @LukasNespor Yes, I was going to mention did you create it using the YamlCreate.ps1 script. I also used that tool to create my manifest, perhaps that is the issue?

Yes, that is the issue. When the PowerShell script is generating the yaml file in UTF-8, everything works just fine. Just created PR #451

**Comment by maxmichels** [comment] 2020-05-20 13:36
This way you generate UTF8 with BOM. Also you have modified many more lines than needed. I have committed PR #462 to create the file with UTF8 without BOM

**Comment by VIKTORVAV99** [comment] 2020-05-21 10:41
It looks like the validation has been fixed. #605 passed validation with a binary file.

**Comment by denelon** [comment] 2021-01-06 17:09
This issue should be resolved now.

**Closed by denelon** 2021-01-06 17:09 UTC
Labels: Issue-Feature
