### ISSUE TITLE
[New Feature]: PR automation should validate new versions have same amount of installer types and architectures

### ISSUE THREAD

**Issue by o-l-a-v** [microsoft/winget-pkgs#199918] opened 2024-12-19 22:46 UTC
### Description of the new feature/enhancement

Azure CLI lost the portable ZIP x64 installer when it was updated from v2.65.0 to v2.66.0 in PR #190611.

That showed a test gap that should be pretty easy to add. As I wrote in comment <https://github.com/microsoft/winget-pkgs/pull/190611#issuecomment-2496178990> (slightly modified):

---

The portable ZIP was left out in this PR for v2.66.0. It's still included in the Azure CLI release:

* <https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.66.0>

And the WinGet manifest for v2.65.0 had ZIP x64:

* <https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/AzureCLI/2.65.0/Microsoft.AzureCLI.installer.yaml>

While it was left out for v2.66.0:

* <https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/AzureCLI/2.66.0/Microsoft.AzureCLI.installer.yaml>

Maybe the automation for reviewing PRs could get a test that checks new manifest version got at least as many installer types and architectures as the previous version? Here it'd be three:

* x64 MSI
* x64 ZIP
* x86 MSI

### Proposed technical implementation details (optional)

On version bump of a manifest, validate that the new version has at least as many installer types and archictectures as the previous version. If no add a warning to the PR, so the contributor and/or reviewer can validate that the missing option wasn't available.

**Comment by Trenly** [comment] 2024-12-20 15:05
* Duplicate of #92688

This has already been implemented, and can be seen in the PR you linked in the [comment from Wingetbot](https://github.com/microsoft/winget-pkgs/pull/190611#issuecomment-2487114082)
```
=== manifests\m\Microsoft\AzureCLI\2.66.0 ===
Missing Properties value based on version 2.65.0:
Installers
```

@stephengillie - does your automation need to exclude PRs with https://github.com/microsoft/winget-pkgs/labels/Manifest-Metadata-Consistency ?

**Closed** 2024-12-20 15:05 UTC
Labels: Issue-Feature

**Comment by stephengillie** [comment] 2024-12-20 18:57
`-label:Manifest-Metadata-Consistency+` has been added to my Approval query.
