### ISSUE TITLE
[Update Request]: Genymobile.scrcpy

### ISSUE THREAD

**Issue by welpdx** [microsoft/winget-pkgs#192018] opened 2024-11-16 22:21 UTC
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Genymobile.scrcpy 

### Package Version

2.7

### Please describe the changes you would like to see

There is a new release (2.7) available.
Download Page Url: https://github.com/Genymobile/scrcpy/releases/

Updating to this url should keep the repo always up to date. https://github.com/microsoft/winget-cli/discussions/863

**Comment by Dragon1573** [comment] 2024-11-17 05:20
> [!NOTE]
>
> It's currently in progress.
>
> - See #173679.

**Comment by welpdx** [comment] 2024-11-18 00:17
Thanks @Dragon1573

**Comment by stephengillie** [comment] 2024-11-18 17:45
Close with reason: Duplicate of #173679;

**Closed** 2024-11-18 17:45 UTC
Labels: Blocking-Issue, Help-Wanted, zip-binary, Package-Update
