### ISSUE TITLE
[New Feature]: Support android apk files (windows subsystem for anroid, wsa)

### ISSUE THREAD

**Issue by oxygen-dioxide** [microsoft/winget-pkgs#35340] opened 2021-11-19 08:37 UTC
### Description of the new feature/enhancement

support android apk as an installer type

### Proposed technical implementation details (optional)

Take AmazeFileExplorer as an example
```
PackageIdentifier: TeamAmaze.AmazeFileManager
PackageVersion: 3.6.7
PackageLocale: en-US
Publisher: TeamAmaze
PackageName: com.amaze.filemanager
License: GPL3
ShortDescription: Simple and attractive Material Design file manager for Android
Installers: 
 - Architecture: arm64
   InstallerType: apk
   InstallerUrl: https://github.com/TeamAmaze/AmazeFileManager/releases/download/v3.6.7/app-fdroid-release.apk
   InstallerSha256: ac25eed953aa2d1fdce3d92e8abe4ded6e89741ec5e43dc3eab102c0c7a1cbe9
ManifestType: singleton
ManifestVersion: 1.0.0
```

**Comment by OfficialEsco** [comment] 2021-11-19 10:55
This should probably be moved to https://github.com/microsoft/winget-cli/issues

**Comment by jedieaston** [comment] 2021-11-19 13:59
In which case it's a duplicate of https://github.com/microsoft/winget-cli/issues/1625

**Comment by jedieaston** [comment] 2021-11-19 14:00
Duplicate of https://github.com/microsoft/winget-cli/issues/1625

**Comment by denelon** [comment] 2021-11-19 22:24
Duplicate of microsoft/winget-cli#1625

**Closed** 2021-11-19 22:24 UTC
Labels: Issue-Feature, Blocking-Issue
