### ISSUE TITLE
Publishing is down :(

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-pkgs#70728] opened 2022-08-18 12:30 UTC
It looks like publishing has been failing since last night at about 7:30 PM PST: https://dev.azure.com/ms/winget-pkgs/_build?definitionId=338&_a=summary

It fails during commit validation, saying "Index is not consistent" (I'm guessing it's failing to write at some point in the process and the error just bubbles up at the end, but I don't really know how it works, so that's extremely uneducated).

**Comment by denelon** [comment] 2022-08-18 23:07
We've paused the publish pipeline while we're working on the issue. As soon as we have a meaningful update, we'll post the details here. We've narrowed the issue down to a subset of PRs that were merged in based on the time of the failure. Until we have more details, we won't know whether it was a specific PR or another systemic failure unrelated to a PR.

**Comment by denelon** [comment] 2022-08-19 21:43
We've isolated the issue. 

It's related to the Python package. We have some version range overlap across architectures.
for example, python 3.4.3 has displayversion (3.4.3000 - 3.4.15678) depending on the architecturepython 3.4.4 has displayversion (3.4.4000 - 3.4.16789).

This was discovered when the packages were split into minor versions.

If we split that package into x86 and x64 the range overlap goes away.

**Comment by denelon** [comment] 2022-08-20 03:56
The manifests were modified to allow publishing to resume. The root cause is known. We will start working towards a permanent solution for this scenario.

**Closed by denelon** 2022-08-20 03:56 UTC
Labels: Issue-Bug

**Comment by vedantmgoyal2009** [comment] 2022-08-21 03:23
@denelon you forgot to unpin the issue.

**Comment by mdanish-kh** [comment] 2022-08-21 06:50
Also, the pipeline needs to be re-run on the packages submitted before it was paused. 
![image](https://user-images.githubusercontent.com/88161975/185779283-f28b96cd-2734-4dd3-8c3b-d3329cdedbb9.png)

**Comment by denelon** [comment] 2022-08-22 14:39
We kept the issue pinned because this could still happen again until we create a permanent fix. As far as previous PRs, we will likely run a rebuild to ensure consistency.

**Comment by vedantmgoyal2009** [comment] 2022-08-23 03:28
@denelon does the publish pipeline rebuild the whole index from scratch or only changed manifests?

**Comment by denelon** [comment] 2022-08-23 14:14
The default mode is just the changes. We can also perform a "full" rebuild when necessary.

**Comment by jedieaston** [comment] 2022-08-29 11:42
The pipeline has been failing since Saturday due to the sheer amount of traffic. Commit processing is taking too long:

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/21368066/187193397-6b6fffae-09de-41e5-b1f3-9a9f5ed80b3a.png">

**Comment by denelon** [comment] 2022-08-29 14:36
It looks like we had a version overlap, and now publishing is hitting an upstream hard limit. As soon as the engineering team gets in, we'll take a look and run a rebuild.
