### ISSUE TITLE
[Package Issue]: Duplicate package

### ISSUE THREAD

**Issue by CanePlayz** [microsoft/winget-pkgs#174102] opened 2024-09-18 12:45 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Currently, UnigetUI is being tracked in two different places:

- https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/MartiCliment/UniGetUI
- https://github.com/microsoft/winget-pkgs/tree/master/manifests/s/SomePythonThings/WingetUIStore

The program was recently renamed from WingetUI to UnigetUI. I think the second location is the right one because there are all of the author's other packages. However, they don't go by the name "SomePythonThings" anymore, so all of the packages there should be moved to the other location. Additionally, the "WingetUIStore" version in the second location would need to be renamed to reflect the new name.

### Steps to reproduce

.

### Actual behavior

.

### Expected behavior

.

### Environment

```raw
.
```

**Comment by Dragon1573** [comment] 2024-09-18 13:21
@vikingnope and @marticliment is currently working on this.

- See #173379 
  - Removal pull requests
    - #173815
    - #173817
    - #173793
    - #173804
  - Appending pull requests
    - #173838
    - #173839
    - #173840
    - #173841
    - #173842
    - #173843
    - #173844

This should be closed with reason: Duplicate issue.

**Comment by stephengillie** [comment] 2024-09-18 14:16
https://github.com/microsoft/winget-pkgs/issues/173379#issuecomment-2354095012

Duplicate of #173379

**Closed** 2024-09-18 14:16 UTC
Labels: Issue-Bug

**Comment by CanePlayz** [comment] 2024-09-18 15:46
Ah, thanks. Sorry, I will make sure to check existing issues and PRs more thoroughly the next time.
