### ISSUE TITLE
Duplicate Packages

### ISSUE THREAD

**Issue by kjacobsen** [microsoft/winget-pkgs#908] opened 2020-05-24 02:17 UTC
Hi,

Seems putty has been two separate package manifests.

https://github.com/microsoft/winget-pkgs/blob/master/manifests/Putty/Putty/0.73.yaml

and 

https://github.com/microsoft/winget-pkgs/blob/master/manifests/SimonTatham/Putty/0.73.yaml

**Comment by jerrythiesen** [comment] 2020-05-24 18:07
Confirmed:

![image](https://user-images.githubusercontent.com/36054829/82761240-48950580-9dc7-11ea-9934-f53b5b396df1.png)

The default flow should be:
1. Package Creator checks Package Directory for package.
2. If it does not exist, generate a YAML file.
3. Submit PR for new Package.
4. During PR Review, a second review should be performed to ensure that there is not a duplicate package, as in this case.
5. **IF** a duplicate package is being submitted for a PR, it should be rejected, with a reason why the package was rejected.

**Comment by Croydon** [comment] 2020-05-28 23:24
> During PR Review, a second review should be performed to ensure that there is not a duplicate package, as in this case.

This step could be half-automated. The build bot could check the name against existing manifests and if there are similar matches it could post a comment in the PR `Potential duplicate of: [name](URL to manifest)`

**Comment by takekazuomi** [comment] 2020-06-06 08:24
There are several gnu win32 make. Once approved, the package should not disappear. For reproducibility. It looks like there are already duplicate packages.
I think we need something like a package alias.
https://github.com/microsoft/winget-pkgs/blob/master/manifests/GnuWin32/Make/3.81.yaml
https://github.com/microsoft/winget-pkgs/blob/master/manifests/GnuWin32/MakeforWindows/3.81.yaml

**Comment by denelon** [comment] 2020-08-26 16:15
We can check for a duplicate with the SHA256. The package alias may also be necessary to prevent someone from losing the ability to install a package that had an approved manifest.

**Comment by kjacobsen** [comment] 2021-01-14 01:24
Happy to close this as the duplicated packages reported have been removed.

@denelon did you want to look at a pipeline improvement still?

**Comment by Croydon** [comment] 2021-01-21 04:02
Hi! This is my generic reply for every issue which is still relevant and is on the edge of getting closed by a stale bot.

**Comment by denelon** [comment] 2021-02-03 22:04
The message from the bot wasn't correct. The issue will not be auto closed unless it has the "Needs-author-feedback" and hasn't had any activity for 7 days after the "Status: no recent activity" label has been added. This will not be auto closed based on the current bot rules.

**Comment by vedantmgoyal2009** [comment] 2021-09-11 16:43
@denelon I think this has already been implemented and bot checks for duplicate hashes. It can be closed(?)

**Closed** 2021-09-13 18:02 UTC
Labels: Area-Validation-Pipepline, Issue-Feature
