### ISSUE TITLE
[New Version Available]: K-Lite Codec Pack Standard

### ISSUE THREAD

**Issue by Hellements** [microsoft/winget-pkgs#60870] opened 2022-05-15 22:01 UTC
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: 
Publisher Url: https://www.codecguide.com
Package Name: 
Description: 
Package Version: 17.0.0
Installer URL: https://files3.codecguide.com/K-Lite_Codec_Pack_1700_Standard.exe

Current Package Identifier (for new versions):

**Comment by OfficialEsco** [comment] 2022-05-20 08:22
* Resolved in #61123

**Comment by OfficialEsco** [comment] 2022-05-23 16:47
Duplicate of #61123

**Closed by OfficialEsco** 2022-05-23 16:47 UTC
Labels: Help-Wanted, Package-Request
