### ISSUE TITLE
[New Feature]: Add check to Action for presence of `DisplayVersion` in `AppsAndFeaturesEntries` in previous versions

### ISSUE THREAD

**Issue by rakleed** [microsoft/winget-pkgs#173333] opened 2024-09-14 11:04 UTC
### Description of the new feature/enhancement

Now, if there was no `DisplayVersion` in `AppsAndFeaturesEntries` before, and you add it in a new version, then only with manual validation @stephengillie https://github.com/microsoft/winget-pkgs/pull/172303#issuecomment-2338645094 it will say that you need to add it for all previous versions or remove it from the new version. I would like it to be checked automatically when running Actions, so that it can be fixed faster.

**Comment by mdanish-kh** [comment] 2024-09-14 12:16
Duplicate of #138520

**Closed** 2024-09-14 12:16 UTC
Labels: Issue-Feature
