### ISSUE TITLE
[Package Issue]: Helm.Helm

### ISSUE THREAD

**Issue by EricDeng1001** [microsoft/winget-pkgs#108058] opened 2023-05-25 00:56 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Helm Path Env is not setup correctly after install.

### Steps to reproduce

step 1.
`winget install --id Helm.Helm`

step2.
open a new terminal.
run`helm`
shows: not a cmdlet

step 3.
open env settings in windows, shows:
![image](https://github.com/microsoft/winget-pkgs/assets/28720903/fec98de0-456a-4968-b45c-6a37677921ad)
C:\Users\ganti\AppData\Local\Microsoft\WinGet\Packages\Helm.Helm_Microsoft.Winget.Source_8wekyb3d8bbwe

step4.
check folder C:\Users\ganti\AppData\Local\Microsoft\WinGet\Packages\Helm.Helm_Microsoft.Winget.Source_8wekyb3d8bbwe
shows:
![image](https://github.com/microsoft/winget-pkgs/assets/28720903/70fe9dda-a158-4b7f-b34b-06a13c0550cd)

### Actual behavior

ENV PATH is not set correctly 

### Expected behavior

PATH should be set to

C:\Users\ganti\AppData\Local\Microsoft\WinGet\Packages\Helm.Helm_Microsoft.Winget.Source_8wekyb3d8bbwe\windows-amd64

or

### Environment

```raw
Windows 程序包管理器 v1.4.10173
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.22621.1702
系统体系结构: X64
软件包: Microsoft.DesktopAppInstaller v1.19.10173.0

日志: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

用户设置: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

链接
----------------------------------------------------------------------------
隐私声明             https://aka.ms/winget-privacy
许可协议             https://aka.ms/winget-license
第三方声明           https://aka.ms/winget-3rdPartyNotice
主页                 https://aka.ms/winget
Windows 应用商店条款 https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by mdanish-kh** [comment] 2023-05-25 01:03
Duplicate of #96973;

This was a known CLI bug that was fixed in a preview release of WinGet.

You can upgrade to the latest preview version of WinGet by installing the msix from [aka.ms/getwingetpreview](https://aka.ms/getwingetpreview)

**Closed by mdanish-kh** 2023-05-25 01:03 UTC
Labels: Issue-Bug, Needs-Triage
