### ISSUE TITLE
[Package Issue]: Mega.MEGAsync & Almico.SpeedFan unknown versions

### ISSUE THREAD

**Issue by pwnorbitals** [microsoft/winget-pkgs#133840] opened 2024-01-12 16:56 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Version reported as "Unknown", even with the latest versions are installed

### Steps to reproduce

Not sure, has always been the case on my system

### Actual behavior

```
PS C:\Users\decla> winget upgrade --all --include-unknown
Nom                    ID                          Version  Disponible Source
-----------------------------------------------------------------------------
MEGAsync               Mega.MEGASync               Unknown  4.11.0.0   winget
SpeedFan (remove only) Almico.SpeedFan             Unknown  4.52       winget
Epic Games Launcher    EpicGames.EpicGamesLauncher 1.3.82.0 1.3.93.0   winget
5 mises à niveau disponibles.

Les packages suivants ont une mise à niveau disponible, mais nécessitent un ciblage explicite pour la mise à niveau :
Nom             ID              Version     Disponible           Source
-----------------------------------------------------------------------
Discord         Discord.Discord 1.0.9012    1.0.9025             winget
Microsoft Teams Microsoft.Teams 1.6.00.6754 23320.3027.2591.1505 winget

Installation des dépendances
(1/2) Trouvé MEGAsync [Mega.MEGASync] Version 4.11.0.0
La licence d’utilisation de cette application vous est octroyée par son propriétaire.
Microsoft n’est pas responsable des paquets tiers et n’accorde pas de licences à ceux-ci.
Téléchargement en cours https://mega.nz/MEGAsyncSetup64.exe
  ██████████████████████████████  52.0 MB / 52.0 MB
Le code de hachage de l’installation a été vérifié avec succès
Démarrage du package d’installation... Merci de patienter.
Installé correctement
```

### Expected behavior

The correct version should be shown

### Environment

```raw
PS C:\Users\decla> winget --info
Gestionnaire de package Windows v1.6.3482
Copyright (c) Microsoft Corporation. Tous droits réservés.

Windows: Windows.Desktop v10.0.22000.2538
Architecture du système : X64
Package : Microsoft.DesktopAppInstaller v1.21.3482.0

Répertoires Winget
-------------------------------------------------------------------------------------------------------------------
Journaux                                     %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\L…
Paramètres utilisateurs                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\L…
Répertoire des liens portables (utilisateur) %LOCALAPPDATA%\Microsoft\WinGet\Links
Répertoire des liens portables (ordinateur)  C:\Program Files\WinGet\Links
Racine de package portable (utilisateur)     %LOCALAPPDATA%\Microsoft\WinGet\Packages
Racine du package portable                   C:\Program Files\WinGet\Packages
Racine de package portable (x86)             C:\Program Files (x86)\WinGet\Packages
Téléchargements du programme d’installation  E:\Downloads

Liens
---------------------------------------------------------------------------------------------
Déclaration de confidentialité        https://aka.ms/winget-privacy
Contrat de licence                    https://aka.ms/winget-license
Avis de tiers                         https://aka.ms/winget-3rdPartyNotice
Page d’accueil                        https://aka.ms/winget
Conditions générales du Windows Store https://www.microsoft.com/en-us/storedocs/terms-of-sale

Paramètre administrateur                  État
---------------------------------------------------
LocalManifestFiles                        Désactivé
BypassCertificatePinningForMicrosoftStore Désactivé
InstallerHashOverride                     Désactivé
LocalArchiveMalwareScanOverride           Désactivé
```
```


### Screenshots and Logs

[WinGet-2024-01-12-17-47-16.454.log](https://github.com/microsoft/winget-pkgs/files/13921809/WinGet-2024-01-12-17-47-16.454.log)
[WinGet-2024-01-12-17-47-05.288.log](https://github.com/microsoft/winget-pkgs/files/13921810/WinGet-2024-01-12-17-47-05.288.log)
[WinGet-2024-01-12-17-44-35.180.log](https://github.com/microsoft/winget-pkgs/files/13921811/WinGet-2024-01-12-17-44-35.180.log)
[WinGet-2024-01-12-17-44-03.575.log](https://github.com/microsoft/winget-pkgs/files/13921812/WinGet-2024-01-12-17-44-03.575.log)
[WinGet-2024-01-12-17-43-39.359.log](https://github.com/microsoft/winget-pkgs/files/13921813/WinGet-2024-01-12-17-43-39.359.log)
[WinGet-2024-01-12-17-43-31.778.log](https://github.com/microsoft/winget-pkgs/files/13921814/WinGet-2024-01-12-17-43-31.778.log)
[WinGet-2024-01-12-17-43-12.153.log](https://github.com/microsoft/winget-pkgs/files/13921815/WinGet-2024-01-12-17-43-12.153.log)
[WinGet-2024-01-12-17-43-07.704.log](https://github.com/microsoft/winget-pkgs/files/13921816/WinGet-2024-01-12-17-43-07.704.log)
[WinGet-2024-01-12-17-42-55.501.log](https://github.com/microsoft/winget-pkgs/files/13921817/WinGet-2024-01-12-17-42-55.501.log)
[WinGet-2024-01-12-17-41-21.117.log](https://github.com/microsoft/winget-pkgs/files/13921818/WinGet-2024-01-12-17-41-21.117.log)
[WinGet-2024-01-12-17-40-02.991.log](https://github.com/microsoft/winget-pkgs/files/13921820/WinGet-2024-01-12-17-40-02.991.log)
[WinGet-2024-01-12-17-36-37.195.log](https://github.com/microsoft/winget-pkgs/files/13921821/WinGet-2024-01-12-17-36-37.195.log)
[WinGet-2024-01-12-17-24-10.971.log](https://github.com/microsoft/winget-pkgs/files/13921822/WinGet-2024-01-12-17-24-10.971.log)
[WinGet-2024-01-12-17-24-02.200.log](https://github.com/microsoft/winget-pkgs/files/13921823/WinGet-2024-01-12-17-24-02.200.log)
[WinGet-2024-01-12-17-55-18.797.log](https://github.com/microsoft/winget-pkgs/files/13921824/WinGet-2024-01-12-17-55-18.797.log)
[WinGet-2024-01-12-17-54-46.931.log](https://github.com/microsoft/winget-pkgs/files/13921825/WinGet-2024-01-12-17-54-46.931.log)
[WinGet-2024-01-12-17-50-40.505.log](https://github.com/microsoft/winget-pkgs/files/13921826/WinGet-2024-01-12-17-50-40.505.log)
[WinGet-2024-01-12-17-50-37.267.log](https://github.com/microsoft/winget-pkgs/files/13921827/WinGet-2024-01-12-17-50-37.267.log)

**Comment by pwnorbitals** [comment] 2024-01-12 16:59
Looks related to https://github.com/microsoft/winget-pkgs/issues/15946

**Comment by Trenly** [comment] 2024-01-12 19:43
Duplicate of #15946; 

These issues are caused because the installer for the application doesn't write a version to the registry. This can only be fixed by the creators of the installers

[Policy] Installer-Issue

**Closed** 2024-01-12 19:43 UTC
Labels: Issue-Bug, Area-External, Needs-Triage, Installer-Issue
