### ISSUE TITLE
[Package Issue]: niconico.nair.live

### ISSUE THREAD

**Issue by teruteru128** [microsoft/winget-pkgs#190695] opened 2024-11-12 07:51 UTC
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The upgrade is broken because an old manifest called "latest" is still present.
Therefore, delete this old manifest.

### Steps to reproduce

```ps1
winget upgrade --id niconico.nair.live
```

### Actual behavior

```log
見つかりました N-Air [niconico.nair.live] バージョン latest
このアプリケーションは所有者からライセンス供与されます。
Microsoft はサードパーティのパッケージに対して責任を負わず、ライセンスも付与しません。
ダウンロード中 https://n-air-app.nicovideo.jp/download/windows
  ██████████████████████████████   457 MB /  457 MB
インストーラーのハッシュが一致しません; これは、管理者として実行している場合は上書きできません
```

### Expected behavior

```log
見つかりました N-Air [niconico.nair.live] バージョン 1.1.20241016-2
このアプリケーションは所有者からライセンス供与されます。
Microsoft はサードパーティのパッケージに対して責任を負わず、ライセンスも付与しません。
ダウンロード中 https://n-air-app.nicovideo.jp/download/windows
  ██████████████████████████████   457 MB /  457 MB
インストーラーハッシュが正常に検証されました
パッケージのインストールを開始しています...
インストールが完了しました
```

### Environment

```raw
v1.9.25180 の Windows パッケージ マネージャー
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.5073
システム アーキテクチャ: X64
パッケージ: Microsoft.DesktopAppInstaller v1.24.25180.0
```

**Comment by stephengillie** [comment] 2024-11-12 16:49
It appears that another user saw the same problem and solution: https://github.com/microsoft/winget-pkgs/pull/190696
- Since the PR is merged, I'll assume that the Issue is complete. If this is in error, please @ me and I'll reopen.

This package uses a vanity URL, and I'm guessing that the `latest` manifest was sorted above other versions. So all manifest versions would have had the same `InstallerUrl`, but with different hashes. So the package manager was likely trying to match the most recent package version with the `latest` manifest, causing the hash mismatch.

**Closed by stephengillie** 2024-11-12 16:49 UTC
Labels: Issue-Bug, Help-Wanted, Package-Update

**Comment by teruteru128** [comment] 2024-11-13 12:40
@stephengillie 
I created both the pull request and the issue.
Thank you for your response.
