### ISSUE TITLE
[Package Request]: WinCDEmu

### ISSUE THREAD

**Issue by anderlli0053** [microsoft/winget-pkgs#155323] opened 2024-05-27 18:30 UTC
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

_Download Page Url:_ `https://wincdemu.sysprogs.org/download/`  **or**  `https://github.com/sysprogs/WinCDEmu/releases`
_Publisher:_ `Sysprogs`
_Package Name:_ `WinCDEmu`
_Description:_ `WinCDEmu is an open-source CD/DVD/BD emulator - a tool that allows you to mount optical disc images by simply clicking on them in Windows Explorer. If you have downloaded an ISO image and want to use it without burning it to a blank disc, WinCDEmu is the easiest way to do it.`
_Package Version:_ `4.1`
_Installer URL:_ `https://github.com/sysprogs/WinCDEmu/releases/download/v4.1/WinCDEmu-4.1.exe`
_Official repository:_ `https://github.com/sysprogs/WinCDEmu/`

**Comment by Dragon1573** [comment] 2024-05-29 04:14
> [!CAUTION]
>
> This package requires an authentication of installing drivers. Unless users explicitly allow all unsigned (or untrusted) drivers to be installed silently, a dialog will always prompt out and asking users approval.
>
> ![image](https://github.com/microsoft/winget-pkgs/assets/49941141/44738380-8455-4733-925b-b3213c9c4650)

@anderlli0053 - Sorry, this package is currently not supported by `winget.exe`.

@stephengillie - Could you please mark this as a blocking issue?

**Comment by anderlli0053** [comment] 2024-05-29 09:44
> > [!CAUTION]
> >
> > This package requires an authentication of installing drivers. Unless users explicitly allow all unsigned (or untrusted) drivers to be installed silently, a dialog will always prompt out and asking users approval.
> >
> > ![image](https://github.com/microsoft/winget-pkgs/assets/49941141/44738380-8455-4733-925b-b3213c9c4650)
> 
> @anderlli0053 - Sorry, this package is currently not supported by `winget.exe`.
> 
> @stephengillie - Could you please mark this as a blocking issue?



Ok, thanks for the info... I guess that possible in the future this would get somehow included amongst packages, as the winget evolves.... 

Should the issue be closed now?

**Comment by Dragon1573** [comment] 2024-05-29 13:44
Yes, the cause of blocking this issue can't be solved easily so you can close it now.

Willing to help if "silent driver installation" feature is available.

**Closed** 2024-05-29 17:30 UTC
Labels: Help-Wanted, Package-Request, DriverInstall
