### ISSUE TITLE
[Package Issue]: Libretro.RetroArch

### ISSUE THREAD

**Issue by cobalt2727** [microsoft/winget-pkgs#92643] opened 2022-12-31 02:18 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Trying to upgrade RetroArch from winget always defaults to installing in `C:\RetroArch-Win64`. I'd like for the winget package to determine the location of the **current** RetroArch version before installing a newer version - as is, it just installs a newer version and ignores the existing setup.

### Steps to reproduce

`winget upgrade --all` after installing RetroArch somewhere else manually, with the official installer

### Actual behavior

see above

### Expected behavior

also see above

### Environment

```shell
Windows Package Manager v1.3.2691                                                                                       Copyright (c) Microsoft Corporation. All rights reserved.                                                                                                                                                                                       Windows: Windows.Desktop v10.0.19045.2364                                                                               System Architecture: X64                                                                                                Package: Microsoft.DesktopAppInstaller v1.18.2691.0                                                                                                                                                                                             Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir                                                                                                                                              Links                                                                                                                   ---------------------------------------------------------------------------                                             Privacy Statement   https://aka.ms/winget-privacy                                                                       License Agreement   https://aka.ms/winget-license                                                                       Third Party Notices https://aka.ms/winget-3rdPartyNotice                                                                Homepage            https://aka.ms/winget                                                                               Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment] 2022-12-31 03:45
* See https://github.com/microsoft/winget-cli/issues/1002
* See https://github.com/microsoft/winget-cli/issues/1570

* Duplicate of https://github.com/microsoft/winget-cli/issues/2207

**Closed** 2023-01-06 23:31 UTC
Labels: Issue-Bug
