### ISSUE TITLE
[Package Request]: Carnac key press logger

### ISSUE THREAD

**Issue by github-account1111** [microsoft/winget-pkgs#66525] opened 2022-07-16 15:37 UTC
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Code52
Publisher Url: http://carnackeys.com/
Package Name: Carnac the Magnificent Keyboard Utility
Description: Mouseposé alternative for Windows. Displays keystrokes.
Package Version: 2.3.13
Installer URL: https://github.com/Code52/carnac/releases/download/2.3.13/Setup.exe

Current Package Identifier (for new versions):

**Comment by OfficialEsco** [comment] 2022-07-22 19:42
Duplicate of #23692

**Closed** 2022-07-22 19:42 UTC
Labels: Help-Wanted, Package-Request
