### ISSUE TITLE
Publishing is Down

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-pkgs#86160] opened 2022-10-24 12:36 UTC
Any new commits after #85905 (commit [939285a](https://github.com/microsoft/winget-pkgs/commit/939285af88cebbe003e79dafc4e7301f419353c3)) have not been published. 

The publish pipeline is succeeding, but the package cached at https://cdn.winget.microsoft.com/cache/source.msix is not being updated

**Comment by denelon** [comment] 2022-10-24 18:03
We've purged the CDN and downloaded the latest index. We're looking at testing for this condition, so it doesn't happen again.

**Comment by Trenly** [comment] 2022-10-28 13:29
> Is this still an issue? my package updated the version number but not the hash

Yes. The CDN still seems to be outdated quite frequently

**Comment by denelon** [comment] 2022-10-28 15:04
We've contacted our CDN provider to help determine the root cause. We're also looking into better alerting so we can force the cache to flush and reload.

**Comment by albertosantini** [comment] 2022-10-31 17:50
Any update? Thanks.

**Comment by Trenly** [comment] 2022-10-31 17:54
> Any update? Thanks.

It looks like the cached source is now being updated, but not as regularly as it should be. The latest source available from the CDN was built at 2022.1031.233, which would be 02:33 UTC (I believe). The latest source available should be 2022.1031.1742. So, still issues going on with the CDN

**Comment by denelon** [comment] 2022-10-31 18:56
We've found a bug, and we're going to update shortly.

**Comment by dfoulkes** [comment] 2022-11-04 22:13
Any update? 

Still seeing unable to pull any package via the winget CDN

**Comment by dfoulkes** [comment] 2022-11-04 22:16
```
Updating all sources...
Updating source: msstore...
Done
Updating source: winget...
Cancelled
````

**Comment by albertosantini** [comment] 2022-11-05 19:36
Sigh... now there is also https://github.com/microsoft/winget-cli/issues/2666

**Comment by denelon** [comment] 2022-11-14 19:25
@Trenly I think we're back up and running normally, but I'll let you decide when to close this issue. 

FYI: We're holding off on a full purge with each publish, but we've added that capability behind a feature toggle in the production environment. It makes publish take longer and may introduce new other unintended consequences.

**Comment by Trenly** [comment] 2022-11-14 19:28
> @Trenly I think we're back up and running normally, but I'll let you decide when to close this issue.
> 
> FYI: We're holding off on a full purge with each publish, but we've added that capability behind a feature toggle in the production environment. It makes publish take longer and may introduce new other unintended consequences.

Sounds great - Thank you for the update! I think I'll give it a few days to verify stability. I think we can use this issue for primary tracking and resolve the ones over at cli?

**Comment by Trenly** [comment] 2022-11-18 13:14
Having neither heard or seen any further issues with this, I'm confident that it has been fully resolved.

**Comment by aescanes** [comment] 2022-11-18 17:35
Hi there.
Unfortunately, it seems that it has not yet been resolved.
![Sin título](https://user-images.githubusercontent.com/75578414/202766683-97e10019-82ee-4a24-aab2-5fb468bf6e1c.png)

**Comment by denelon** [comment] 2022-11-22 16:44
Just as a FYI, we've still gotten a few reports. We've resorted to purging the CDN cache each time we publish to reduce the likelihood of getting the zero-byte file.

**Comment by dafunks** [comment] 2022-11-23 12:52
This has returned for me. 
Like before I used "winget source reset --force" and "winget source update --name winget" but not working. This is getting very annoying.

**Comment by mivsvit** [comment] 2022-11-23 13:52
> Just as a FYI, we've still gotten a few reports. We've resorted to purging the CDN cache each time we publish to reduce the likelihood of getting the zero-byte file.

New reports today of 0 byte files:
https://github.com/microsoft/winget-cli/issues/1656#issuecomment-1324799205

**Comment by midnightmercenary** [comment] 2022-11-23 13:53
Broken for me also.

```
PS C:\Users\ANON> winget source update winget
Updating source: winget...
Cancelled
PS C:\Users\ANON> winget source reset --force
Resetting all sources...Done
PS C:\Users\ANON> winget source update --name winget
Updating source: winget...
Cancelled
```

**Comment by SquareQuiz** [comment] 2022-11-23 14:39
Reporting from Belgrade, Serbia:

C:\Windows\System32>winget source list
Name    Argument
-----------------------------------------------------
winget  https://cdn.winget.microsoft.com/cache

C:\Windows\System32>winget source reset --force
Resetting all sources...Done

C:\Windows\System32>winget source update --name winget
Updating source: winget...
Cancelled

It seems that a CDN network is potential source of this problem. Cache file is blank.

**Comment by SquareQuiz** [comment] 2022-11-23 14:50
Disabling the IPv6 on NIC didn't help either.

**Comment by asemarafa** [comment] 2022-11-24 10:41
The CDN has a zero byte source.msix for me in Ireland (CDN here points to 152.199.21.175), resetting the sources did not help.

Updating my hosts file (```C:\Windows\System32\drivers\etc\hosts```) with USA's CDN IP worked for me

```
152.195.19.97           cdn.winget.microsoft.com
```

**Comment by mgthantzin** [comment] 2022-11-25 06:54
If you don't wish to touch your `hosts` file, you can try connecting to a VPN.

**Comment by BuffaloMacnCheese** [comment] 2022-12-13 13:23
I'm still currently experiencing this issue. Is there an update on the status of this? 

My winget sources are pointed to the MSStore 
```
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
```

`Winget source reset --force ` seems to work successfully. Then I'll run `Winget source update --force` which again, appears to run successfully. 
When I go to upgrade packages I get the following error `Failed when searching source; results will not be included: winget
No installed package found matching input criteria.`

I'm hopping on this thread a little late so please let me know if a solution or fix has already been posted.

**Comment by Trenly** [comment] 2022-12-14 01:55
> I'm still currently experiencing this issue. Is there an update on the status of this?
> 
> My winget sources are pointed to the MSStore and to the winget CDN (US-East)
> 
> ```
> msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
> winget  https://cdn.winget.microsoft.com/cache
> ```
> 
> `Winget source reset --force ` seems to work successfully. Then I'll run `Winget source update --force` which again, appears to run successfully. When I go to upgrade packages I get the following error `Failed when searching source; results will not be included: winget No installed package found matching input criteria.`
> 
> I'm hopping on this thread a little late so please let me know if a solution or fix has already been posted.

I don't see the same issue. Have you tried re-installing the latest version of winget?

**Comment by BuffaloMacnCheese** [comment] 2022-12-14 12:42
Hey @Trenly , Thanks for the response. 

Yesterday I downloaded and reinstalled the "latest" version of winget and the issue persisted.
This AM I downloaded and installed the preview version. 
I just downloaded and installed the preview version and tried to run the same command `winget upgrade ` , 
and I'm getting this error running winget from an elevated command prompt: 
```

C:\Windows\System32>winget -v
v1.4.3132-preview

C:\Windows\System32>winget upgrade
Failed when searching source; results will not be included: winget
No installed package found matching input criteria.

C:\Windows\System32>
```
Additionally, this error running winget in elevated powershell terminal:
```
PS C:\WINDOWS\system32> winget upgrade --all --force
Failed when searching source: winget
An unexpected error occurred while executing the command:
0x8a15000f : Data required by the source is missing
PS C:\WINDOWS\system32>
```
I've reset the sources and updated them to no avail.

**Comment by efie45** [comment] 2022-12-19 15:57
I'm having an issue with this as well. It appears to still be an issue with the winget cdn. 

Payload from the winget source cache `https://cdn.winget.microsoft.com/cache` looks like:

```xml
<Error>
<Code>ResourceNotFound</Code>
<Message>The specified resource does not exist. RequestId:3469c4ef-b01e-0026-60be-1332d3000000 Time:2022-12-19T15:24:44.6112948Z</Message>
</Error>
```

**Comment by Trenly** [comment] 2022-12-20 19:08
@efie45 and @BuffaloMacnCheese - If I may ask, what general region(s) are you in? Understanding which countries are effected may help the team at Microsoft pinpoint specific CDN servers that are having issues

**Comment by efie45** [comment] 2022-12-20 19:10
@Trenly I am accessing from a box in Wisconsin, US

**Comment by Trenly** [comment] 2022-12-20 19:11
> @Trenly I am accessing from a box in Wisconsin, US

Interesting - @denelon - I'm from the same region, and I'm not experiencing the issue; It may not be location based 😟

**Comment by denelon** [comment] 2022-12-20 19:17
Thanks @Trenly. We've been trying to determine what heuristic might be hitting us. It's essentially come down to knowing which IP address the name is resolving to, and then doing a force reset on that endpoint to get it to start behaving properly.

**Comment by BuffaloMacnCheese** [comment] 2022-12-20 20:59
@Trenly , My region is South East US.

**Closed** 2023-01-27 03:04 UTC
Labels: Issue-Bug

**Comment by hubertsvk** [comment] 2023-09-27 10:06
hello 
problem is here again, nothing helped, 


PS C:\Users\hubka> winget source reset --force
Resetting all sources...Done
PS C:\Users\hubka> winget source update --verbose-logs
Updating all sources...
Updating source: msstore...
Done
Updating source: winget...
Cancelled
PS C:\Users\hubka> winget -v
v1.6.2631
PS C:\Users\hubka>

**Comment by Carsten0001** [comment] 2023-09-27 11:10
Same here. 😞 
Does this have anything to do with the fact that the Winget Source:
https://cdn.winget.microsoft.com/cache 
returns:
![image](https://github.com/microsoft/winget-pkgs/assets/24300487/c28903e0-dd4c-4f1b-9ac1-933c28b878c4)

**Comment by pascal456** [comment] 2023-09-27 15:56
@Trenly you once reopened and closed this, is it again the same problem?
For me there is the same problem like in the two posts above.

```
PowerShell 7.3.7
PS C:\Windows\System32> winget update
Failed in attempting to update the source: winget
Failed when searching source; results will not be included: winget
No installed package found matching input criteria.
```

**Comment by mdanish-kh** [comment] 2023-09-27 16:05
> Same here. 😞 Does this have anything to do with the fact that the Winget Source: [cdn.winget.microsoft.com/cache](https://cdn.winget.microsoft.com/cache) returns: ![image](https://user-images.githubusercontent.com/24300487/270958268-c28903e0-dd4c-4f1b-9ac1-933c28b878c4.png)

The correct URL for winget source is https://cdn.winget.microsoft.com/cache/source.msix

@pascal456 This issue is related to https://github.com/microsoft/winget-cli/issues/3687

**Comment by Trenly** [comment] 2023-09-27 18:14
> you once reopened and closed this, is it again the same problem?

No, it is not the same

**Comment by denelon** [comment] 2023-09-27 18:57
Hey all, we're tracking this at:
* https://github.com/microsoft/winget-cli/issues/3652
