### ISSUE TITLE
[Package Issue]: Microsoft.VCRedist.2015+.x64

### ISSUE THREAD

**Issue by TaliaFlor** [microsoft/winget-pkgs#84721] opened 2022-10-17 22:58 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

After successfuly updating to the latest version, winget still shows package as having an update. If I try upgrading againg, it still shows the package as needing upgrade.

![image](https://user-images.githubusercontent.com/47438099/196298528-bbf12f5e-21fd-433e-97f7-2c33f7ebc703.png)

<img width="960" alt="2022-10-17_19-43" src="https://user-images.githubusercontent.com/47438099/196297995-7490694a-528e-489d-a2d0-5aec9a3df477.png">

### Steps to reproduce

`winget upgrade` &rarr; to verify that package needs upgrade

`winget upgrade -h --all` &rarr; to upgrade package

`winget upgrade` &rarr; to verify that package has been upgraded

### Actual behavior

Package is not upgrading properly or winget is not getting the upgraded version number.

### Expected behavior

Package upgrades successfuly and `winget upgrade` shows nothing after.

### Environment

```shell
Gerenciador de Pacotes do Windows v1.3.2691
Copyright (c) Microsoft Corporation. Todos os direitos reservados.

Windows: Windows.Desktop v10.0.22000.978
Arquitetura do Sistema: X64
Pacote: Microsoft.DesktopAppInstaller v1.18.2691.0
```

**Comment by Trenly** [comment] 2022-10-18 01:57
Duplicate of -
* https://github.com/microsoft/winget-cli/issues/2448
* https://github.com/microsoft/winget-cli/issues/2427

**Comment by krystofkrticka** [comment] 2022-10-19 09:10
I also had this happen to me but when I opened appwiz.cpl I was able to see duplicate names but some of them either didn't have version number or version number was older but there was always latest version. So winget might have issue with older version.

**Comment by TaliaFlor** [comment] 2022-10-24 23:29
Hey, sorry for the delay,but I finally tested the proposed solution and it worked!
![image](https://user-images.githubusercontent.com/47438099/197648940-d1f05412-0cd8-4828-bcfa-aeda5a84400c.png)

**Comment by WinkelCode** [comment] 2022-11-05 22:25
The workaround of installing the x86 package worked for me as well, but it would be nice if that wasn't a problem in the first place.

**Comment by Trenly** [comment] 2024-04-30 19:30
Several other issues are tracking issues related to VC Runtimes and side-by-side. I'm closing this issue in favor of the work over at the CLI.

###### Close with reason: Tracked at CLI;

**Closed** 2024-04-30 19:30 UTC
Labels: Issue-Bug
