### ISSUE TITLE
[New Feature]: Have a way to set package specific settings such as a certain version or no upgrade.

### ISSUE THREAD

**Issue by ETHREAL1** [microsoft/winget-pkgs#35127] opened 2021-11-17 02:15 UTC
### Description of the new feature/enhancement

There are times where an older version of a package may be needed like an old version of Python or Java for example. It would be nice to have a way to have package-specific settings such as a certain version or a no upgrade flag. Installation settings would also be a nice touch such as with Java. you could have an argument that only installs say the 64bit version.

### Proposed technical implementation details (optional)

As an added argument that is then saved in some way.

Example: winget install "Java 8" -v "7.9" -64bit -noupgrade

**Comment by Trenly** [comment] 2021-11-17 03:22
Duplicate of microsoft/winget-cli#476

**Comment by denelon** [comment] 2021-11-17 17:10
Duplicate of microsoft/winget-cli#476

A couple of other related issues are:
* microsoft/winget-cli/issues/163
* microsoft/winget-cli/issues/906

**Closed** 2021-11-17 17:12 UTC
Labels: Resolution-Duplicate

**Comment by denelon** [comment] 2021-11-17 17:22
@ETHREAL1 we've identified this Issue as a duplicate of another one that already exists. This specific instance is being closed in favor of tracking the concern over on the referenced Issue. Thanks for your report! Be sure to add your 👍 to the other issue to help raise the priority.
