### ISSUE TITLE
[Package Request]: FileZilla

### ISSUE THREAD

**Issue by salmonshark** [microsoft/winget-pkgs#185054] opened 2024-10-22 17:43 UTC
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://filezilla-project.org/download.php?show_all=1
Publisher: FileZilla
Package Name: FileZillaClientx64
Description:  FileZilla Client x64
Package Version:  3.67.1
Installer Url:  https://dl1.cdn.filezilla-project.org/client/FileZilla_3.67.1_win64-setup.exe?h=vvQE_cSQtpagMo14hFQU9Q&x=1729622380

I tried to use wingetcreate to maybe publish my first time but keep running into an error:  Failed to download installer.  Would either like someone to help me, or get this created.

Ultimately would like to have both x64 and x86 versions available.

FileZilla.FileZilla.Client.x64
FileZilla.FileZilla.Client.x86

**Comment by Trenly** [comment] 2024-10-22 19:35
Duplicate of #173955

**Closed** 2024-10-22 19:35 UTC
Labels: Help-Wanted, Package-Request

**Comment by binarygeek119** [comment] 2024-11-18 21:56
https://github.com/microsoft/winget-pkgs/issues/154585#issuecomment-2484210085
