### ISSUE TITLE
Mattermost 4.7 Issues

### ISSUE THREAD

**Issue by ageekhere** [microsoft/winget-pkgs#18934] opened 2021-06-26 07:55 UTC
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

I have Mattermost 4.6.2 install from https://mattermost.com/download
There are 2 issues, 
1. winget upgrade does not show the new update.
Note if i do winget list i get 
Mattermost 4.6.2 0cc73166-b7d0-592b-8d95-6cbe304083a6 4.6.2
2. If i do winget install mattermost i get Installer failed with exit code: 2

# Expected behavior
An update of mattermost is found.

No update is found.
Cannot install using winget install mattermost when mattermost Mattermost 4.6.2 0cc73166-b7d0-592b-8d95-6cbe304083a6 4.6.2 is installed

# Environment

```none
[winget --info]
Windows Package Manager v1.0.11451
Windows: Windows.Desktop Version	10.0.19043 Build 19043
Package: Microsoft.DesktopAppInstaller 1.11.11451.0

Mattermost 4.6.2 0cc73166-b7d0-592b-8d95-6cbe304083a6 4.6.2
```

**Comment by quhxl** [comment] 2021-06-26 15:46
The error has been fixed. However, the issue did not close due to a wrong keyword.

**Comment by ageekhere** [comment] 2021-06-27 05:31
I still get Installer failed with exit code: 2

**Comment by quhxl** [comment] 2021-06-27 05:37
That's weird. The update is now displayed and I can install it without problems. I can not reproduce the error.

**Comment by ageekhere** [comment] 2021-06-27 05:40
Does upgrading work as well for you?

**Comment by quhxl** [comment] 2021-06-27 05:41
Yes, it does work.

**Comment by quhxl** [comment] 2021-06-27 05:44
Maybe it's because of the MSI installer we use. If you installed it with the EXE installer before, there may be problems.

**Comment by ageekhere** [comment] 2021-06-27 05:45
Ah yeah i get NSIS Error

**Comment by ageekhere** [comment] 2021-06-27 05:50
Is upgrading from the EXE fixable? or do you need to uninstall and reinstall using MSI?

**Comment by quhxl** [comment] 2021-06-27 05:59
It's weird. When I type `winget upgrade Mattermost` it takes the MSI installer and when I type `winget install Mattermost` it takes the EXE installer. Maybe you can get it to work that way.

**Comment by ageekhere** [comment] 2021-06-27 06:04
Weird, if i do winget install Mattermost while mattermost is still installed i also get the error

**Comment by quhxl** [comment] 2021-06-27 06:10
I don't get an error no matter which installer I use. Have you tried to update with: `winget upgrade Mattermost -i`? Maybe you will get more information that way.

**Comment by ageekhere** [comment] 2021-06-27 06:27
Sadly it does not, hmm

**Comment by ageekhere** [comment] 2021-06-27 09:22
After a reboot it now works.

**Comment by quhxl** [comment] 2021-06-27 10:00
Good, then you can simply close the issue.

**Closed** 2021-06-27 12:53 UTC
Labels: Needs: Triage
