### ISSUE TITLE
[Package Issue]: Microsoft.DotNet.DesktopRuntime

### ISSUE THREAD

**Issue by ppvnf** [microsoft/winget-pkgs#82561] opened 2022-10-06 00:22 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

This applies to:
Microsoft.DotNet.DesktopRuntime.6
Microsoft.DotNet.DesktopRuntime.5
Microsoft.DotNet.DesktopRuntime.3_1

1. The x86 versions are missing.
Download links: 
https://dotnet.microsoft.com/en-us/download/dotnet/3.1
https://dotnet.microsoft.com/en-us/download/dotnet/5.0
https://dotnet.microsoft.com/en-us/download/dotnet/6.0

2. Microsoft.DotNet.DesktopRuntime.5 is not correctly identified by Winget:
![Captura de tela 2022-10-05 210556](https://user-images.githubusercontent.com/73800734/194185409-43216ed1-7346-4185-9f7f-928b0f78ecc1.png)

3. x86 versions are misidentified after I manually installed them (they have the same identifier as x64 versions):
![Captura de tela 2022-10-05 211533](https://user-images.githubusercontent.com/73800734/194186322-6ca7d555-e82b-4744-b58f-85f700a02d06.png)

### Steps to reproduce

`winget list`

### Actual behavior

- x86 versions missing
- Microsoft.DotNet.DesktopRuntime.5 misidentified 
- x86 versions misidentified 

### Expected behavior

Being able to use Winget to install x86 versions and correctly identify them.

### Environment

```shell
Gerenciador de Pacotes do Windows v1.3.2091
Copyright (c) Microsoft Corporation. Todos os direitos reservados.

Windows: Windows.Desktop v10.0.19044.2006
Arquitetura do Sistema: X64
Pacote: Microsoft.DesktopAppInstaller v1.18.2091.0
```

**Comment by ppvnf** [comment] 2022-10-06 00:25
I guess the 3rd problem is duplicate of https://github.com/microsoft/winget-cli/issues/2448, but at least IMO 1 and 2 are different

**Comment by Trenly** [comment] 2022-10-06 02:17
1) The x86 links are there. Use `winget install Microsoft.DotNet.DesktopRuntime.5 --architecture x86` to install the x86 version
https://github.com/microsoft/winget-pkgs/blob/8d373efba3b79e307a92029a2576c6f2eb40a33d/manifests/m/Microsoft/DotNet/DesktopRuntime/5/5.0.17/Microsoft.DotNet.DesktopRuntime.5.installer.yaml#L28-L35
https://github.com/microsoft/winget-pkgs/blob/8d373efba3b79e307a92029a2576c6f2eb40a33d/manifests/m/Microsoft/DotNet/DesktopRuntime/3_1/3.1.29/Microsoft.DotNet.DesktopRuntime.3_1.installer.yaml#L21-L30
https://github.com/microsoft/winget-pkgs/blob/8d373efba3b79e307a92029a2576c6f2eb40a33d/manifests/m/Microsoft/DotNet/DesktopRuntime/6/6.0.9/Microsoft.DotNet.DesktopRuntime.6.installer.yaml#L31-L40

2) Created a PR to fix the correlation, linked above

3) They aren't misidentified at all. They have the same package identifier in the output because they do have the same identifier, and they are intended to. Certainly microsoft/winget-cli#2448 is an issue, but this isn't a case where the identifiers are intended to be separate. If they were intended to be separate the [Installation guide](https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net60#install-the-runtime) wouldn't install the architecture which is applicable to the system. With them being the same package identifier, the x86 runtime will be installed on x86 versions of Windows and the x64 runtime will be installed on x64 versions of Windows unless the `--architecture` switch is specified

**Comment by ppvnf** [comment] 2022-10-06 02:49
>     3. They aren't misidentified at all. They have the same package identifier in the output because they do have the same identifier, and they are intended to. Certainly [x86 is detected outdated, x64 is installed despite already up-to-date winget-cli#2448](https://github.com/microsoft/winget-cli/issues/2448) is an issue, but this isn't a case where the identifiers are intended to be separate. If they were intended to be separate the [Installation guide](https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net60#install-the-runtime) wouldn't install the architecture which is applicable to the system. With them being the same package identifier, the x86 runtime will be installed on x86 versions of Windows and the x64 runtime will be installed on x64 versions of Windows unless the `--architecture` switch is specified

Thank you. However, I don't totally understand why the x86 versions aren't separate packages. Correct me if I am wrong, but some programs need x86 versions of .NET Desktop Runtimes, even in x64 systems. 

For example, Microsoft Visual C++ Redistributables have different packages for x86 and x64 architectures, because the x86 version may be necessary in x64 systems. 

However, as .NET Desktop Runtimes doesn't have both versions as separate packages, does it mean it's not necessary to install the x86 versions when the x64 ones are already installed?

**Comment by Trenly** [comment] 2022-10-06 03:09
I'm not an expert on the .NET runtimes; Perhaps when this gets triaged someone from MSFT can chime in on that question

**Comment by ppvnf** [comment] 2022-10-07 09:46
> For example, Microsoft Visual C++ Redistributables have different packages for x86 and x64 architectures, because the x86 version may be necessary in x64 systems.
> 
> However, as .NET Desktop Runtimes don't have both versions as separate packages, does it mean it's not necessary to install the x86 versions when the x64 ones are already installed?

@denelon, could you please confirm if this is the case?

**Comment by jedieaston** [comment] 2022-10-07 12:33
> x86 versions when the x64 ones are already installed

I can confirm that (at least for certain versions of .NET) this is not the case. I've seen apps that try to install the x86 runtime on x64 and refuse to run without it. They shouldn't be doing that, but they do.

**Comment by ppvnf** [comment] 2022-10-13 11:58
This also seems related to **https://github.com/microsoft/winget-cli/issues/2129**

**Closed** 2022-10-13 12:44 UTC
Labels: Issue-Bug
