### ISSUE TITLE
Some apps keep updating over and over again

### ISSUE THREAD

**Issue by UsefulVid** [microsoft/winget-pkgs#16070] opened 2021-06-03 20:37 UTC
# Brief description of your issue
Some Apps keep updating over and over again
# Steps to reproduce

run
winget upgrade --all
and again
winget upgrade --all

# Expected behavior
after the first execution, it should not find any new packages in the second run executed a second later

# Actual behavior

It repeats to update some apps
```
PS C:\Windows\system32> winget upgrade --all
Gefunden OpenVPN Connect [OpenVPNTechnologies.OpenVPNConnect]
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Downloading https://swupdate.openvpn.net/downloads/connect/openvpn-connect-3.2.3.1851_signed.msi
  ██████████████████████████████  48.4 MB / 48.4 MB
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Erfolgreich installiert

Gefunden Strawberry Perl [StrawberryPerl.StrawberryPerl]
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Downloading https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit.msi
  ██████████████████████████████   102 MB /  102 MB
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Erfolgreich installiert

PS C:\Windows\system32> winget upgrade --all
Gefunden OpenVPN Connect [OpenVPNTechnologies.OpenVPNConnect]
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Downloading https://swupdate.openvpn.net/downloads/connect/openvpn-connect-3.2.3.1851_signed.msi
  ██████████████████████████████  48.4 MB / 48.4 MB
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Erfolgreich installiert

Gefunden Strawberry Perl [StrawberryPerl.StrawberryPerl]
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Downloading https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit.msi
  ██████████████████████████████   102 MB /  102 MB
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Erfolgreich installiert
```

# Environment

[winget --info]
Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19041.685
Paket: Microsoft.DesktopAppInstaller v1.11.11451.0

Any other software?
no

**Comment by KaranKad** [comment] 2021-06-03 20:40
Can you show me how this applications are displayed in control panel with their versions and all.

**Comment by denelon** [comment] 2021-06-03 20:40
Duplicate of #https://github.com/microsoft/winget-cli/issues/1075

Thanks for all the help @KaranKad 😊

**Comment by UsefulVid** [comment] 2021-06-03 20:41
Damn I tried to find if someone posted already.
Sorry for the duplicate.
Do you still need my software list?

**Comment by KaranKad** [comment] 2021-06-03 20:43
> Do you still need my software list?

Sure, I will update the version according to the control panel ones so that it won't prompt for upgrade again.

**Comment by denelon** [comment] 2021-06-03 20:43
@UsefulVid  no worries, it's cross repository so it's a bit messy.

**Comment by UsefulVid** [comment] 2021-06-03 20:45
OpenVPN Connect:
![grafik](https://user-images.githubusercontent.com/39967070/120709394-15e31a00-c4bd-11eb-97a4-97e92351dd1e.png)

Strawberry Perl:
![grafik](https://user-images.githubusercontent.com/39967070/120709557-45922200-c4bd-11eb-8915-aa476953b7ea.png)

**Comment by KaranKad** [comment] 2021-06-03 20:55
@OfficialEsco pushed fixes and added x64 version of Strawberry Perl which was missing.

**Comment by inceptusp** [comment] 2021-06-06 11:44
I am having this issue too but with `Google.AndroidStudio`... I have Android Studio 4.2.1 and winget informs that I need to update to 4.2.1, I run `winget upgrade --all` and it downoads and install the updates, when I run `winget upgrade` again it says the same thing, that I have to upgrade to 4.2.1...

**Comment by OfficialEsco** [comment] 2021-06-06 13:32
@inceptusp this appears to be because Google don't use the full version in Windows.
Windows Reports it as 4.2 instead of 4.2.1.0.

**Comment by ItzLevvie** [comment] 2021-07-15 22:03
> I am having this issue too but with `Google.AndroidStudio`... I have Android Studio 4.2.1 and winget informs that I need to update to 4.2.1, I run `winget upgrade --all` and it downoads and install the updates, when I run `winget upgrade` again it says the same thing, that I have to upgrade to 4.2.1...

The issue with `Google.AndroidStudio` should be fixed now.

**Comment by leochras** [comment] 2021-09-01 15:53
These packages also have this issue..
![image](https://user-images.githubusercontent.com/16163571/131703650-bd2c59b1-3d07-4e45-8725-d0b1ba8d5e08.png)

**Comment by vedantmgoyal2009** [comment] 2021-09-01 16:00
> These packages also have this issue..
> ![image](https://user-images.githubusercontent.com/16163571/131703650-bd2c59b1-3d07-4e45-8725-d0b1ba8d5e08.png)

I guess you are referring to the first two packages because those applications don't register their version in the registry.

**Comment by leochras** [comment] 2021-09-01 16:04
> > These packages also have this issue..
> > ![image](https://user-images.githubusercontent.com/16163571/131703650-bd2c59b1-3d07-4e45-8725-d0b1ba8d5e08.png)
> 
> I guess you are referring to the first two packages because those applications don't register their version in the registry.

No, I tried reinstalling all of them and upgrading them multiple times with no success..

**Comment by OfficialEsco** [comment] 2021-09-01 16:08
`REAPER` and `obs-asio`: Sadly you need to add a DisplayVersion manually to the registry since the developer have not

`VC++2013`: it probably installed a newer version and they are now installed side-by-side, this will be fixed tonight by adding `uninstallPrevious` since VC++2013 does not upgrade itself

`Python 3`: i'm unsure if we should implement uninstallPrevious for this, does it matter what Python Version you have installed? or is it just the Major version that matters?

`Synology Drive Client`: Did this install twice? if so we can add `uninstallPrevious`

**Comment by leochras** [comment] 2021-09-01 16:18
> `REAPER` and `obs-asio`: Sadly you need to add a DisplayVersion manually to the registry since the developer have not
> 
> `VC++2013`: it probably installed a newer version and they are now installed side-by-side, this will be fixed tonight by adding `uninstallPrevious` since VC++2013 does not upgrade itself
> 
> `Python 3`: i'm unsure if we should implement uninstallPrevious for this, does it matter what Python Version you have installed? or is it just the Major version that matters?
> 
> `Synology Drive Client`: Did this install twice? if so we can add `uninstallPrevious`

I need multiple versions of Python for testing, how would I go about updating them?
Synology Drive Client is only installed once..

**Comment by vedantmgoyal2009** [comment] 2021-09-01 16:46
> > I need multiple versions of Python for testing, how would I go about updating them?
> 
> Multiple version of Python 3? Then this is a very special case

I guess that would be fixed by schema 1.1.0

**Comment by denelon** [comment] 2021-09-01 16:58
https://github.com/microsoft/winget-pkgs/discussions/26635

**Comment by OfficialEsco** [comment] 2021-09-17 21:11
@denelon i was referring to you for this btw
> I actually realized this is a issue with how winget installs the program, /qb and /passive works as expected in Powershell, and it DOES update, however the registry string does not get updated

**Comment by leochras** [comment] 2021-10-05 16:49
I think this belongs here. I am also facing this issue and I use multiple versions of python, so this is really annoying

https://github.com/microsoft/winget-cli/issues/1550

**Comment by Trenly** [comment] 2021-11-07 01:03
After reading through the comments, I think this should be closed, as the packages which can be fixed appear to have been fixed, and the issues which remain have separate issues filed against them, which will be used to track anything that is still pending.

**Closed** 2021-11-07 12:06 UTC
Labels: Help-Wanted

**Comment by ElPistoler0** [comment] 2022-08-18 00:05
Same issue

Opera Stable 89.0.4447.83 Opera.Opera 89.0.4447.83 89.0.4447.91 winget

Please and thank you.

**Comment by hros** [comment] 2023-11-22 00:50
> These packages also have this issue.. ![image](https://user-images.githubusercontent.com/16163571/131703650-bd2c59b1-3d07-4e45-8725-d0b1ba8d5e08.png)

Android Studio is always being updated by winget
It is a large download (>1GB)
