### ISSUE TITLE
127891

### ISSUE THREAD

**Issue by fwadnjar** [microsoft/winget-pkgs#128406] opened 2023-11-28 14:54 UTC
<samp>
Azure Pipelines successfully started running 1 pipeline(s).<br>

</samp>

_Originally posted by @azure-pipelines[bot] in https://github.com/microsoft/winget-pkgs/issues/127891#issuecomment-1824769308_

**Comment by mdanish-kh** [comment] 2023-11-28 15:13
Duplicate of #128404

**Closed** 2023-11-28 15:13 UTC
Labels: Needs-Triage
