### ISSUE TITLE
[Package Issue]: Microsoft.VCRedist.2015+.x64 14.34.31931.0

### ISSUE THREAD

**Issue by thedoggybrad** [microsoft/winget-pkgs#103205] opened 2023-04-22 22:48 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Microsoft.VCRedist.2015+.x64 14.34.31931.0

Updating all my packages using the winget upgrade --all command updates this product. Then after typing it again, then it upgrades this again. After a day, this updates again.

Weird Issue

### Steps to reproduce

Install this Microsoft.VCRedist.2015+.x64 14.34.31931.0
Type winget upgrade --all and let it finish
then
Type winget upgrade --all and let it finish
then 
Restart your PC 
Type winget upgrade --all and let it finish
then
Shutdown your PC and wait for approximately 10 hours
Type winget upgrade --all and let it finish

### Actual behavior

PowerShell 7.3.4
PS C:\Users\**********> winget upgrade --all
Name                                                    Id                           Version       Available     Source
-----------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x86) -… Microsoft.VCRedist.2015+.x64 14.34.31931.0 14.34.31938.0 winget
1 upgrades available.
1 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.

(1/1) Found Microsoft Visual C++ 2015-2022 Redistributable (x64) [Microsoft.VCRedist.2015+.x64] Version 14.34.31938.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.visualstudio.microsoft.com/download/pr/8b92f460-7e03-4c75-a139-e264a770758d/26C2C72FBA6438F5E29AF8EBC4826A1E424581B3C446F8C735361F1DB7BEFF72/VC_redist.x64.exe
  ██████████████████████████████  24.3 MB / 24.3 MB
Successfully verified installer hash
Starting package install...
Successfully installed

1 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.

PS C:\Users\**********> winget upgrade --all
Name                                                    Id                           Version       Available     Source
-----------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x86) -… Microsoft.VCRedist.2015+.x64 14.34.31931.0 14.34.31938.0 winget
1 upgrades available.
1 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.

(1/1) Found Microsoft Visual C++ 2015-2022 Redistributable (x64) [Microsoft.VCRedist.2015+.x64] Version 14.34.31938.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.visualstudio.microsoft.com/download/pr/8b92f460-7e03-4c75-a139-e264a770758d/26C2C72FBA6438F5E29AF8EBC4826A1E424581B3C446F8C735361F1DB7BEFF72/VC_redist.x64.exe
  ███▋                            3.00 MB / 24.3 MB
Package download canceled.

Cancelled
1 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.

### Expected behavior

PowerShell 7.3.4
PS C:\Users\**********> winget upgrade --all
Name                                                    Id                           Version       Available     Source
-----------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x86) -… Microsoft.VCRedist.2015+.x64 14.34.31931.0 14.34.31938.0 winget
1 upgrades available.
1 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.

(1/1) Found Microsoft Visual C++ 2015-2022 Redistributable (x64) [Microsoft.VCRedist.2015+.x64] Version 14.34.31938.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.visualstudio.microsoft.com/download/pr/8b92f460-7e03-4c75-a139-e264a770758d/26C2C72FBA6438F5E29AF8EBC4826A1E424581B3C446F8C735361F1DB7BEFF72/VC_redist.x64.exe
  ██████████████████████████████  24.3 MB / 24.3 MB
Successfully verified installer hash
Starting package install...
Successfully installed

1 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
PS C:\Users\**********> winget upgrade --all
1 upgrades available.
1 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.

### Environment

```raw
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1555
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

[WinGet-2023-04-23-06-47-11.692.log](https://github.com/microsoft/winget-pkgs/files/11302435/WinGet-2023-04-23-06-47-11.692.log)
[WinGet-2023-04-23-06-47-16.475.log](https://github.com/microsoft/winget-pkgs/files/11302436/WinGet-2023-04-23-06-47-16.475.log)
[WinGetCOM-2023-04-16-19-23-31.063.log](https://github.com/microsoft/winget-pkgs/files/11302437/WinGetCOM-2023-04-16-19-23-31.063.log)
[WinGetCOM-2023-04-20-19-01-41.066.log](https://github.com/microsoft/winget-pkgs/files/11302438/WinGetCOM-2023-04-20-19-01-41.066.log)
[WinGet-Microsoft.VCRedist.2015+.x64.14.34.31938.0-2023-04-20-19-07-58.825.log](https://github.com/microsoft/winget-pkgs/files/11302439/WinGet-Microsoft.VCRedist.2015%2B.x64.14.34.31938.0-2023-04-20-19-07-58.825.log)
[WinGet-Microsoft.VCRedist.2015+.x64.14.34.31938.0-2023-04-20-19-07-58.825_000_vcRuntimeMinimum_x64.log](https://github.com/microsoft/winget-pkgs/files/11302440/WinGet-Microsoft.VCRedist.2015%2B.x64.14.34.31938.0-2023-04-20-19-07-58.825_000_vcRuntimeMinimum_x64.log)
[WinGet-Microsoft.VCRedist.2015+.x64.14.34.31938.0-2023-04-20-19-07-58.825_001_vcRuntimeAdditional_x64.log](https://github.com/microsoft/winget-pkgs/files/11302441/WinGet-Microsoft.VCRedist.2015%2B.x64.14.34.31938.0-2023-04-20-
[WinGet-2023-04-21-21-11-52.758.log](https://github.com/microsoft/winget-pkgs/files/11302446/WinGet-2023-04-21-21-11-52.758.log)
[WinGet-2023-04-22-19-12-17.072.log](https://github.com/microsoft/winget-pkgs/files/11302447/WinGet-2023-04-22-19-12-17.072.log)
19-07-58.825_001_vcRuntimeAdditional_x64.log)
[WinGet-Microsoft.VCRedist.2015+.x64.14.34.31938.0-2023-04-22-19-14-38.100.log](https://github.com/microsoft/winget-pkgs/files/11302442/WinGet-Microsoft.VCRedist.2015%2B.x64.14.34.31938.0-2023-04-22-19-14-38.100.log)
[WinGet-Microsoft.VCRedist.2015+.x64.14.34.31938.0-2023-04-23-06-42-57.962.log](https://github.com/microsoft/winget-pkgs/files/11302443/WinGet-Microsoft.VCRedist.2015%2B.x64.14.34.31938.0-2023-04-23-06-42-57.962.log)
[WinGet-2023-04-17-19-24-50.897.log](https://github.com/microsoft/winget-pkgs/files/11302444/WinGet-2023-04-17-19-24-50.897.log)
[WinGet-2023-04-20-19-01-52.887.log](https://github.com/microsoft/winget-pkgs/files/11302445/WinGet-2023-04-20-19-01-52.887.log)
[WinGet-2023-04-22-19-13-23.458.log](https://github.com/microsoft/winget-pkgs/files/11302448/WinGet-2023-04-22-19-13-23.458.log)
[WinGet-2023-04-22-19-13-34.285.log](https://github.com/microsoft/winget-pkgs/files/11302449/WinGet-2023-04-22-19-13-34.285.log)
[WinGet-2023-04-22-19-13-59.448.log](https://github.com/microsoft/winget-pkgs/files/11302450/WinGet-2023-04-22-19-13-59.448.log)
[WinGet-2023-04-22-19-14-13.070.log](https://github.com/microsoft/winget-pkgs/files/11302451/WinGet-2023-04-22-19-14-13.070.log)
[WinGet-2023-04-22-19-27-07.551.log](https://github.com/microsoft/winget-pkgs/files/11302452/WinGet-2023-04-22-19-27-07.551.log)
[WinGet-2023-04-22-19-34-51.995.log](https://github.com/microsoft/winget-pkgs/files/11302453/WinGet-2023-04-22-19-34-51.995.log)
[WinGet-2023-04-22-19-39-27.379.log](https://github.com/microsoft/winget-pkgs/files/11302454/WinGet-2023-04-22-19-39-27.379.log)
[WinGet-2023-04-22-19-49-13.127.log](https://github.com/microsoft/winget-pkgs/files/11302455/WinGet-2023-04-22-19-49-13.127.log)
[WinGet-2023-04-22-19-54-34.900.log](https://github.com/microsoft/winget-pkgs/files/11302456/WinGet-2023-04-22-19-54-34.900.log)
[WinGet-2023-04-22-19-56-49.231.log](https://github.com/microsoft/winget-pkgs/files/11302457/WinGet-2023-04-22-19-56-49.231.log)
[WinGet-2023-04-22-19-57-34.130.log](https://github.com/microsoft/winget-pkgs/files/11302458/WinGet-2023-04-22-19-57-34.130.log)
[WinGet-2023-04-22-20-09-12.139.log](https://github.com/microsoft/winget-pkgs/files/11302459/WinGet-2023-04-22-20-09-12.139.log)
[WinGet-2023-04-22-21-16-24.506.log](https://github.com/microsoft/winget-pkgs/files/11302460/WinGet-2023-04-22-21-16-24.506.log)
[WinGet-2023-04-22-21-31-34.220.log](https://github.com/microsoft/winget-pkgs/files/11302461/WinGet-2023-04-22-21-31-34.220.log)
[WinGet-2023-04-23-05-47-21.444.log](https://github.com/microsoft/winget-pkgs/files/11302462/WinGet-2023-04-23-05-47-21.444.log)
[WinGet-2023-04-23-06-42-18.592.log](https://github.com/microsoft/winget-pkgs/files/11302463/WinGet-2023-04-23-06-42-18.592.log)
[WinGet-2023-04-23-06-42-47.151.log](https://github.com/microsoft/winget-pkgs/files/11302464/WinGet-2023-04-23-06-42-47.151.log)
[WinGet-2023-04-23-06-43-09.463.log](https://github.com/microsoft/winget-pkgs/files/11302466/WinGet-2023-04-23-06-43-09.463.log)
[WinGet-2023-04-23-06-47-08.504.log](https://github.com/microsoft/winget-pkgs/files/11302468/WinGet-2023-04-23-06-47-08.504.log)

**Comment by Trenly** [comment] 2023-04-23 12:55
* See https://github.com/microsoft/winget-cli/issues/2995

**Comment by Trenly** [comment] 2023-05-01 14:40
Duplicate of https://github.com/microsoft/winget-cli/issues/2427

**Closed by Trenly** 2023-05-01 14:40 UTC
Labels: Issue-Bug
